import Link from "next/link";
import SiteHeader from "@/components/site/SiteHeader";
import SiteFooter from "@/components/site/SiteFooter";
import { Phone } from "@/components/site/Phone";
import { Btn, Container, Eyebrow, H2, Lead, S, Section } from "@/components/site/ui";

export const metadata = { title: "About MrBuilder", description: "Outdoor installation and service should be easy to access, coordinate and follow." };

const PRINCIPLES = [["A quote before a commitment", "Nobody is booked until the customer has seen an itemized price and approved it."], ["One status, every side", "A single set of job stages shared by the consumer app, the contractor app and partner accounts."], ["Evidence over argument", "Checklists, before-work evidence and completion photos are part of every job, so issues are resolved on facts."], ["Confirmation releases payment", "The customer confirms the finished work; only then is the contractor paid. Reported issues put payment on hold."], ["Care continues after the install", "MrCare maintenance and electronics protection keep the relationship going past the first job."], ["Honest about what's live", "Where a capability is planned rather than built, like the company portal, we say so."]];
const STORY: [string, string[]][] = [
  ["Our story started in 2020", ["MrBuilder first took shape in 2020 as a team handling installation and service for the pergolas our own company sold.", "Working directly with products and customers gave us a practical understanding of what happens after a sale. We saw how much the final experience depends on the people who assemble, install, troubleshoot, and maintain the system.", "We also recognized that the same challenges extended far beyond our own customers. Manufacturers needed dependable installation support. Dealers needed help with after-sales service. Customers needed someone they could turn to long after their purchase.", "What started as a team supporting our own projects became the foundation for a bigger idea: make installation and service more accessible across the outdoor living industry."]],
  ["Connecting products, people, and professionals", ["We are developing MrBuilder around two connected apps: one for customers and one for contractors.", "Our goal is to bring the people who need installation, maintenance, repairs, and technical support together with professionals who can carry out the work.", "For homeowners, that means a clearer path from purchasing a product to having it installed and cared for. For restaurants and hotels, it means support for outdoor spaces that are part of the guest experience. For manufacturers and sellers, it means a service network that can help them support customers beyond their immediate location.", "Whether a product comes from a local showroom, an online retailer, or an overseas manufacturer, our vision is to make dependable local support easier to find."]],
  ["Creating opportunities for skilled people", ["Building that network also means creating opportunities.", "There are many capable tradespeople and hands-on professionals who have the skills and motivation to do great work but need a way to enter this growing field.", "We are building a pathway for them to register through the contractor app, complete relevant training and onboarding, and join the MrBuilder network as installation and service professionals.", "As outdoor systems become more advanced, product knowledge matters as much as practical ability. Our aim is to help professionals develop both, while connecting them with opportunities to put those skills to work."]],
  ["Helping businesses reach further", ["For a manufacturer or seller, entering a new market involves more than shipping a product. Customers also need installation and someone to call afterward.", "Our long-term vision is to help businesses reach more cities with confidence, supported by a growing network of local professionals. As coverage expands, MrBuilder can help connect product delivery with installation and provide a path for future maintenance, repairs, and technical support.", "That gives businesses room to grow and customers greater freedom to choose the products that suit them."]],
  ["Support beyond the sale", ["A well-designed outdoor space should remain a place to enjoy for years to come. Making that possible takes skilled installation, ongoing care, and people who understand the systems behind it.", "We created MrBuilder to bring those pieces together.", "For the customer ready to enjoy their space. For the business ready to reach new markets. For the professional ready to build a future in a growing industry.", "That's why we're building MrBuilder."]],
];

export default function AboutPage() {
  return (
    <>
      <div className="bg-[#181D27] text-white"><SiteHeader dark /><Container className="pb-16 pt-10 lg:pb-24 lg:pt-16"><Eyebrow color="text-[#F7A26B]">About MrBuilder</Eyebrow><h1 className="max-w-3xl text-[40px] font-bold leading-[1.05] tracking-tight md:text-[56px]">Outdoor installation and service should be easy to access, coordinate and follow.</h1><p className="mt-6 max-w-2xl text-[17px] leading-7 text-[#D5D7DA]">That's the whole purpose. MrBuilder is a platform that connects outdoor living installation, repair and service needs with the professionals who carry out the work, and keeps everyone looking at the same job.</p></Container></div>

      <Section><Container className="grid items-center gap-10 lg:grid-cols-[1fr_1.3fr]"><div className="rounded-[28px] bg-[#FAFAFA] p-10 text-center"><img src="/site/brand/mrb-lockup.png" alt="Mr. Builder" className="mx-auto w-full max-w-[360px]" /><div className="mt-4 text-[13px] font-bold uppercase tracking-wide text-gray-500">Since 2020</div></div><div><Eyebrow>The problem we're solving</Eyebrow><H2>A pergola takes an afternoon to sell and a decade to own.</H2><Lead>In between are quotes, installers, schedules, motors that stop responding and warranties nobody can find. We built MrBuilder so that all of it lives in one place.</Lead><div className="mt-6 flex flex-wrap gap-2">{["For the homeowner", "For the contractor doing the work", "For the company that sold the product"].map((x) => <span key={x} className="rounded-full border border-gray-300 px-3 py-1.5 text-[13px] font-medium text-gray-700">{x}</span>)}</div></div></Container></Section>

      <Section className="bg-[#FAFAFA]"><Container><Eyebrow>Our story</Eyebrow><H2>Built on experience. Created to fill a gap.</H2><Lead>MrBuilder began with a simple observation: buying a pergola should be the beginning of enjoying it, with dependable support every step of the way.</Lead>
        <div className="mt-10 grid gap-4 md:grid-cols-3">{[["2020", "MrBuilder takes shape as the installation and service team for the pergolas our own company sold."], ["Now", "Two connected apps, one for customers and one for contractors, launching in the United States."], ["Next", "A growing network of local professionals that helps businesses reach more cities with confidence."]].map(([t, b]) => <div key={t} className="rounded-[20px] border border-gray-200 bg-white p-6"><div className="text-[24px] font-bold text-[#EF6820]">{t}</div><p className="mt-2 text-[15px] leading-6 text-gray-600">{b}</p></div>)}</div>
        <div className="mt-12 max-w-3xl space-y-4 text-[17px] leading-7 text-gray-700"><p>After more than a decade in the pergola and outdoor structure industry, our founder saw the market grow into an industry of its own. New manufacturers entered the space. Showrooms opened. Product choices expanded. Homeowners, restaurants, and hotels began investing in outdoor spaces that could do more, with motorized roofs, retractable screens, integrated lighting, heating, and smart controls.</p><p>But one essential part of that experience was too often missing: reliable installation and ongoing service.</p><p>Who installs the product after it arrives? Who adjusts the system when something isn't working properly? Who helps when a motor stops responding, a screen needs repair, or the original seller is hundreds of miles away?</p><p>These were challenges we encountered firsthand. They became the reason for MrBuilder.</p></div>
        <div className="mt-12 grid gap-10 md:grid-cols-2">{STORY.map(([h, ps]) => <div key={h}><h3 className="text-[22px] font-bold text-[#181D27]">{h}</h3><div className="mt-3 space-y-3 text-[15px] leading-7 text-gray-600">{ps.map((p) => <p key={p}>{p}</p>)}</div></div>)}</div></Container></Section>

      <Section><Container><Eyebrow>How it connects</Eyebrow><H2>Three sides of one job.</H2><Lead>Every request on MrBuilder moves through a shared set of statuses. What a homeowner sees as "Contractor assigned", the contractor sees as "Accepted", and a partner company sees in its request list. Same job, same moment, three views.</Lead><div className="mt-10 grid gap-6 md:grid-cols-3">{[["Consumers", "Request, approve, follow, confirm.", "Homeowners describe what they need, approve an itemized quote, follow the visit and confirm the finished work before paying. Afterwards, MrCare offers ongoing maintenance and electronics protection.", "/for-consumers", "For Consumers →"], ["Contractors", "Find work, do it well, get confirmed.", "Vetted professionals accept priced, scheduled jobs that match their skills, run them with checklists and proof photos, and communicate in the job thread. Inspections they perform become the quotes customers approve.", "/for-contractors", "For Contractors →"], ["Companies", "Sell, submit, track.", "Pergola companies submit installation, repair and service requests for products they've sold and follow each one in a partner account, while MrBuilder coordinates the work and the after-sales service.", "/partner", "Partner With Us →"]].map(([e, h, b, href, l]) => <div key={e} className="rounded-[20px] border border-gray-200 bg-white p-6"><Eyebrow>{e}</Eyebrow><div className="text-[20px] font-bold text-[#181D27]">{h}</div><p className="mt-2 text-[15px] leading-6 text-gray-600">{b}</p><Link href={href} className="mt-4 inline-block font-semibold text-[#B93815]">{l}</Link></div>)}</div></Container></Section>

      <Section className="bg-[#FAFAFA]"><Container><Eyebrow>How we work</Eyebrow><H2>Principles built into the product.</H2><div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{PRINCIPLES.map(([t, b]) => <div key={t} className="rounded-[20px] border border-gray-200 bg-white p-6"><div className="text-[18px] font-bold text-[#181D27]">{t}</div><p className="mt-2 text-[15px] leading-6 text-gray-600">{b}</p></div>)}</div></Container></Section>

      <Section className="bg-[#181D27] text-white"><Container className="grid items-center gap-10 lg:grid-cols-2"><div><Eyebrow color="text-[#F7A26B]">Where we are</Eyebrow><h2 className="text-[34px] font-bold leading-tight">Starting in the United States. Building to expand internationally.</h2><p className="mt-4 text-[16px] leading-7 text-[#D5D7DA]">We're launching in the U.S. first and opening areas as we onboard contractors and partner companies. The apps are built for that path from day one: feet and metres, 12-hour and 24-hour time, and a string table ready for additional languages.</p><div className="mt-6 flex flex-wrap items-center gap-4"><Btn href="/partner#inquiry">Apply to Partner</Btn><Link href="/" className="font-semibold text-white/80">Back to Home</Link></div></div><div className="flex justify-center gap-4"><Phone src={S("c-home")} alt="Consumer app: Home" className="w-1/2" /><Phone src={S("k-marketplace")} alt="Contractor app: Marketplace" className="mt-8 w-1/2" /></div></Container></Section>
      <SiteFooter />
    </>
  );
}
