// Cart · Checkout · Order placed · My orders · Order details · Track order · Saved addresses
import React, { useCallback, useEffect, useState } from "react";
import { Alert, Image, Linking, Pressable, ScrollView, Text as RNText, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { useFocusEffect, useNavigation, useRoute } from "@react-navigation/native";
import { NativeStackNavigationProp } from "@react-navigation/native-stack";
import { Ionicons } from "@expo/vector-icons";
import { Header, Sheet } from "../../components/sheet";
import { Field, PrimaryButton, SecondaryButton } from "../../components/form";
import { api, APP_VARIANT } from "../../api/client";
import { useSession } from "../../auth/session";
import { useTheme } from "../../theme/ThemeProvider";
import { font } from "../../theme/tokens";
import { RootParams } from "../../navigation";
import { Address, Cart, Order, loadCart, money, orderStatus } from "./store";

const useS = () => { const { c } = useTheme(); return (n: number, w: "400" | "500" | "600" | "700" = "400", col = c.text) => ({ fontSize: n, fontFamily: w === "400" ? font.regular : w === "500" ? font.medium : w === "600" ? font.semibold : font.bold, color: col }); };
const Card = ({ children, style }: { children: React.ReactNode; style?: object }) => { const { c } = useTheme(); return <View style={[{ backgroundColor: c.surface, borderWidth: 1, borderColor: c.border, borderRadius: 16, padding: 14, gap: 10 }, style]}>{children}</View>; };
const Totals = ({ sub, ship, total, count }: { sub: number; ship: number; total: number; count?: number }) => { const { c } = useTheme(); const S = useS(); return <Card>{[[`Subtotal${count ? ` · ${count} item${count > 1 ? "s" : ""}` : ""}`, money(sub), c.text], ["Delivery", ship ? money(ship) : "Free", ship ? c.text : "#079455"]].map(([k, v, col]) => <View key={k as string} style={{ flexDirection: "row", justifyContent: "space-between" }}><RNText style={S(14, "400", c.text4)}>{k as string}</RNText><RNText style={S(14, "500", col as string)}>{v as string}</RNText></View>)}<View style={{ flexDirection: "row", justifyContent: "space-between", alignItems: "center", paddingTop: 8, borderTopWidth: 1, borderTopColor: c.border }}><RNText style={S(15, "600")}>Total</RNText><RNText style={S(22, "700")}>{money(total)}</RNText></View></Card>; };

export function StoreCartScreen() {
  const nav = useNavigation<NativeStackNavigationProp<RootParams>>();
  const { params } = useRoute<{ key: string; name: string; params?: { jobId?: string } }>();
  const { c } = useTheme(); const S = useS();
  const [cart, setCart] = useState<Cart | null>(null);
  const load = useCallback(async () => { const r = await loadCart(params?.jobId); setCart(r.data ?? null); }, [params?.jobId]);
  useFocusEffect(useCallback(() => { load(); }, [load]));
  const qty = async (id: string, q: number) => { if (q <= 0) await api(`/store/cart/items/${id}`, { method: "DELETE" }); else await api(`/store/cart/items/${id}`, { method: "PATCH", body: { qty: q } }); load(); };
  const items = cart?.items ?? [];
  return (
    <SafeAreaView edges={["top"]} style={{ flex: 1, backgroundColor: c.bg }}>
      <Header title="Cart" onBack={() => nav.goBack()} />
      <ScrollView contentContainerStyle={{ padding: 16, gap: 12 }}>
        {items.length === 0 ? <View style={{ alignItems: "center", gap: 8, paddingTop: 48 }}><View style={{ width: 56, height: 56, borderRadius: 16, backgroundColor: c.surface, borderWidth: 1, borderColor: c.border, alignItems: "center", justifyContent: "center" }}><Ionicons name="cart-outline" size={26} color={c.primary} /></View><RNText style={S(17, "600")}>Your cart is empty</RNText><RNText style={{ ...S(14, "400", c.text4), textAlign: "center" }}>Louvers, motors, lighting and hardware for your next pergola job.</RNText><PrimaryButton title="Browse the store" onPress={() => nav.navigate("StoreProducts", {})} style={{ alignSelf: "stretch", marginTop: 8, height: 44 }} /></View>
          : <><Card style={{ gap: 0 }}>{items.map((it, i) => <View key={it.id} style={{ flexDirection: "row", gap: 12, paddingVertical: 10, borderTopWidth: i ? 1 : 0, borderTopColor: c.border }}><View style={{ width: 64, height: 64, borderRadius: 12, backgroundColor: "#fff", borderWidth: 1, borderColor: c.border, alignItems: "center", justifyContent: "center", overflow: "hidden" }}>{it.image_url ? <Image source={{ uri: it.image_url }} style={{ width: 52, height: 52 }} resizeMode="contain" /> : <Ionicons name="cube-outline" size={24} color={c.text4} />}</View><View style={{ flex: 1, gap: 8 }}><View style={{ flexDirection: "row", justifyContent: "space-between", gap: 8 }}><RNText style={{ flex: 1, ...S(14, "500") }} numberOfLines={2}>{it.name}</RNText><RNText style={S(15, "700")}>{money(it.amount)}</RNText></View><View style={{ flexDirection: "row", alignItems: "center", justifyContent: "space-between" }}><View style={{ flexDirection: "row", alignItems: "center", borderWidth: 1, borderColor: c.border2, borderRadius: 10 }}><Pressable onPress={() => qty(it.id, it.qty - 1)} style={{ width: 32, height: 32, alignItems: "center", justifyContent: "center" }}><RNText style={S(16, "400", c.text2)}>−</RNText></Pressable><RNText style={{ width: 26, textAlign: "center", ...S(14, "600") }}>{it.qty}</RNText><Pressable onPress={() => qty(it.id, it.qty + 1)} style={{ width: 32, height: 32, alignItems: "center", justifyContent: "center" }}><RNText style={S(16, "400", c.text2)}>+</RNText></Pressable></View><Pressable onPress={() => qty(it.id, 0)} style={{ width: 32, height: 32, alignItems: "center", justifyContent: "center" }}><Ionicons name="trash-outline" size={18} color={c.text4} /></Pressable></View></View></View>)}</Card>
            {cart?.job_id && <View style={{ padding: 10, paddingHorizontal: 12, borderRadius: 10, backgroundColor: c.primarySoft }}><RNText style={S(13, "400", c.orange)}>Parts for job <RNText style={S(13, "700", c.orange)}>{cart.request_code}</RNText> · shipped to the job address</RNText></View>}
            <Totals sub={cart!.subtotal} ship={cart!.shipping_fee} total={cart!.total} count={items.reduce((a, i) => a + i.qty, 0)} />
            <PrimaryButton title={`Checkout · ${money(cart!.total)}`} onPress={() => nav.navigate("StoreCheckout", { jobId: params?.jobId })} /></>}
      </ScrollView>
    </SafeAreaView>
  );
}

export function StoreCheckoutScreen() {
  const nav = useNavigation<NativeStackNavigationProp<RootParams>>();
  const { params } = useRoute<{ key: string; name: string; params?: { jobId?: string } }>();
  const { user } = useSession();
  const { c } = useTheme(); const S = useS();
  const [cart, setCart] = useState<Cart | null>(null); const [addrs, setAddrs] = useState<Address[]>([]); const [addr, setAddr] = useState<string>(""); const [pms, setPms] = useState<{ id: string; label: string | null; card_brand: string | null; card_last_four: string | null; is_default: boolean }[]>([]); const [pm, setPm] = useState(""); const [method, setMethod] = useState<"card" | "cash">("card"); const [payMode, setPayMode] = useState<"contractor" | "customer_account">("contractor"); const [busy, setBusy] = useState(false); const [done, setDone] = useState<Order | null>(null);
  useEffect(() => { (async () => { const [ct, a, p] = await Promise.all([loadCart(params?.jobId), api<Address[]>("/store/addresses"), api<{ id: string; label: string | null; card_brand: string | null; card_last_four: string | null; is_default: boolean }[]>("/payment-methods")]); setCart(ct.data ?? null); setAddrs(a.data ?? []); setAddr((a.data ?? []).find((x) => x.is_default)?.id ?? a.data?.[0]?.id ?? ""); setPms(p.data ?? []); const d = (p.data ?? []).find((x) => x.is_default) ?? p.data?.[0]; setPm(d?.id ?? ""); if (!d) setMethod(ct.data?.cod_enabled ? "cash" : "card"); })(); }, [params?.jobId]);
  const A = addrs.find((x) => x.id === addr); const forJob = !!cart?.job_id;
  async function place() { setBusy(true); const r = await api<Order>("/store/orders", { method: "POST", body: { payment_method: method, payment_method_id: method === "card" ? pm || undefined : undefined, address_id: forJob ? undefined : addr || undefined, job_id: cart?.job_id ?? undefined, pay_mode: forJob ? payMode : undefined } }); setBusy(false); if (!r.success || !r.data) { Alert.alert("Couldn't place order", r.error ?? "Try again"); return; } setDone(r.data); }
  if (done) return (
    <SafeAreaView edges={["top"]} style={{ flex: 1, backgroundColor: c.bg }}><ScrollView contentContainerStyle={{ padding: 16, paddingTop: 40, gap: 16, alignItems: "center" }}><View style={{ width: 72, height: 72, borderRadius: 36, backgroundColor: c.okBg, alignItems: "center", justifyContent: "center" }}><View style={{ width: 50, height: 50, borderRadius: 25, backgroundColor: "#079455", alignItems: "center", justifyContent: "center" }}><Ionicons name="checkmark" size={28} color="#fff" /></View></View><RNText style={S(22, "700")}>Order placed!</RNText><RNText style={{ ...S(14, "400", c.text3), textAlign: "center" }}>Order #{done.order_number} · {money(done.total)}{method === "cash" ? " · pay the courier on delivery" : ""}{forJob && payMode === "customer_account" ? " · added to the client's invoice for approval" : ""}</RNText><View style={{ alignSelf: "stretch", gap: 10, marginTop: 8 }}><PrimaryButton title="Track order" onPress={() => nav.replace("StoreOrder", { id: done.id })} /><SecondaryButton title="Continue shopping" onPress={() => nav.navigate("Store", {})} /></View></ScrollView></SafeAreaView>
  );
  return (
    <SafeAreaView edges={["top"]} style={{ flex: 1, backgroundColor: c.bg }}>
      <Header title="Checkout" onBack={() => nav.goBack()} />
      <ScrollView contentContainerStyle={{ padding: 16, gap: 14 }}>
        <View style={{ gap: 6 }}><RNText style={S(13.5, "500", c.text2)}>Phone number</RNText><View style={{ height: 50, borderRadius: 12, borderWidth: 1, borderColor: c.border2, backgroundColor: c.surface, paddingHorizontal: 14, flexDirection: "row", alignItems: "center", gap: 10 }}><RNText style={S(15, "500")}>US (+1)</RNText><RNText style={S(15, "400")}>{user?.phone ?? "Add a phone in your profile"}</RNText></View></View>
        <Card><View style={{ flexDirection: "row", justifyContent: "space-between", alignItems: "center" }}><View style={{ flexDirection: "row", alignItems: "center", gap: 8 }}><Ionicons name="location-outline" size={18} color={c.text2} /><RNText style={S(15, "600")}>Delivery address</RNText></View>{!forJob && <Pressable onPress={() => nav.navigate("StoreAddresses")}><RNText style={S(13, "600", c.orange)}>Add new</RNText></Pressable>}</View>
          {forJob ? <View style={{ padding: 12, borderRadius: 12, backgroundColor: c.primarySoft }}><RNText style={S(14, "600")}>Job site · {cart?.request_code}</RNText><RNText style={S(12.5, "400", c.text3)}>Shipped to the job address on file.</RNText></View> : addrs.length === 0 ? <View style={{ flexDirection: "row", alignItems: "center", gap: 8, padding: 10, borderRadius: 10, backgroundColor: c.warnBg }}><Ionicons name="alert-circle-outline" size={16} color={c.warn} /><RNText style={S(13, "500", c.warn)}>Please add a delivery address to proceed</RNText></View> : addrs.map((a) => <Pressable key={a.id} onPress={() => setAddr(a.id)} style={{ height: 56, borderRadius: 12, borderWidth: 1.5, borderColor: addr === a.id ? c.primary : c.border, backgroundColor: addr === a.id ? c.primarySoft : c.surface, paddingHorizontal: 14, flexDirection: "row", alignItems: "center", justifyContent: "space-between" }}><View><RNText style={S(14, "600")}>{a.label ?? "Address"}</RNText><RNText style={S(12.5, "400", c.text4)} numberOfLines={1}>{a.line1}, {a.city}{a.state ? `, ${a.state}` : ""} {a.zip_code ?? ""}</RNText></View><Ionicons name={addr === a.id ? "radio-button-on" : "radio-button-off"} size={20} color={addr === a.id ? c.primary : c.border2} /></Pressable>)}</Card>
        {forJob && APP_VARIANT === "contractor" && <Card><RNText style={S(15, "600")}>Who pays for these parts?</RNText>{[["contractor", "I pay now", "Reimbursed on the job invoice per your agreement"], ["customer_account", "Add to client's invoice", "Client approves in their app before shipping"]].map(([k, t, s]) => <Pressable key={k} onPress={() => setPayMode(k as "contractor")} style={{ height: 60, borderRadius: 12, borderWidth: 1.5, borderColor: payMode === k ? c.primary : c.border, backgroundColor: payMode === k ? c.primarySoft : c.surface, paddingHorizontal: 14, flexDirection: "row", alignItems: "center", justifyContent: "space-between" }}><View><RNText style={S(14, "600")}>{t}</RNText><RNText style={S(12.5, "400", c.text4)}>{s}</RNText></View><Ionicons name={payMode === k ? "radio-button-on" : "radio-button-off"} size={20} color={payMode === k ? c.primary : c.border2} /></Pressable>)}</Card>}
        {(!forJob || payMode === "contractor") && <Card><View style={{ flexDirection: "row", justifyContent: "space-between", alignItems: "center" }}><View style={{ flexDirection: "row", alignItems: "center", gap: 8 }}><Ionicons name="card-outline" size={18} color={c.text2} /><RNText style={S(15, "600")}>Payment method</RNText></View><Pressable onPress={() => nav.navigate("PayoutMethod")}><RNText style={S(13, "600", c.orange)}>Add new</RNText></Pressable></View>
          <View style={{ flexDirection: "row", backgroundColor: c.surface3, borderRadius: 10, padding: 3 }}>{(["card", "cash"] as const).filter((m) => m === "card" || cart?.cod_enabled).map((m) => <Pressable key={m} onPress={() => setMethod(m)} style={{ flex: 1, height: 36, borderRadius: 8, backgroundColor: method === m ? c.surface : "transparent", alignItems: "center", justifyContent: "center" }}><RNText style={S(13.5, "600", method === m ? c.text : c.text4)}>{m === "card" ? "Bank card" : "Cash"}</RNText></Pressable>)}</View>
          {method === "cash" ? <View style={{ flexDirection: "row", gap: 8, padding: 10, borderRadius: 10, backgroundColor: c.infoBg }}><Ionicons name="cash-outline" size={16} color={c.info} /><RNText style={{ flex: 1, ...S(13, "400", c.info) }}><RNText style={S(13, "700", c.info)}>Pay {money(cart?.total)} in cash on delivery.</RNText> Have exact change ready — the courier can't give change over ${cart?.cod_max_change ?? 20}. Cash orders can't be canceled after packing.</RNText></View>
            : pms.length === 0 ? <View style={{ flexDirection: "row", alignItems: "center", gap: 8, padding: 10, borderRadius: 10, backgroundColor: c.warnBg }}><Ionicons name="alert-circle-outline" size={16} color={c.warn} /><RNText style={S(13, "500", c.warn)}>Please add a payment method to complete your order</RNText></View>
            : pms.map((p) => <Pressable key={p.id} onPress={() => setPm(p.id)} style={{ height: 52, borderRadius: 12, borderWidth: 1.5, borderColor: pm === p.id ? c.primary : c.border, backgroundColor: pm === p.id ? c.primarySoft : c.surface, paddingHorizontal: 14, flexDirection: "row", alignItems: "center", gap: 10 }}><View style={{ width: 40, height: 24, borderRadius: 5, backgroundColor: "#1A1F71", alignItems: "center", justifyContent: "center" }}><RNText style={S(9, "700", "#fff")}>{(p.card_brand ?? "CARD").toUpperCase()}</RNText></View><RNText style={{ flex: 1, ...S(14, "600") }}>•••• •••• •••• {p.card_last_four}</RNText><Ionicons name={pm === p.id ? "radio-button-on" : "radio-button-off"} size={20} color={pm === p.id ? c.primary : c.border2} /></Pressable>)}</Card>}
        {cart && <Totals sub={cart.subtotal} ship={cart.shipping_fee} total={cart.total} count={cart.items.reduce((a, i) => a + i.qty, 0)} />}
      </ScrollView>
      <View style={{ padding: 12, paddingHorizontal: 16, paddingBottom: 30, backgroundColor: c.surface, borderTopWidth: 1, borderTopColor: c.border }}><PrimaryButton title={forJob && payMode === "customer_account" ? "Send to client for approval" : `Place order · ${money(cart?.total)}`} onPress={place} loading={busy} disabled={!cart || (!forJob && !A) || ((!forJob || payMode === "contractor") && method === "card" && !pm)} /></View>
    </SafeAreaView>
  );
}

export function StoreOrdersScreen() {
  const nav = useNavigation<NativeStackNavigationProp<RootParams>>();
  const { c } = useTheme(); const S = useS();
  const [orders, setOrders] = useState<Order[]>([]); const [loading, setLoading] = useState(true);
  const load = useCallback(async () => { const r = await api<Order[]>("/store/orders"); setOrders(r.data ?? []); setLoading(false); }, []);
  useFocusEffect(useCallback(() => { load(); }, [load]));
  const tone = (t: string) => ({ ok: [c.okBg, c.ok], warn: [c.warnBg, c.warn], info: [c.infoBg, c.info], err: [c.errBg, c.err], neutral: [c.surface2, c.text3] }[t] ?? [c.surface2, c.text3]);
  return (
    <SafeAreaView edges={["top"]} style={{ flex: 1, backgroundColor: c.bg }}>
      <Header title="My orders" onBack={() => nav.goBack()} />
      <ScrollView contentContainerStyle={{ padding: 16, gap: 12 }}>
        {loading && [1, 2, 3].map((k) => <View key={k} style={{ height: 112, borderRadius: 16, backgroundColor: c.surface2 }} />)}
        {!loading && orders.length === 0 && <View style={{ alignItems: "center", gap: 8, paddingTop: 48 }}><Ionicons name="receipt-outline" size={30} color={c.text4} /><RNText style={S(17, "600")}>No orders yet</RNText></View>}
        {orders.map((o) => { const st = orderStatus[o.status] ?? orderStatus.paid; const [bg, fg] = tone(st.tone); return <Pressable key={o.id} onPress={() => nav.navigate("StoreOrder", { id: o.id })} style={{ backgroundColor: c.surface, borderWidth: 1, borderColor: c.border, borderRadius: 16, padding: 14, gap: 12 }}><View style={{ flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start" }}><View><RNText style={S(15, "600")}>Order #{o.order_number}</RNText><RNText style={S(12.5, "400", c.text4)}>{new Date(o.created_at).toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" })} · {o.items.reduce((a, i) => a + i.qty, 0)} items</RNText></View><View style={{ paddingHorizontal: 8, paddingVertical: 3, borderRadius: 999, backgroundColor: bg }}><RNText style={S(12, "600", fg)}>{st.label}</RNText></View></View><View style={{ flexDirection: "row", justifyContent: "space-between", alignItems: "center" }}><View style={{ flexDirection: "row", gap: 6 }}>{o.items.slice(0, 3).map((it, i) => <View key={i} style={{ width: 44, height: 44, borderRadius: 10, backgroundColor: "#fff", borderWidth: 1, borderColor: c.border, alignItems: "center", justifyContent: "center", overflow: "hidden" }}>{it.image_url ? <Image source={{ uri: it.image_url }} style={{ width: 34, height: 34 }} resizeMode="contain" /> : <Ionicons name="cube-outline" size={18} color={c.text4} />}</View>)}</View><View style={{ alignItems: "flex-end" }}><RNText style={S(12, "400", c.text4)}>Total</RNText><RNText style={S(17, "700")}>{money(o.total)}</RNText></View></View></Pressable>; })}
      </ScrollView>
    </SafeAreaView>
  );
}

export function StoreOrderScreen() {
  const nav = useNavigation<NativeStackNavigationProp<RootParams>>();
  const { params } = useRoute<{ key: string; name: string; params: { id: string; track?: boolean } }>();
  const { c } = useTheme(); const S = useS();
  const [o, setO] = useState<Order | null>(null); const [track, setTrack] = useState(!!params.track); const [report, setReport] = useState(false); const [reason, setReason] = useState("");
  const load = useCallback(async () => { const r = await api<Order>(`/store/orders/${params.id}`); setO(r.data ?? null); }, [params.id]);
  useFocusEffect(useCallback(() => { load(); }, [load]));
  if (!o) return <SafeAreaView style={{ flex: 1, backgroundColor: c.bg }}><Header title="Order" onBack={() => nav.goBack()} /></SafeAreaView>;
  const st = orderStatus[o.status] ?? orderStatus.paid; const tone = { ok: [c.okBg, c.ok], warn: [c.warnBg, c.warn], info: [c.infoBg, c.info], err: [c.errBg, c.err], neutral: [c.surface2, c.text3] }[st.tone];
  const STEPS = ["paid", "packing", "shipped", "delivered"]; const idx = STEPS.indexOf(o.status); const tl = o.timeline ?? [];
  const at = (s: string) => tl.find((x) => x.status === s)?.at;
  const fmt = (v?: string | null) => v ? new Date(v).toLocaleString("en-US", { month: "short", day: "numeric", hour: "numeric", minute: "2-digit" }) : undefined;
  const canCancel = ["pending", "paid"].includes(o.status) && !(o.payment_method === "cash" && o.status !== "pending");
  const addr = o.address ? [o.address.line1, o.address.city, o.address.state, o.address.zip_code].filter(Boolean).join(", ") : "Job site";
  if (track) return (
    <SafeAreaView edges={["top"]} style={{ flex: 1, backgroundColor: c.bg }}>
      <Header title="Track order" onBack={() => setTrack(false)} />
      <ScrollView contentContainerStyle={{ padding: 16, gap: 12 }}>
        <View style={{ height: 170, borderRadius: 16, backgroundColor: c.surface2, alignItems: "center", justifyContent: "center" }}><View style={{ height: 32, paddingHorizontal: 12, borderRadius: 999, backgroundColor: c.surface, flexDirection: "row", alignItems: "center", gap: 6 }}><Ionicons name="map-outline" size={16} color={c.text} /><RNText style={S(13, "600")}>Live map · coming with courier integration</RNText></View></View>
        <Card><View style={{ flexDirection: "row", justifyContent: "space-between" }}><View><RNText style={S(16, "700")}>Order #{o.order_number}</RNText><RNText style={S(12.5, "400", c.text4)}>{o.tracking?.number ? `Tracking number ${o.tracking.number}` : "Tracking number pending"}</RNText></View><View style={{ alignItems: "flex-end" }}><RNText style={S(12, "400", c.text4)}>Estimated</RNText><RNText style={S(18, "700", c.primary)}>{o.tracking?.eta_at ? fmt(o.tracking.eta_at) : "—"}</RNText></View></View>
          <View style={{ flexDirection: "row", alignItems: "center", gap: 10, padding: 10, borderRadius: 12, backgroundColor: c.bg }}><Ionicons name="location-outline" size={18} color={c.text2} /><View><RNText style={S(12, "400", c.text4)}>Delivery address</RNText><RNText style={S(14, "500")}>{addr}</RNText></View></View>
          <View>{STEPS.map((s, i) => { const done = i < idx || o.status === "delivered"; const cur = i === idx && o.status !== "delivered"; return <View key={s} style={{ flexDirection: "row", gap: 12 }}><View style={{ alignItems: "center", width: 26 }}>{done ? <View style={{ width: 26, height: 26, borderRadius: 13, backgroundColor: "#079455", alignItems: "center", justifyContent: "center" }}><Ionicons name="checkmark" size={15} color="#fff" /></View> : cur ? <View style={{ width: 26, height: 26, borderRadius: 13, backgroundColor: c.primarySoft, alignItems: "center", justifyContent: "center" }}><View style={{ width: 10, height: 10, borderRadius: 5, backgroundColor: c.primary }} /></View> : <View style={{ width: 26, height: 26, borderRadius: 13, borderWidth: 1, borderColor: c.border2, alignItems: "center", justifyContent: "center" }}><RNText style={S(12, "600", c.text5)}>{i + 1}</RNText></View>}{i < 3 && <View style={{ flex: 1, width: 2, backgroundColor: done ? "#079455" : c.border, marginVertical: 3 }} />}</View><View style={{ flex: 1, paddingBottom: i < 3 ? 16 : 0 }}><RNText style={S(14.5, "600", done || cur ? c.text : c.text5)}>{["Order confirmed", "Packed", "Out for delivery", "Delivered"][i]}</RNText>{fmt(at(s)) && <RNText style={S(13, "400", c.text4)}>{fmt(at(s))}</RNText>}</View></View>; })}</View></Card>
        <Card style={{ flexDirection: "row", alignItems: "center" }}><View style={{ width: 44, height: 44, borderRadius: 22, backgroundColor: c.hero, alignItems: "center", justifyContent: "center" }}><RNText style={S(13, "700", "#fff")}>{(o.tracking?.courier ?? "MS").slice(0, 2).toUpperCase()}</RNText></View><View style={{ flex: 1 }}><RNText style={S(14.5, "600")}>Contact courier</RNText><RNText style={S(12.5, "400", c.text4)}>{o.tracking?.courier ?? "The courier will contact you when your order is about to arrive."}</RNText></View>{o.tracking?.phone && <Pressable onPress={() => Linking.openURL(`tel:${o.tracking!.phone}`)} style={{ width: 44, height: 44, borderRadius: 12, backgroundColor: c.primary, alignItems: "center", justifyContent: "center" }}><Ionicons name="call-outline" size={18} color="#fff" /></Pressable>}</Card>
      </ScrollView>
    </SafeAreaView>
  );
  return (
    <SafeAreaView edges={["top"]} style={{ flex: 1, backgroundColor: c.bg }}>
      <Header title="Order details" onBack={() => nav.goBack()} />
      <ScrollView contentContainerStyle={{ padding: 16, gap: 12 }}>
        <Card><View style={{ flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start" }}><View><RNText style={S(17, "700")}>Order #{o.order_number}</RNText><RNText style={S(12.5, "400", c.text4)}>Placed on {new Date(o.created_at).toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" })}</RNText></View><View style={{ paddingHorizontal: 8, paddingVertical: 3, borderRadius: 999, backgroundColor: tone[0] }}><RNText style={S(12, "600", tone[1])}>{st.label}</RNText></View></View>
          <View style={{ flexDirection: "row", gap: 10, padding: 12, borderRadius: 12, backgroundColor: tone[0] }}><Ionicons name="information-circle-outline" size={18} color={tone[1]} /><View style={{ flex: 1 }}><RNText style={S(14, "600", tone[1])}>{st.title}</RNText><RNText style={S(13, "400", c.text2)}>{o.cancel_reason ? `Reason: ${o.cancel_reason}` : st.text}</RNText></View></View>
          {["shipped", "packing"].includes(o.status) && <>{o.tracking?.courier && <View style={{ gap: 4 }}>{[["Courier", o.tracking.courier], ["Tracking number", o.tracking.number ?? "—"]].map(([k, v]) => <View key={k} style={{ flexDirection: "row", justifyContent: "space-between" }}><RNText style={S(14, "400", c.text4)}>{k}</RNText><RNText style={S(14, "500")}>{v}</RNText></View>)}</View>}<PrimaryButton title="Track order" icon="navigate-outline" onPress={() => setTrack(true)} style={{ height: 48 }} /></>}</Card>
        <Card><RNText style={S(15, "600")}>Items ({o.items.reduce((a, i) => a + i.qty, 0)})</RNText>{o.items.map((it, i) => <View key={i} style={{ flexDirection: "row", alignItems: "center", gap: 12 }}><View style={{ width: 52, height: 52, borderRadius: 10, backgroundColor: "#fff", borderWidth: 1, borderColor: c.border, alignItems: "center", justifyContent: "center", overflow: "hidden" }}>{it.image_url ? <Image source={{ uri: it.image_url }} style={{ width: 42, height: 42 }} resizeMode="contain" /> : <Ionicons name="cube-outline" size={20} color={c.text4} />}</View><View style={{ flex: 1 }}><RNText style={S(14, "500")}>{it.name}</RNText><RNText style={S(12.5, "400", c.text4)}>Qty {it.qty}</RNText></View><RNText style={S(15, "600")}>{money(it.unit_price * it.qty)}</RNText></View>)}</Card>
        <Card>{[["location-outline", "Delivery address", o.address?.label ?? (o.job_id ? "Job site" : "Address"), addr], ["card-outline", "Payment method", o.payment_method === "cash" ? "Cash on delivery" : "Bank card", o.payment_method === "cash" ? "Pay the courier" : "Charged on confirmation"]].map(([ic, l, t, s]) => <View key={l} style={{ flexDirection: "row", gap: 12 }}><View style={{ width: 36, height: 36, borderRadius: 10, backgroundColor: c.primarySoft, alignItems: "center", justifyContent: "center" }}><Ionicons name={ic as keyof typeof Ionicons.glyphMap} size={17} color={c.primary} /></View><View style={{ flex: 1 }}><RNText style={S(12.5, "400", c.text4)}>{l}</RNText><RNText style={S(14, "600")}>{t}</RNText><RNText style={S(13.5, "400", c.text2)}>{s}</RNText></View></View>)}</Card>
        <Totals sub={o.subtotal} ship={o.shipping_fee} total={o.total} />
        <View style={{ flexDirection: "row", gap: 8 }}>{canCancel && <SecondaryButton title="Cancel order" tone="danger" style={{ flex: 1 }} onPress={() => Alert.alert("Cancel order?", undefined, [{ text: "Keep", style: "cancel" }, { text: "Cancel order", style: "destructive", onPress: async () => { await api(`/store/orders/${o.id}/cancel`, { method: "POST", body: { reason: "changed_mind" } }); load(); } }])} />}{o.status === "delivered" && <SecondaryButton title="Report a problem" style={{ flex: 1 }} onPress={() => setReport(true)} />}{["delivered", "cancelled"].includes(o.status) && <SecondaryButton title="Reorder" style={{ flex: 1 }} onPress={async () => { await api(`/store/orders/${o.id}/reorder`, { method: "POST", body: {} }); nav.navigate("StoreCart", {}); }} />}</View>
      </ScrollView>
      <Sheet open={report} onClose={() => setReport(false)} title="Report a problem"><Field label="What went wrong?" value={reason} onChangeText={setReason} placeholder="Damaged, missing item, wrong part…" /><PrimaryButton title="Send report" disabled={reason.trim().length < 5} onPress={async () => { await api(`/store/orders/${o.id}/report`, { method: "POST", body: { reason } }); setReport(false); load(); }} /></Sheet>
    </SafeAreaView>
  );
}

export function StoreAddressesScreen() {
  const nav = useNavigation();
  const { c } = useTheme(); const S = useS();
  const [list, setList] = useState<Address[]>([]); const [edit, setEdit] = useState<Partial<Address> | null>(null);
  const load = useCallback(async () => { const r = await api<Address[]>("/store/addresses"); setList(r.data ?? []); }, []);
  useFocusEffect(useCallback(() => { load(); }, [load]));
  async function save() { if (!edit?.line1 || !edit.city) return; const body = { label: edit.label ?? "Home", line1: edit.line1, line2: edit.line2, city: edit.city, state: edit.state, zip_code: edit.zip_code, is_default: edit.is_default ?? list.length === 0 }; if (edit.id) await api(`/store/addresses/${edit.id}`, { method: "PATCH", body }); else await api("/store/addresses", { method: "POST", body }); setEdit(null); load(); }
  return (
    <SafeAreaView edges={["top"]} style={{ flex: 1, backgroundColor: c.bg }}>
      <Header title="Saved addresses" onBack={() => nav.goBack()} right={<Pressable onPress={() => setEdit({ label: "Home", line1: "", city: "", state: "", zip_code: "" })} style={{ width: 40, height: 40, borderRadius: 12, backgroundColor: c.primary, alignItems: "center", justifyContent: "center" }}><Ionicons name="add" size={22} color="#fff" /></Pressable>} />
      <ScrollView contentContainerStyle={{ padding: 16, gap: 10 }}>
        {list.length === 0 && <RNText style={{ ...S(13.5, "400", c.text4), textAlign: "center", paddingTop: 24 }}>No addresses yet. Add one for deliveries.</RNText>}
        {list.map((a) => <Pressable key={a.id} onPress={() => setEdit(a)} onLongPress={() => Alert.alert("Delete address?", undefined, [{ text: "Keep", style: "cancel" }, { text: "Delete", style: "destructive", onPress: async () => { await api(`/store/addresses/${a.id}`, { method: "DELETE" }); load(); } }])} style={{ flexDirection: "row", alignItems: "center", gap: 12, backgroundColor: c.surface, borderWidth: 1, borderColor: c.border, borderRadius: 14, padding: 12, paddingHorizontal: 14 }}><View style={{ width: 38, height: 38, borderRadius: 12, backgroundColor: c.primarySoft, alignItems: "center", justifyContent: "center" }}><Ionicons name="location-outline" size={18} color={c.primary} /></View><View style={{ flex: 1 }}><RNText style={S(14.5, "600")}>{a.label ?? "Address"}</RNText><RNText style={S(12.5, "400", c.text4)}>{a.line1}{a.line2 ? `, ${a.line2}` : ""}, {a.city}{a.state ? `, ${a.state}` : ""} {a.zip_code ?? ""}</RNText></View>{a.is_default ? <View style={{ paddingHorizontal: 8, paddingVertical: 3, borderRadius: 999, backgroundColor: c.primarySoft }}><RNText style={S(12, "600", c.orange)}>Default</RNText></View> : <Pressable onPress={async () => { await api(`/store/addresses/${a.id}`, { method: "PATCH", body: { is_default: true } }); load(); }}><RNText style={S(12.5, "600", c.text4)}>Set default</RNText></Pressable>}</Pressable>)}
      </ScrollView>
      <Sheet open={!!edit} onClose={() => setEdit(null)} title={edit?.id ? "Edit address" : "New address"}>{edit && <><Field label="Label" value={edit.label ?? ""} onChangeText={(v) => setEdit({ ...edit, label: v })} placeholder="Home, Warehouse…" /><Field label="Street" value={edit.line1 ?? ""} onChangeText={(v) => setEdit({ ...edit, line1: v })} /><Field label="Apt / unit (optional)" value={edit.line2 ?? ""} onChangeText={(v) => setEdit({ ...edit, line2: v })} /><View style={{ flexDirection: "row", gap: 8 }}><View style={{ flex: 1.5 }}><Field label="City" value={edit.city ?? ""} onChangeText={(v) => setEdit({ ...edit, city: v })} /></View><View style={{ flex: 0.7 }}><Field label="State" value={edit.state ?? ""} onChangeText={(v) => setEdit({ ...edit, state: v })} autoCapitalize="words" /></View><View style={{ flex: 1 }}><Field label="ZIP" value={edit.zip_code ?? ""} onChangeText={(v) => setEdit({ ...edit, zip_code: v })} keyboardType="numeric" /></View></View><PrimaryButton title="Save address" onPress={save} disabled={!edit.line1 || !edit.city} /></>}</Sheet>
    </SafeAreaView>
  );
}
