// Mr Supply shared types/helpers
import { api } from "../../api/client";
export interface Product { id: string; sku: string; name: string; description: string | null; category: string; price: number; compare_at_price?: number | null; image_url: string | null; images?: string[]; is_top_seller: boolean; in_stock: boolean; stock_qty: number; compatible_types?: string[]; rating_avg?: number | null; reviews_count?: number; specs?: Record<string, string>; is_favorite?: boolean }
export interface Category { slug: string; name: string; image_url: string | null; product_count: number }
export interface CartItem { id: string; product_id: string; name: string; image_url: string | null; in_stock: boolean; qty: number; unit_price: number; amount: number }
export interface Cart { id: string | null; job_id: string | null; request_code?: string | null; items: CartItem[]; subtotal: number; shipping_fee: number; total: number; cod_enabled: boolean; cod_max_change: number }
export interface Address { id: string; label: string | null; recipient?: string | null; line1: string; line2?: string | null; city: string; state: string | null; zip_code: string | null; is_default: boolean }
export interface Order { id: string; order_number: string; status: string; step?: number; total: number; subtotal: number; shipping_fee: number; payment_method: string; created_at: string; items: { product_id: string; name: string; image_url: string | null; qty: number; unit_price: number }[]; address?: { label?: string | null; line1: string; city: string; state?: string | null; zip_code?: string | null } | null; tracking?: { number?: string | null; courier?: string | null; phone?: string | null; eta_at?: string | null } | null; timeline?: { status: string; at: string | null }[]; job_id?: string | null; request_code?: string | null; cancel_reason?: string | null }
export const money = (v: number | null | undefined) => v == null ? "—" : `$${Number(v).toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
export const cartKey = (jobId?: string) => jobId ? `?job_id=${jobId}` : "";
export const loadCart = (jobId?: string) => api<Cart>(`/store/cart${cartKey(jobId)}`);
export const orderStatus: Record<string, { label: string; tone: "ok" | "warn" | "info" | "err" | "neutral"; title: string; text: string }> = {
  pending: { label: "Pending", tone: "warn", title: "Waiting for payment", text: "Cash on delivery — pay the courier when it arrives." }, paid: { label: "Processing", tone: "info", title: "Order received", text: "We're preparing your items." }, packing: { label: "Packing", tone: "info", title: "Being packed", text: "Your items are being packed for shipment." },
  shipped: { label: "Out for delivery", tone: "info", title: "On its way", text: "Your order is out for delivery." }, delivered: { label: "Delivered", tone: "ok", title: "Delivered", text: "Thanks for shopping with Mr Supply." }, cancelled: { label: "Cancelled", tone: "err", title: "Order cancelled", text: "Any payment is refunded to the original method." }, reported: { label: "Issue reported", tone: "err", title: "We're looking into it", text: "Our team will contact you about this order." },
};
