import Link from "next/link";
import SiteHeader from "@/components/site/SiteHeader";
import SiteFooter from "@/components/site/SiteFooter";
import { Phone } from "@/components/site/Phone";
import { PhoneDemo } from "@/components/site/PhoneDemo";
import { QuickForm } from "@/components/site/QuickForm";
import { Faq } from "@/components/site/Faq";
import { AppBadges } from "@/components/site/AppBadges";
import { Btn, Container, Eyebrow, H2, Lead, S, Section } from "@/components/site/ui";
import { getContent } from "@/lib/content";

export const metadata = { title: "For Contractors — MrBuilder", description: "Pergola work, priced and scheduled before you accept it." };

const SERVICE_TYPES = ["Installation", "Repair", "Maintenance", "Cleaning", "Programming & Smart Controls", "Upgrades & Accessories", "Inspection & Diagnostics", "Removal & Relocation"];
const BENEFITS = [["01", "Jobs you can evaluate", "Location, distance, preferred dates, payment and the customer's description appear on the card. Structure details (type, mounting, W × L × H) are one tap away."], ["02", "Installation, repair and inspection", "Three kinds of work from the same marketplace. Inspection visits produce a report that MrBuilder prices; if the customer approves, it becomes your installation or repair job."], ["03", "Filters for your skills", "Filter the marketplace by service type, distance and dates so you only see work you can actually take."], ["04", "A schedule that fills itself", "Accepted jobs land on your calendar with the agreed dates and times. Reschedule requests from customers show up as a proposal you can accept or counter."], ["05", "Proof built into the flow", "Pre-job checklists, before-work evidence and completion photos are part of the job, shared with the customer and MrBuilder, so disputes are rare and resolvable."], ["06", "Payments you can follow", "Each job shows the payment and the platform fee before you accept. Transactions and payouts are listed in the app."]];
const JOURNEY = [
  { n: 1, chip: "Join", title: "Apply from the app.", body: "Sign-up walks through account information, address, your role, business information, insurance and skills, and final steps. Your skills use the same eight service types customers pick from, so matching is exact.", a: [S("k-onboarding"), "Onboarding: Jobs, Earnings and Mr Supply intro slides."], b: [S("k-signup"), "Sign-up · 1 of 6: Account information."] },
  { n: 2, chip: "Find work", title: "Browse the marketplace.", body: "New jobs near you appear on Home with a New tag, service type, location and distance, the customer's description, preferred dates and payment. Filter by what you do.", a: [S("k-marketplace"), "Marketplace: job cards with Decline / Accept job."], b: [S("k-filters"), "Filters sheet: service type, distance, dates."] },
  { n: 3, chip: "Review & accept", title: "Read the details, then commit.", body: "Tap Details to see the structure specs, client notes, address and request ID. Accepting notifies the customer that a contractor is assigned and adds the job to your schedule.", a: [S("k-job-accepted"), "Job: Accepted: timeline, preferred dates, payment, pre-job checklist."], b: [S("k-schedule"), "Schedule: accepted jobs by day."] },
  { n: 4, chip: "Communicate", title: "Message the client in the job thread.", body: "Each job has its own chat. Ask questions before you arrive, share updates during the work and send photos. The customer sees the same thread in their app.", a: [S("k-messages"), "Messages: conversations grouped by job."], b: [S("k-chat"), "Chat: job conversation with the client."] },
  { n: 5, chip: "Inspect (when the job calls for it)", title: "Report facts. MrBuilder prices them.", body: "On an inspection job you record findings and photos and submit a structured report. MrBuilder generates the quote from it; the customer approves in their app and the work converts to a job you can take.", a: [S("k-inspection-report"), "Inspection report & quote sheet: findings, photos, itemized lines, payout preview."], b: [S("k-insp-sent"), "Inspection sent: waiting for the customer's approval."] },
  { n: 6, chip: "Do the work", title: "Update progress as you go.", body: "Complete the pre-job checklist, tap Start job, and the customer's timeline moves to In progress. When you're done, mark the job complete with proof photos and a note.", a: [S("k-job-started"), "Job: Started: checklist done, progress steps, Mark completed."], b: [S("k-job-waiting"), "Job: Awaiting client confirmation."] },
  { n: 7, chip: "Complete", title: "The customer confirms. The job closes.", body: "Once the customer confirms the finished work, the job is marked Client confirmed & paid, moves to your History and appears in Payments & transactions.", a: [S("k-job-completed"), "Job: Completed: Client confirmed & paid."], b: [S("k-payments"), "Payments & transactions."] },
];
const DEMO = JOURNEY.map((j) => ({ screen: j.a[0], title: j.chip, caption: j.title }));
const FAQ: [string, string][] = [["What kinds of jobs are on MrBuilder?", "Pergola installation, repair, maintenance, cleaning, programming & smart controls, upgrades & accessories, inspection & diagnostics, and removal & relocation. Jobs come from homeowners using the consumer app and from partner companies that sold the product."], ["Do I have to accept every job I'm shown?", "No. Each card has Decline and Accept. You only commit to jobs whose scope, dates and payment work for you."], ["Who sets the price?", "MrBuilder prices each job, from the customer's request details or from an inspector's report, and shows the payment and platform fee on the card before you accept."], ["What is an inspection job?", "A short site visit where you record findings and photos in a structured report. MrBuilder turns the report into a quote for the customer; if they approve, the resulting job appears for acceptance."], ["What happens if the customer reports an issue?", "Payment is held while you review their feedback. You can fix the issue, propose a return visit, or raise a dispute for MrBuilder to review. Every step is visible to both sides."], ["Can I cancel after accepting?", "Yes, with a reason. The job is re-offered to other contractors and the customer is notified. Cancellation terms will be published with the contractor agreement."], ["Where is MrBuilder available?", "We are starting in the United States. We'll announce new areas as we open them."]];

export default async function ForContractorsPage() {
  const content = await getContent();
  return (
    <>
      <div className="relative overflow-hidden bg-[#181D27] text-white"><video className="absolute inset-0 h-full w-full object-cover opacity-40 motion-reduce:hidden" autoPlay muted loop playsInline poster="/site/video/bg-waitlist.jpg"><source src="/site/video/bg-waitlist.mp4" type="video/mp4" /></video><div className="absolute inset-0 bg-gradient-to-b from-[#181D27]/60 via-[#181D27]/30 to-[#181D27]" /><div className="relative"><SiteHeader dark />
        <Container className="grid items-start gap-10 pb-16 pt-8 lg:grid-cols-[1fr_460px] lg:pb-24 lg:pt-14"><div className="pt-6"><Eyebrow color="text-[#F7A26B]">For contractors</Eyebrow><h1 className="text-[40px] font-bold leading-[1.05] tracking-tight md:text-[56px]">Pergola work, priced and scheduled before you accept it.</h1><p className="mt-6 max-w-xl text-[17px] leading-7 text-[#D5D7DA]">MrBuilder brings installation, repair and inspection jobs to your phone. Every job shows the scope, the dates and the payment up front. You decide what to take on, then run the whole job from the app.</p><div className="mt-8 flex flex-wrap gap-3"><Btn href="#waitlist">Join the Contractor Waitlist</Btn><Btn href="#journey" kind="white">How it works ↓</Btn></div><div className="mt-8 flex flex-wrap gap-2">{SERVICE_TYPES.map((t) => <span key={t} className="rounded-full bg-white/10 px-3 py-1 text-[13px] font-medium text-white/85 ring-1 ring-white/15">{t}</span>)}</div></div><div id="waitlist" className="scroll-mt-24"><QuickForm kind="contractor" appLinks={content.app_links} /></div></Container></div></div>

      <Section><Container><Eyebrow>Why contractors use MrBuilder</Eyebrow><H2>Less chasing. More installing.</H2><div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{BENEFITS.map(([n, t, b]) => <div key={n} className="rounded-[20px] border border-gray-200 bg-white p-6"><div className="text-[13px] font-bold text-[#EF6820]">{n}</div><div className="mt-2 text-[19px] font-bold text-[#181D27]">{t}</div><p className="mt-2 text-[15px] leading-6 text-gray-600">{b}</p></div>)}</div></Container></Section>

      <Section id="journey" className="scroll-mt-20 bg-[#FAFAFA]"><Container><Eyebrow>How it works</Eyebrow><H2>The contractor journey, step by step.</H2><Lead>Each step below is paired with the actual screen from the MrBuilder contractor app. Names, prices and dates in the screens are sample data.</Lead>
        <div className="mt-10 rounded-[28px] border border-gray-200 bg-white p-6 md:p-10"><PhoneDemo steps={DEMO} app="Contractor app" /></div>
        <div className="mt-14 space-y-14">{JOURNEY.map((j, i) => <div key={j.n} className={`grid items-center gap-10 lg:grid-cols-2 ${i % 2 ? "lg:[&>*:first-child]:order-2" : ""}`}><div><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-full bg-[#181D27] text-sm font-bold text-white">{j.n}</span><span className="rounded-full border border-[#F9DBAF] bg-[#FEF6EE] px-3 py-1 text-[13px] font-semibold text-[#B93815]">{j.chip}</span></div><h3 className="mt-4 text-[26px] font-bold leading-tight text-[#181D27]">{j.title}</h3><p className="mt-3 text-[16px] leading-7 text-gray-600">{j.body}</p><div className="mt-5 grid gap-3 sm:grid-cols-2">{[j.a, j.b].map(([, cap]) => <div key={cap} className="rounded-xl bg-[#FAFAFA] p-3"><div className="text-xs font-bold uppercase tracking-wide text-gray-500">Screen</div><div className="mt-1 text-[13px] text-gray-700">{cap}</div></div>)}</div></div><div className="flex justify-center gap-4"><Phone src={j.a[0]} alt={j.a[1]} className="w-1/2" tall /><Phone src={j.b[0]} alt={j.b[1]} className="mt-8 w-1/2" tall /></div></div>)}</div></Container></Section>

      <Section><Container><Eyebrow>Manage your work</Eyebrow><H2>Everything a job needs, in one app.</H2><div className="mt-10 grid gap-6 sm:grid-cols-2 lg:grid-cols-4">{[[S("k-schedule"), "Schedule", "Your accepted jobs by day, with times and locations."], [S("k-history"), "History", "Completed and canceled jobs, with details and client ratings."], [S("k-notifications"), "Notifications", "New jobs, client approvals, reschedule requests, confirmations and payouts. Each opens the right screen."], [S("k-filters"), "Filters", "Narrow the marketplace by service type, distance and dates so you only see work you can take."]].map(([img, t, b]) => <div key={t} className="rounded-[20px] border border-gray-200 bg-white p-5"><div className="h-[300px] overflow-hidden rounded-[18px] border-[4px] border-[#181D27] bg-white"><img src={img} alt={`Contractor app: ${t}`} className="w-full" loading="lazy" /></div><div className="mt-4 text-[17px] font-bold text-[#181D27]">{t}</div><p className="mt-1 text-[14px] leading-6 text-gray-600">{b}</p></div>)}</div></Container></Section>

      <Section className="bg-[#FAFAFA]"><Container className="grid gap-10 lg:grid-cols-[1fr_1.4fr]"><div><Eyebrow>FAQ</Eyebrow><H2>Questions contractors ask.</H2><p className="mt-4 text-[14px] text-gray-500">Payment terms, eligibility criteria and job volume will be published when the contractor program opens. Nothing below is a guarantee.</p></div><Faq items={FAQ} /></Container></Section>

      <Section className="bg-[#181D27] text-white"><Container className="grid items-center gap-10 lg:grid-cols-2"><div><Eyebrow color="text-[#F7A26B]">Contractor program</Eyebrow><h2 className="text-[34px] font-bold leading-tight">Join as a Contractor.</h2><p className="mt-4 text-[16px] leading-7 text-[#D5D7DA]">Apply in the MrBuilder contractor app. You'll set up your account, address, role, business details, insurance and skills, then submit. We review applications before activating marketplace access.</p><div className="mt-6 flex flex-wrap items-center gap-4"><Btn href="/register?role=contractor">Join as a Contractor</Btn><a href={`mailto:${content.company.email}`} className="font-semibold text-white/80">Questions? Contact us</a></div><div className="mt-5"><AppBadges links={content.app_links} app="contractor" /></div><div className="mt-4 text-[13px] text-white/50">Currently onboarding in the United States.</div></div><div className="flex justify-center gap-4"><Phone src={S("k-onboarding")} alt="Contractor app: onboarding" className="w-1/2" /><Phone src={S("k-signup")} alt="Contractor app: sign-up step 1, account information" className="mt-8 w-1/2" /></div></Container></Section>
      <SiteFooter />
    </>
  );
}
