package routes

import (
	"database/sql"

	"github.com/gin-gonic/gin"
	"github.com/mrbuilder/backend/internal/handlers"
	"github.com/mrbuilder/backend/internal/middleware"
)

func Setup(r *gin.Engine, db *sql.DB, jwtSecret string) {
	auth := handlers.NewAuthHandler(db, jwtSecret)
	profile := handlers.NewProfileHandler(db)
	job := handlers.NewJobHandler(db)
	quote := handlers.NewQuoteHandler(db)
	msg := handlers.NewMessageHandler(db)
	rating := handlers.NewRatingHandler(db)
	notif := handlers.NewNotificationHandler(db)
	warranty := handlers.NewWarrantyHandler(db)
	platform := handlers.NewPlatformHandler(db)
	admin := handlers.NewAdminHandler(db)
	settings := handlers.NewSettingsHandler(db)
	money := handlers.NewMoneyHandler(db)
	account := handlers.NewAccountHandler(db)
	training := handlers.NewTrainingHandler(db)
	mrcare := handlers.NewMrCareHandler(db)
	store := handlers.NewStoreHandler(db)
	leadsH := &handlers.LeadsHandler{DB: db}
	hh := handlers.NewHouseholdHandler(db)
	integ := handlers.NewIntegrationsHandler(db)
	payments := handlers.NewPaymentsHandler(db)
	handlers.InitPush(db)

	api := r.Group("/api/v1")
	{
		// Public routes
		api.POST("/register", auth.Register)
		api.POST("/login", auth.Login)
		api.POST("/refresh", auth.Refresh)
		api.POST("/logout", auth.Logout)
		api.GET("/contractors", profile.ListContractors)
		api.GET("/contractors/:id", profile.GetContractorPublic)
		api.POST("/waitlist", platform.JoinWaitlist)
		api.POST("/partner-requests", platform.CreatePartnerRequest)
		api.GET("/settings", settings.List)
		api.GET("/categories", settings.ListCategories)
		api.GET("/mrcare/plans", settings.ListMrCarePlans)
		api.GET("/contractors/:id/summary", hh.ContractorSummary)
		api.GET("/public/documents/:token", hh.PublicDocument)
		api.GET("/content", training.Content)
		api.POST("/leads", leadsH.Create)
		api.GET("/legal/:kind", training.Legal)
		api.POST("/auth/oauth", auth.OAuth)
		api.POST("/auth/forgot", auth.Forgot)
		api.POST("/auth/reset", auth.Reset)
		api.POST("/webhooks/stripe", payments.Webhook)

		// Protected routes
		protected := api.Group("")
		protected.Use(middleware.AuthRequired(jwtSecret))
		{
			protected.GET("/me", auth.Me)
			protected.GET("/profile", profile.GetMyProfile)
			protected.PUT("/profile", profile.UpdateMyProfile)
			protected.PUT("/profile/skills", middleware.RoleRequired("contractor"), training.UpdateServices)
			protected.PUT("/profile/pergola-systems", middleware.RoleRequired("contractor"), profile.UpdatePergolaSystems)

			// Jobs
			protected.POST("/jobs", middleware.RoleRequired("consumer"), job.Create)
			protected.GET("/jobs", middleware.RoleRequired("contractor", "admin"), job.ListOpen)
			protected.GET("/jobs/me", job.ListMine)
			protected.GET("/jobs/:id", job.Get)
			protected.PATCH("/jobs/:id/cancel", job.CancelJob)
			protected.GET("/jobs/:id/cancel-preview", job.CancelPreview)
			// Money & schedule
			protected.GET("/earnings", middleware.RoleRequired("contractor"), money.Earnings)
			protected.GET("/transactions", money.Transactions)
			protected.POST("/payouts", middleware.RoleRequired("contractor"), money.RequestPayout)
			protected.GET("/payouts/me", middleware.RoleRequired("contractor"), money.ListPayouts)
			protected.GET("/schedule", middleware.RoleRequired("contractor"), money.Schedule)
			protected.GET("/payment-methods", money.ListPaymentMethods)
			protected.POST("/payment-methods", money.AddPaymentMethod)
			protected.PATCH("/payment-methods/:id/default", money.SetDefaultPaymentMethod)
			protected.DELETE("/payment-methods/:id", money.DeletePaymentMethod)
			// Account
			protected.GET("/me/settings", account.GetSettings)
			protected.PATCH("/me/notifications", account.UpdateNotifications)
			protected.PATCH("/me/preferences", account.UpdatePreferences)
			protected.POST("/me/devices", account.RegisterDevice)
			protected.DELETE("/me/devices", account.UnregisterDevice)
			protected.DELETE("/me", account.DeleteAccount)
			// Training & activation
			tr := protected.Group("/training", middleware.RoleRequired("contractor"))
			tr.GET("", training.Hub)
			tr.GET("/modules/:slug", training.Module)
			tr.GET("/lessons/:id", training.Lesson)
			tr.POST("/lessons/:id/watched", training.Watched)
			tr.POST("/lessons/:id/complete", training.Complete)
			tr.POST("/lessons/:id/quiz", training.SubmitQuiz)
			tr.GET("/library", training.Library)
			tr.GET("/services", training.MyServices)
			tr.PUT("/services", training.UpdateServices)
			// Pergolas, equipment, MrCare (consumer)
			cs := protected.Group("", middleware.RoleRequired("consumer"))
			cs.GET("/pergolas", mrcare.ListPergolas)
			cs.POST("/pergolas", mrcare.CreatePergola)
			cs.PATCH("/pergolas/:id", mrcare.UpdatePergola)
			cs.DELETE("/pergolas/:id", mrcare.DeletePergola)
			cs.GET("/equipment", mrcare.ListEquipment)
			cs.POST("/equipment", mrcare.AddEquipment)
			cs.DELETE("/equipment/:id", mrcare.RemoveEquipment)
			cs.GET("/mrcare", mrcare.Hub)
			cs.POST("/mrcare/quote", mrcare.QuoteSubscription)
			cs.POST("/mrcare/subscriptions", mrcare.CreateSubscription)
			cs.GET("/mrcare/subscriptions/:id", mrcare.GetSubscription)
			cs.PATCH("/mrcare/subscriptions/:id", mrcare.ChangeSubscription)
			cs.DELETE("/mrcare/subscriptions/:id", mrcare.CancelSubscription)
			cs.POST("/mrcare/bookings", mrcare.CreateBooking)
			cs.POST("/mrcare/claims", mrcare.CreateClaim)
			cs.POST("/parts-requests/:id/approve", store.ApprovePartsRequest)
			cs.POST("/parts-requests/:id/decline", store.DeclinePartsRequest)
			// Household, drafts, reminders (consumer)
			cs.GET("/household", hh.Get)
			cs.POST("/household/invites", hh.Invite)
			cs.POST("/household/accept", hh.Accept)
			cs.PATCH("/household/members/:id", hh.UpdateMember)
			cs.DELETE("/household/members/:id", hh.RemoveMember)
			cs.POST("/jobs/:id/acknowledge", hh.Acknowledge)
			cs.GET("/drafts", hh.ListDrafts)
			cs.POST("/drafts", hh.CreateDraft)
			cs.PUT("/drafts/:id", hh.UpdateDraft)
			cs.DELETE("/drafts/:id", hh.DeleteDraft)
			cs.GET("/reminders", hh.ListReminders)
			cs.POST("/reminders/:id/:action", hh.ReminderAction)
			// Documents & referrals (both roles)
			protected.GET("/documents", hh.ListDocuments)
			protected.POST("/documents/:id/share", hh.ShareDocument)
			protected.GET("/referrals", hh.Referrals)
			protected.POST("/referrals/apply", hh.ApplyReferral)
			protected.POST("/uploads", integ.CreateUpload)
			protected.POST("/geocode", integ.Geocode)
			protected.POST("/me/verify/send", auth.VerifySend)
			protected.POST("/me/verify/confirm", auth.VerifyConfirm)
			protected.POST("/payments/setup-intent", payments.SetupIntent)
			protected.POST("/payment-methods/attach", payments.AttachPaymentMethod)
			protected.POST("/payouts/connect", middleware.RoleRequired("contractor"), payments.ConnectOnboard)
			protected.GET("/payouts/connect/status", middleware.RoleRequired("contractor"), payments.ConnectStatus)
			protected.POST("/parts-requests/:id/remind", middleware.RoleRequired("contractor"), store.RemindPartsRequest)
			protected.GET("/jobs/:id/parts-requests", store.ListPartsRequests)
			// Mr Supply store (both roles)
			st := protected.Group("/store")
			st.GET("/categories", store.Categories)
			st.GET("/products", store.Products)
			st.GET("/products/:id", store.Product)
			st.PUT("/favorites/:id", store.AddFavorite)
			st.DELETE("/favorites/:id", store.RemoveFavorite)
			st.GET("/cart", store.GetCart)
			st.POST("/cart/items", store.AddCartItem)
			st.PATCH("/cart/items/:id", store.UpdateCartItem)
			st.DELETE("/cart/items/:id", store.RemoveCartItem)
			st.POST("/orders", store.Checkout)
			st.GET("/orders", store.ListOrders)
			st.GET("/orders/:id", store.GetOrder)
			st.POST("/orders/:id/cancel", store.CancelOrder)
			st.POST("/orders/:id/reorder", store.Reorder)
			st.POST("/orders/:id/report", store.ReportOrder)
			protected.GET("/addresses", store.ListAddresses)
			protected.POST("/addresses", store.CreateAddress)
			protected.PATCH("/addresses/:id", store.UpdateAddress)
			protected.DELETE("/addresses/:id", store.DeleteAddress)
			protected.POST("/jobs/:id/en-route", middleware.RoleRequired("contractor"), job.EnRoute)
			protected.POST("/jobs/:id/arrived", middleware.RoleRequired("contractor"), job.Arrived)
			protected.POST("/jobs/:id/evidence", middleware.RoleRequired("contractor"), job.AddEvidence)
			protected.GET("/jobs/:id/evidence", job.ListEvidence)
			protected.PUT("/jobs/:id/checklist", middleware.RoleRequired("contractor"), job.UpdateChecklist)
			protected.POST("/jobs/:id/start", middleware.RoleRequired("contractor"), job.StartJob)
			protected.POST("/jobs/:id/pause", middleware.RoleRequired("contractor"), job.Pause)
			protected.POST("/jobs/:id/resume", middleware.RoleRequired("contractor"), job.Resume)
			protected.POST("/jobs/:id/complete", middleware.RoleRequired("contractor"), job.CompleteJob)
			protected.POST("/jobs/:id/fix-done", middleware.RoleRequired("contractor"), job.FixDone)
			protected.POST("/jobs/:id/confirm", middleware.RoleRequired("consumer"), job.ConfirmJob)
			protected.POST("/jobs/:id/issue", middleware.RoleRequired("consumer"), job.ReportIssue)
			protected.POST("/jobs/:id/dispute", middleware.RoleRequired("contractor"), job.OpenDispute)
			protected.POST("/jobs/:id/reschedule", job.ProposeReschedule)
			protected.GET("/jobs/:id/reschedule", job.ListReschedule)
			protected.PATCH("/jobs/:id/reschedule/:pid", job.RespondReschedule)
			protected.GET("/jobs/:id/events", job.ListEvents)
			protected.POST("/jobs/:id/quote/approve", middleware.RoleRequired("consumer"), job.ApproveQuote)
			protected.POST("/jobs/:id/quote/decline", middleware.RoleRequired("consumer"), job.DeclineQuote)
			protected.POST("/jobs/:id/accept", middleware.RoleRequired("contractor"), job.Accept)
			protected.POST("/jobs/:id/decline", middleware.RoleRequired("contractor"), job.Decline)
			protected.POST("/jobs/:id/inspection-report", middleware.RoleRequired("contractor"), job.SubmitInspectionReport)

			// Quotes & invoices
			protected.POST("/jobs/:id/quotes", handlers.Gone)
			protected.GET("/jobs/:id/quotes", handlers.Gone)
			protected.GET("/quotes/me", handlers.Gone)
			protected.PATCH("/quotes/:id/accept", handlers.Gone)
			protected.PATCH("/quotes/:id/reject", handlers.Gone)
			protected.PATCH("/quotes/:id/withdraw", handlers.Gone)
			protected.GET("/invoices/me", quote.ListMyInvoices)

			// Messaging
			protected.POST("/jobs/:id/conversation", msg.GetOrCreate)
			protected.GET("/conversations", msg.List)
			protected.GET("/conversations/:id/messages", msg.ListMessages)
			protected.POST("/conversations/:id/messages", msg.Send)

			// Ratings
			protected.POST("/jobs/:id/ratings", rating.Create)
			protected.GET("/jobs/:id/ratings", rating.ListForJob)
			protected.GET("/users/:id/ratings", rating.ListForUser)

			// Notifications
			protected.GET("/notifications", notif.List)
			protected.PATCH("/notifications/:id/read", notif.MarkRead)
			protected.PATCH("/notifications/read-all", notif.MarkAllRead)

			// Warranties & claims
			protected.POST("/jobs/:id/warranties", middleware.RoleRequired("contractor"), warranty.Create)
			protected.GET("/warranties/me", warranty.ListMine)
			protected.POST("/warranties/:id/claims", middleware.RoleRequired("consumer"), warranty.CreateClaim)
			protected.GET("/claims/me", middleware.RoleRequired("consumer"), warranty.ListMyClaims)

			// Admin
			adm := protected.Group("/admin")
			adm.Use(middleware.RoleRequired("admin"))
			{
				adm.GET("/stats", admin.Stats)
				adm.GET("/users", admin.ListUsers)
				adm.PATCH("/users/:id/status", admin.SetUserStatus)
				adm.GET("/jobs", admin.ListJobs)
				adm.POST("/jobs/:id/requote", job.AdminRequote)
				adm.PATCH("/jobs/:id/dispute", job.AdminDisputeDecision)
				adm.GET("/payouts", money.AdminListPayouts)
				adm.PATCH("/payouts/:id", money.AdminPayoutDecision)
				adm.POST("/jobs/:id/assign", training.AdminAssignJob)
				adm.GET("/contractors/:id/training", training.AdminContractorTraining)
				adm.POST("/contractors/:id/practical", training.AdminPractical)
				adm.PUT("/contractors/:id/qualifications/:category", training.AdminSetQualification)
				adm.PUT("/training/lessons/:slug", training.AdminUpsertLesson)
				adm.PUT("/training/lessons/:slug/quiz", training.AdminReplaceQuiz)
				adm.GET("/mrcare/claims", mrcare.AdminListClaims)
				adm.PATCH("/mrcare/claims/:id", mrcare.AdminReviewClaim)
				adm.GET("/store/orders", store.AdminListOrders)
				adm.PATCH("/store/orders/:id", store.AdminOrderStatus)
				adm.PUT("/store/products/:sku", store.AdminUpsertProduct)
				adm.GET("/store/products", integ.AdminListProducts)
				adm.PUT("/store/categories/:slug", integ.AdminUpsertCategory)
				adm.GET("/integrations", integ.List)
				adm.PUT("/integrations/:provider", integ.Update)
				adm.POST("/integrations/:provider/test", integ.Test)
				adm.GET("/jobs2", job.AdminListJobs)
				adm.GET("/jobs2/:id", job.AdminGetJob)
				adm.GET("/contractors", training.AdminListContractors)
				adm.GET("/dashboard", job.AdminDashboard)
				adm.POST("/users", training.AdminCreateUser)
				adm.PATCH("/users/:id", training.AdminUpdateUser)
				adm.GET("/customers", training.AdminListCustomers)
				adm.GET("/team", training.AdminListTeam)
				adm.POST("/jobs", job.Create)
				adm.GET("/training", training.AdminContent)
				adm.GET("/training/lessons/:slug", training.AdminLesson)
				adm.GET("/claims", admin.ListClaims)
				adm.PATCH("/claims/:id", admin.SetClaimStatus)
				adm.GET("/waitlist", admin.ListWaitlist)
				adm.GET("/partner-requests", admin.ListPartnerRequests)
				adm.GET("/invoices", admin.ListInvoices)
				adm.GET("/warranties", admin.ListWarranties)
				adm.PATCH("/waitlist/:id/activate", admin.ActivateWaitlist)
				adm.GET("/system", admin.SystemInfo)
				adm.GET("/leads", leadsH.AdminList)
				adm.PATCH("/leads/:id", leadsH.AdminUpdate)
				adm.GET("/settings", settings.AdminList)
				adm.PUT("/settings", settings.Update)
				adm.PUT("/categories/:slug", settings.UpdateCategory)
				adm.GET("/pricing-rules", settings.ListPricingRules)
				adm.POST("/pricing-rules", settings.CreatePricingRule)
				adm.PUT("/pricing-rules/:id", settings.UpdatePricingRule)
				adm.DELETE("/pricing-rules/:id", settings.DeletePricingRule)
				adm.PUT("/mrcare/plans/:slug", settings.UpsertMrCarePlan)
				adm.PUT("/mrcare/addons/:slug", settings.UpsertMrCareAddon)
			}
		}
	}
}
