import Link from "next/link";
import SiteHeader from "@/components/site/SiteHeader";
import SiteFooter from "@/components/site/SiteFooter";
import { Phone } from "@/components/site/Phone";
import { PhoneDemo } from "@/components/site/PhoneDemo";
import { QuickForm } from "@/components/site/QuickForm";
import { Faq } from "@/components/site/Faq";
import { AppBadges } from "@/components/site/AppBadges";
import { Btn, Container, Eyebrow, H2, Lead, S, Section } from "@/components/site/ui";
import { getContent } from "@/lib/content";

export const metadata = { title: "For Homeowners — MrBuilder", description: "Your pergola, handled from first quote to last repair." };

const BENEFITS = [["01", "A quote before a booking", "Describe the work, get an itemized quote, then decide. Nothing is scheduled until you approve."], ["02", "Vetted professionals", "MrBuilder matches your approved job to a contractor whose skills fit the work. You see who accepted, their rating and how to reach them."], ["03", "One thread for everything", "Status, messages, photos, documents and receipts stay with the request, not scattered across texts and emails."], ["04", "You confirm before paying", "The contractor marks the job complete with proof photos. You review, confirm and pay in the app, or report an issue."]];
const JOURNEY = [
  { n: 1, chip: "New request", title: "Choose installation or repair.", body: "From Home or the Requests tab, pick \"Install a pergola\" for a new structure or \"Repair or maintain\" for an existing one. Each opens a short, structured form.", a: [S("c-home"), "Home: What do you need? Install a pergola · Repair or maintain, plus a weather and pergola-care card for your property."], b: [S("c-new-request"), "New request: two options and the MrCare promo."] },
  { n: 2, chip: "Submitted", title: "Give the details once.", body: "Address, property type, preferred dates and notes; then each pergola's type, brand, mounting and W × L × H, with photos and plan documents. For repairs: the pergola, service type, description, urgency, a time window and photos.", a: [S("c-install-form"), "New installation request: Address, Project details, Pergolas to install."], b: [S("c-add-pergola"), "Add pergola: type, brand, dimensions, attachment, enclosures, footings, accessories, photos and plan PDF."] },
  { n: 3, chip: "Quote ready", title: "Review the quote. Approve or decline.", body: "MrBuilder prices the request from your details, or from an inspector's on-site report when the job needs one. The quote is itemized, valid for a set period, and can be approved, declined with a reason, or shared.", a: [S("c-quote"), "Quote: total, summary table and the pergolas included."], b: [S("c-inspector-quote"), "Request details: inspector report with findings, photos and itemized quote."] },
  { n: 4, chip: "Contractor assigned", title: "A professional accepts your job.", body: "Approved jobs are matched to a vetted contractor. You see their name, rating and contact options, the scheduled window, and can reschedule, add the visit to your calendar, or cancel.", a: [S("c-assigned"), "Request details: contractor assigned, with Message, Call, Reschedule and Add to calendar."], b: [S("c-requests"), "Requests: all your requests with status chips."] },
  { n: 5, chip: "In progress", title: "Follow the visit as it happens.", body: "You're notified when the contractor is on the way, when they arrive and when work starts. The timeline updates from their app in real time.", a: [S("c-enroute"), "Request details: contractor on the way, with ETA."], b: [S("c-in-progress"), "Request details: In progress with live steps."] },
  { n: 6, chip: "Chat", title: "Talk to your professional in the job thread.", body: "Each request has a chat with the assigned professional. Quotes and reports appear as cards; the phone icon opens their contact card. When a job ends, the thread stays as a record.", a: [S("c-chat"), "Chat: conversation with the technician, quote card with Review."], b: [S("c-invoices"), "Invoices: payment balance and invoice cards with PDF / Pay."] },
  { n: 7, chip: "Completed · paid", title: "Review the finished work, confirm and pay.", body: "The contractor submits proof photos and a note. You confirm and pay (with an optional tip) or report an issue and payment stays on hold. Afterwards you can rate the professional.", a: [S("c-awaiting"), "Request details: Awaiting your confirmation, with Confirm & pay / Report an issue."], b: [S("c-confirm-pay"), "Confirm & pay: tip presets, charge summary and payment method."] },
];
const DEMO = JOURNEY.map((j) => ({ screen: j.a[0], title: j.chip, caption: j.title }));
const FAQ: [string, string][] = [["Do I pay before the work is done?", "No. You approve a quote first; payment is made when you confirm the finished work in the app. If you report an issue, payment stays on hold while it is resolved."], ["Who does the work?", "A vetted contractor matched to your approved job. You see their name and rating when they accept, and can message or call them from the request."], ["What if I need to change the date?", "Open the request and tap Reschedule to propose a new day and time. The contractor accepts it or suggests another; your original slot is kept until you agree."], ["Can I cancel a request?", "Yes, from the request itself. Cancelling before a contractor is assigned is free; terms after assignment will be shown in the app when you cancel."], ["What is MrCare?", "MrCare is the consumer app's section for ongoing care: a Service & Maintenance Subscription and a separate Electronics Protection Plan. Both are optional and sold per pergola."], ["Where is MrBuilder available?", "We are starting in the United States. New areas will be announced as we open them."]];

export default async function ForConsumersPage() {
  const content = await getContent();
  return (
    <>
      <div className="relative overflow-hidden bg-[#181D27] text-white"><video className="absolute inset-0 h-full w-full object-cover opacity-40 motion-reduce:hidden" autoPlay muted loop playsInline poster="/site/video/bg-hero-consumer.jpg"><source src="/site/video/bg-hero-consumer.mp4" type="video/mp4" /></video><div className="absolute inset-0 bg-gradient-to-b from-[#181D27]/60 via-[#181D27]/30 to-[#181D27]" /><div className="relative"><SiteHeader dark />
        <Container className="grid items-start gap-10 pb-16 pt-8 lg:grid-cols-[1fr_460px] lg:pb-24 lg:pt-14"><div className="pt-6"><Eyebrow color="text-[#F7A26B]">For homeowners</Eyebrow><h1 className="text-[40px] font-bold leading-[1.05] tracking-tight md:text-[56px]">Your pergola, handled from first quote to last repair.</h1><p className="mt-6 max-w-xl text-[17px] leading-7 text-[#D5D7DA]">Tell MrBuilder what you need. We price it, match a vetted professional, and keep you updated in one thread, with photos, messages and payment all in the app.</p><div className="mt-8 flex flex-wrap gap-3"><Btn href="#request">Submit My Request</Btn><Btn href="#journey" kind="white">See how it works ↓</Btn></div><div className="mt-8"><AppBadges links={content.app_links} /></div></div><div id="request" className="scroll-mt-24"><QuickForm kind="consumer" appLinks={content.app_links} /></div></Container></div></div>

      <Section><Container className="grid gap-5 md:grid-cols-2 lg:grid-cols-4">{BENEFITS.map(([n, t, b]) => <div key={n} className="rounded-[20px] border border-gray-200 bg-white p-6"><div className="text-[13px] font-bold text-[#EF6820]">{n}</div><div className="mt-2 text-[19px] font-bold text-[#181D27]">{t}</div><p className="mt-2 text-[15px] leading-6 text-gray-600">{b}</p></div>)}</Container></Section>

      <Section id="journey" className="scroll-mt-20 bg-[#FAFAFA]"><Container><Eyebrow>The customer journey</Eyebrow><H2>Seven steps, one request.</H2><Lead>Every step is shown with the real screen from the MrBuilder consumer app. Names, prices and dates are sample data.</Lead>
        <div className="mt-10 rounded-[28px] border border-gray-200 bg-white p-6 md:p-10"><PhoneDemo steps={DEMO} app="Consumer app" /></div>
        <div className="mt-14 space-y-14">{JOURNEY.map((j, i) => <div key={j.n} className={`grid items-center gap-10 lg:grid-cols-2 ${i % 2 ? "lg:[&>*:first-child]:order-2" : ""}`}><div><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-full bg-[#181D27] text-sm font-bold text-white">{j.n}</span><span className="rounded-full border border-[#F9DBAF] bg-[#FEF6EE] px-3 py-1 text-[13px] font-semibold text-[#B93815]">{j.chip}</span></div><h3 className="mt-4 text-[26px] font-bold leading-tight text-[#181D27]">{j.title}</h3><p className="mt-3 text-[16px] leading-7 text-gray-600">{j.body}</p><div className="mt-5 grid gap-3 sm:grid-cols-2">{[j.a, j.b].map(([, cap]) => <div key={cap} className="rounded-xl bg-[#FAFAFA] p-3"><div className="text-xs font-bold uppercase tracking-wide text-gray-500">Screen</div><div className="mt-1 text-[13px] text-gray-700">{cap}</div></div>)}</div></div><div className="flex justify-center gap-4"><Phone src={j.a[0]} alt={j.a[1]} className="w-1/2" tall /><Phone src={j.b[0]} alt={j.b[1]} className="mt-8 w-1/2" tall /></div></div>)}</div></Container></Section>

      <Section id="mrcare" className="scroll-mt-20"><Container className="grid items-center gap-12 lg:grid-cols-2"><div><Eyebrow>MrCare</Eyebrow><H2>Two ways to protect your pergola.</H2><Lead>After installation, MrCare in the consumer app offers two separate, optional offerings. Buy either, or both.</Lead><div className="mt-8 space-y-4">{[["Service & Maintenance Subscription", "Scheduled inspections, cleaning and priority scheduling across Essential, Plus and Premium plans. Book included visits from the app."], ["Electronics Protection Plan", "Repair or replacement coverage for motors, sensors, remotes and controllers, sold per pergola. Report an electronics issue as a claim."]].map(([t, b]) => <div key={t} className="rounded-[20px] border border-gray-200 bg-white p-6"><div className="text-[19px] font-bold text-[#181D27]">{t}</div><p className="mt-2 text-[15px] leading-6 text-gray-600">{b}</p></div>)}</div><p className="mt-4 text-[13px] text-gray-500">Plan contents, pricing and terms are shown in the app at purchase and are still being finalized.</p></div><div className="flex justify-center gap-4"><Phone src={S("c-mrcare")} alt="Consumer app: MrCare hub with both offerings" className="w-1/2" /><Phone src={S("c-protection")} alt="Consumer app: Electronics Protection Plan details" className="mt-8 w-1/2" /></div></Container></Section>

      <Section className="bg-[#FAFAFA]"><Container><Eyebrow>Also in the app</Eyebrow><H2>Everything about your pergola, in one place.</H2><div className="mt-10 grid gap-6 sm:grid-cols-2 lg:grid-cols-4">{[[S("c-add-empty"), "My pergolas", "Each structure with its type, dimensions, warranty status and service history."], [S("c-add-pergola"), "Pergola details", "Specs, dimensions, dates, warranties and last services on one page."], [S("c-repair-form"), "Repair requests", "Pick the pergola and service type, describe the issue, set urgency and a time window, attach photos."], [S("c-completed"), "Receipts & ratings", "Completed requests keep the receipt and let you rate the professional."]].map(([img, t, b]) => <div key={t} className="rounded-[20px] border border-gray-200 bg-white p-5"><div className="h-[300px] overflow-hidden rounded-[18px] border-[4px] border-[#181D27] bg-white"><img src={img} alt={t} className="w-full" loading="lazy" /></div><div className="mt-4 text-[17px] font-bold text-[#181D27]">{t}</div><p className="mt-1 text-[14px] leading-6 text-gray-600">{b}</p></div>)}</div></Container></Section>

      <Section><Container className="grid gap-10 lg:grid-cols-[1fr_1.4fr]"><div><Eyebrow>FAQ</Eyebrow><H2>Good to know.</H2></div><Faq items={FAQ} /></Container></Section>

      <Section className="bg-[#181D27] text-white"><Container className="grid items-center gap-10 lg:grid-cols-2"><div><Eyebrow color="text-[#F7A26B]">MrBuilder for homeowners</Eyebrow><h2 className="text-[34px] font-bold leading-tight">Get Started with your first request.</h2><p className="mt-4 text-[16px] leading-7 text-[#D5D7DA]">Download the MrBuilder app, sign up with your email, and create an installation or repair request in a few minutes. You'll see a quote before anyone is booked.</p><div className="mt-6 flex flex-wrap items-center gap-4"><Btn href="/register">Get Started</Btn><Link href="/partner#companies" className="font-semibold text-white/80">Bought from a partner company?</Link></div><div className="mt-5"><AppBadges links={content.app_links} /></div><div className="mt-4 text-[13px] text-white/50">Starting in the United States.</div></div><div className="flex justify-center gap-4"><Phone src={S("c-new-request")} alt="Consumer app: New request with two options" className="w-1/2" /><Phone src={S("c-home-dark")} alt="Consumer app: Home in dark mode" className="mt-8 w-1/2" /></div></Container></Section>
      <SiteFooter />
    </>
  );
}
