"use client";

import { useState } from "react";
import Link from "next/link";
import { api } from "@/lib/api";
import { AppBadges } from "./AppBadges";

type Field = { id: string; label: string; type: "text" | "email" | "tel" | "select" | "seg" | "chips" | "multi" | "area" | "file"; placeholder?: string; options?: string[]; span?: 1 | 2; optional?: boolean; hint?: string; showIf?: { field: string; includes: string } };
const STATES = ["AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "DC", "FL", "GA", "HI", "ID", "IL", "IN", "IA", "KS", "KY", "LA", "ME", "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY", "NC", "ND", "OH", "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY"];
const BUSINESS = ["Manufacturer", "Wholesaler / Distributor", "Retail Showroom", "Online Retailer / E-commerce Store", "Motor & Automation Supplier / Dealer", "Outdoor Living / Patio Company", "Landscape Design / Landscaping Company", "Pool & Spa Company", "Architecture / Engineering Firm", "General Contractor", "Builder", "Real Estate Developer", "Residential Property Management", "Commercial Property Management", "Facilities Management Company", "Homeowners Association (HOA)", "Hotel / Resort", "Restaurant / Café / Bar", "Country Club / Golf Club", "Event / Wedding Venue", "Other (please specify)"];
const PRODUCTS = ["Motorized Pergola Systems", "Retractable Awnings & Shade Systems", "Motorized Zip Screens & Outdoor Blinds", "Motorized Louvers & Sunshades", "Motorized Pool Covers", "Automatic Gates & Garage Doors", "Motorized Outdoor TV Lifts & Enclosures", "Motorized Outdoor Kitchen Covers & Panels", "Outdoor Heating & Cooling Systems", "Automated Misting Systems", "Smart Outdoor Lighting Systems", "Motors, Sensors & Automation Systems"];

const SPECS = {
  contractor: { eyebrow: "Contractor waitlist", title: "Get on the list before jobs open in your area.", sub: "Takes a minute. No app needed. We'll reach out when onboarding starts near you.", btn: "Join the Contractor Waitlist", fine: "By joining you agree to be contacted about the contractor program. No job volume or earnings are guaranteed.", successTitle: "You're on the list!", successBody: "We'll contact you about the next steps.", appHeading: "Prefer the app? Download MrBuilder for Contractors.", app: "contractor" as const,
    fields: [{ id: "name", label: "Full name", type: "text", placeholder: "Jane Rivera", span: 2 }, { id: "email", label: "Email", type: "email", placeholder: "jane@company.com" }, { id: "phone", label: "Phone number", type: "tel", placeholder: "(555) 000-0000" }, { id: "city", label: "City", type: "text", placeholder: "Austin", span: 2 }, { id: "state", label: "State", type: "text", placeholder: "Texas", span: 2 }, { id: "country", label: "Country", type: "text", placeholder: "United States", span: 2 }, { id: "services", label: "Services offered", type: "chips", options: ["Installation", "Repair", "Maintenance"], span: 2 }] as Field[] },
  consumer: { eyebrow: "Quick service request", title: "Tell us what you need. We'll take it from there.", sub: "Submit directly here, no download required. A MrBuilder coordinator follows up with next steps.", btn: "Submit My Request", fine: "Submitting adds your request to our queue; nothing is scheduled or charged until you approve a quote.", successTitle: "Your request has been added to our queue.", successBody: "We'll contact you about the next steps.", appHeading: "Prefer the app? Download MrBuilder.", app: "consumer" as const,
    fields: [{ id: "service", label: "Service needed", type: "seg", options: ["Installation", "Repair"], span: 2 }, { id: "name", label: "Full name", type: "text", placeholder: "Jordan Lee", span: 2 }, { id: "email", label: "Email", type: "email", placeholder: "jordan@email.com" }, { id: "phone", label: "Phone number", type: "tel", placeholder: "(555) 000-0000" }, { id: "address", label: "Address", type: "text", placeholder: "Street address", span: 2 }, { id: "city", label: "City", type: "text", placeholder: "City" }, { id: "state", label: "State", type: "select", placeholder: "State", options: STATES }, { id: "zip", label: "Zip Code", type: "text", placeholder: "78701" }, { id: "photos", label: "Photos", type: "file", optional: true }, { id: "desc", label: "Brief project or issue description", type: "area", placeholder: "e.g. 12×10 ft louvered pergola to install on an existing patio slab", span: 2 }] as Field[] },
  partner: { eyebrow: "Partnership inquiry", title: "Partner with MrBuilder", sub: "Tell us about your business and how you'd like to work together.", btn: "Submit Partnership Inquiry", fine: "By submitting you agree to be contacted about a partnership.", successTitle: "Thank you for your interest in partnering with MrBuilder.", successBody: "Our team will contact you to discuss the next steps.", appHeading: "", app: "consumer" as const,
    fields: [{ id: "company", label: "Company name", type: "text", placeholder: "Acme Outdoor Living", span: 2 }, { id: "contact", label: "Contact name", type: "text", placeholder: "Full name", span: 2 }, { id: "email", label: "Business email", type: "email", placeholder: "you@company.com" }, { id: "phone", label: "Phone number", type: "tel", placeholder: "+1 (555) 000-0000" }, { id: "website", label: "Website", type: "text", placeholder: "https://", span: 2, optional: true }, { id: "businessTypes", label: "What type of business do you operate?", hint: "Select all that apply.", type: "multi", options: BUSINESS, span: 2 }, { id: "businessOther", label: "Please specify your business type", type: "text", placeholder: "Tell us about your business", span: 2, showIf: { field: "businessTypes", includes: "Other (please specify)" } }, { id: "products", label: "What products do you sell?", hint: "Select all that apply.", type: "multi", options: PRODUCTS, span: 2 }, { id: "country", label: "Country", type: "text", placeholder: "United States" }, { id: "cityRegion", label: "City and State/Region", type: "text", placeholder: "Austin, TX" }, { id: "areas", label: "Areas served", type: "text", placeholder: "e.g. Texas, Arizona, New Mexico", span: 2 }, { id: "servicesNeeded", label: "Which services do your customers need?", hint: "Select all that apply.", type: "multi", options: ["Project Installation", "Repair", "Maintenance & Service", "Programming & Smart Controls", "Pergola Cleaning Service"], span: 2 }] as Field[] },
};

export function QuickForm({ kind, appLinks = {}, id, preset = {} }: { kind: keyof typeof SPECS; appLinks?: Record<string, string>; id?: string; preset?: Record<string, unknown> }) {
  const spec = SPECS[kind];
  const [v, setV] = useState<Record<string, unknown>>({ ...preset }); const [err, setErr] = useState<Record<string, string>>({}); const [busy, setBusy] = useState(false); const [done, setDone] = useState(false); const [fail, setFail] = useState<string | null>(null); const [openMulti, setOpenMulti] = useState<string | null>(null);
  const shown = (f: Field) => !f.showIf || ((v[f.showIf.field] as string[] | undefined) ?? []).includes(f.showIf.includes);
  const set = (k: string, val: unknown) => { setV({ ...v, [k]: val }); if (err[k]) setErr({ ...err, [k]: "" }); };
  async function submit() {
    const e: Record<string, string> = {};
    spec.fields.forEach((f) => { if (!shown(f) || f.type === "file") return; const val = v[f.id]; if (f.optional) { if (f.id === "website" && val && !/^https?:\/\/.+/.test(String(val))) e[f.id] = "Include https://"; return; } if (f.type === "chips" || f.type === "multi") { if (!Array.isArray(val) || !val.length) e[f.id] = "Select at least one"; return; } if (!val || !String(val).trim()) e[f.id] = "Required"; else if (f.type === "email" && !/^\S+@\S+\.\S+$/.test(String(val))) e[f.id] = "Enter a valid email"; });
    setErr(e); if (Object.keys(e).length) return;
    setBusy(true); setFail(null);
    const photos = (v.photos as FileList | undefined) ? Array.from(v.photos as FileList).map((f) => ({ name: f.name, size: f.size, type: f.type })) : undefined;
    const r = await api<{ id: string }>("/leads", { method: "POST", body: { kind, ...v, photos, submittedAt: new Date().toISOString(), source: "website" } });
    setBusy(false); if (r.success) setDone(true); else setFail(r.error ?? "Couldn't save. Please try again.");
  }
  const inputCls = (f: Field) => `h-12 w-full rounded-xl border bg-white px-3.5 text-[15px] text-[#181D27] outline-none placeholder:text-gray-400 focus:border-[#EF6820] focus:ring-2 focus:ring-[#F9DBAF] ${err[f.id] ? "border-red-400" : "border-gray-300"}`;
  return (
    <div id={id} className="rounded-[24px] border border-gray-200 bg-white p-6 shadow-[0_20px_50px_-30px_rgba(24,29,39,.35)] md:p-8">
      {done ? (
        <div className="py-6 text-center"><div className="mx-auto mb-4 grid h-14 w-14 place-items-center rounded-full bg-[#ECFDF3] text-2xl text-[#067647]">✓</div><h3 className="text-2xl font-bold text-[#181D27]">{spec.successTitle}</h3><p className="mt-2 text-gray-600">{spec.successBody}</p>{spec.appHeading && <div className="mt-6"><div className="mb-2 text-sm font-semibold text-gray-700">{spec.appHeading}</div><div className="flex justify-center"><AppBadges links={appLinks} app={spec.app} /></div></div>}{kind !== "partner" && <div className="mt-6 text-sm text-gray-500">Want to track it in the app? <Link href={kind === "contractor" ? "/register?role=contractor" : "/register"} className="font-semibold text-[#B93815]">Create an account</Link></div>}</div>
      ) : (
        <>
          <div className="text-[13px] font-bold uppercase tracking-[.08em] text-[#EF6820]">{spec.eyebrow}</div>
          <h3 className="mt-2 text-2xl font-bold leading-tight text-[#181D27]">{spec.title}</h3>
          <p className="mt-2 text-[15px] text-gray-600">{spec.sub}</p>
          <div className="mt-6 grid gap-4 sm:grid-cols-2">
            {spec.fields.filter(shown).map((f) => <label key={f.id} className={`block ${f.span === 2 ? "sm:col-span-2" : ""}`}>
              <span className="mb-1.5 block text-[13px] font-semibold text-gray-700">{f.label}{f.optional && <span className="ml-1 font-normal text-gray-400">(optional)</span>}</span>{f.hint && <span className="mb-1.5 block text-xs text-gray-500">{f.hint}</span>}
              {f.type === "seg" && <div className="grid grid-cols-2 gap-1 rounded-xl bg-gray-100 p-1">{f.options!.map((o) => <button type="button" key={o} onClick={() => set(f.id, o)} className={`h-10 rounded-lg text-[15px] font-semibold ${v[f.id] === o ? "bg-white text-[#181D27] shadow" : "text-gray-500"}`}>{o}</button>)}</div>}
              {f.type === "chips" && <div className="flex flex-wrap gap-2">{f.options!.map((o) => { const on = ((v[f.id] as string[]) ?? []).includes(o); return <button type="button" key={o} onClick={() => set(f.id, on ? (v[f.id] as string[]).filter((x) => x !== o) : [...((v[f.id] as string[]) ?? []), o])} className={`h-10 rounded-full border px-4 text-[14px] font-semibold ${on ? "border-[#EF6820] bg-[#FEF6EE] text-[#B93815]" : "border-gray-300 text-gray-700"}`}>{on ? "✓ " : ""}{o}</button>; })}</div>}
              {f.type === "multi" && <div className="relative"><button type="button" onClick={() => setOpenMulti(openMulti === f.id ? null : f.id)} className={`${inputCls(f)} flex items-center justify-between text-left`}><span className={((v[f.id] as string[]) ?? []).length ? "" : "text-gray-400"}>{((v[f.id] as string[]) ?? []).length ? `${(v[f.id] as string[]).length} selected` : f.placeholder ?? "Select"}</span><span className="text-gray-400">▾</span></button>{openMulti === f.id && <div className="absolute z-20 mt-1 max-h-64 w-full overflow-y-auto rounded-xl border border-gray-200 bg-white p-1 shadow-lg">{f.options!.map((o) => { const on = ((v[f.id] as string[]) ?? []).includes(o); return <button type="button" key={o} onClick={() => set(f.id, on ? (v[f.id] as string[]).filter((x) => x !== o) : [...((v[f.id] as string[]) ?? []), o])} className="flex w-full items-center gap-2 rounded-lg px-3 py-2 text-left text-[14px] hover:bg-gray-50"><span className={`grid h-4 w-4 place-items-center rounded border text-[10px] ${on ? "border-[#EF6820] bg-[#EF6820] text-white" : "border-gray-300"}`}>{on ? "✓" : ""}</span>{o}</button>; })}</div>}{((v[f.id] as string[]) ?? []).length > 0 && <div className="mt-2 flex flex-wrap gap-1">{(v[f.id] as string[]).map((o) => <span key={o} className="rounded-full bg-gray-100 px-2 py-0.5 text-xs">{o}</span>)}</div>}</div>}
              {f.type === "select" && <select value={(v[f.id] as string) ?? ""} onChange={(e) => set(f.id, e.target.value)} className={inputCls(f)}><option value="">{f.placeholder}</option>{f.options!.map((o) => <option key={o}>{o}</option>)}</select>}
              {f.type === "area" && <textarea value={(v[f.id] as string) ?? ""} onChange={(e) => set(f.id, e.target.value)} placeholder={f.placeholder} rows={4} className={`${inputCls(f)} h-auto py-3`} />}
              {f.type === "file" && <input type="file" accept="image/*" multiple onChange={(e) => set(f.id, e.target.files)} className="block w-full text-sm text-gray-600 file:mr-3 file:rounded-full file:border-0 file:bg-gray-100 file:px-4 file:py-2 file:text-sm file:font-semibold" />}
              {(f.type === "text" || f.type === "email" || f.type === "tel") && <input type={f.type} value={(v[f.id] as string) ?? ""} onChange={(e) => set(f.id, e.target.value)} placeholder={f.placeholder} className={inputCls(f)} />}
              {err[f.id] && <span className="mt-1 block text-xs text-red-600">{err[f.id]}</span>}
            </label>)}
          </div>
          {fail && <div className="mt-4 rounded-xl bg-red-50 px-4 py-3 text-sm text-red-700">{fail}</div>}
          <button type="button" onClick={submit} disabled={busy} className="mt-6 h-12 w-full rounded-full bg-[#EF6820] text-[15px] font-semibold text-white hover:bg-[#C4561A] disabled:opacity-60">{busy ? "Sending…" : spec.btn}</button>
          <p className="mt-3 text-center text-xs text-gray-500">{spec.fine}</p>
          {spec.appHeading && <div className="mt-5 border-t border-gray-100 pt-4"><div className="mb-2 text-center text-sm font-semibold text-gray-700">{spec.appHeading}</div><div className="flex justify-center"><AppBadges links={appLinks} app={spec.app} /></div></div>}
        </>
      )}
    </div>
  );
}
