import React, { useState } from "react";
import { Linking, Pressable, ScrollView, Text as RNText, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { useNavigation } from "@react-navigation/native";
import { NativeStackNavigationProp } from "@react-navigation/native-stack";
import { Ionicons } from "@expo/vector-icons";
import { Header } from "../../components/sheet";
import { useTheme } from "../../theme/ThemeProvider";
import { font } from "../../theme/tokens";
import { RootParams } from "../../navigation";

const FAQ = [["How do I get activated?", "Complete the Core and Safety training, then at least one category module. Installation and Repair also need a supervised first job (practical assessment)."], ["When do I get paid?", "Earnings land in your balance when the client confirms the work. Withdraw any time above the minimum payout, or turn on automatic payouts."], ["What if the client reports an issue?", "You'll see their feedback and photos. You can return to fix it (no charge to the client) or dispute it — MrBuilder reviews disputes within 48 hours."], ["Can I change the price?", "No. Quotes are generated by MrBuilder from the request. Extra work goes through a new request or an admin re-quote."], ["What are the cancellation fees?", "1% of the job if you cancel after accepting but before starting; 5% after starting. Pausing for safety is always free."], ["Who covers parts?", "Order from Mr Supply straight to the job. Depending on the job, parts are paid by you (reimbursed on the invoice) or by the client."]];

export default function HelpScreen() {
  const nav = useNavigation<NativeStackNavigationProp<RootParams>>();
  const { c } = useTheme();
  const [open, setOpen] = useState(0);
  const S = (n: number, w: "400" | "600" | "700" = "400", col = c.text) => ({ fontSize: n, fontFamily: w === "400" ? font.regular : w === "600" ? font.semibold : font.bold, color: col });
  return (
    <SafeAreaView edges={["top"]} style={{ flex: 1, backgroundColor: c.bg }}>
      <Header title="Help & Support" onBack={() => nav.goBack()} />
      <ScrollView contentContainerStyle={{ padding: 16, gap: 16 }}>
        <View style={{ flexDirection: "row", gap: 10 }}>{[["Phone support", "(800) 555-0199", "call-outline", () => Linking.openURL("tel:+18005550199")], ["Email us", "support@mrbuilder.com", "mail-outline", () => Linking.openURL("mailto:support@mrbuilder.com")]].map(([l, v, ic, fn]) => <Pressable key={l as string} onPress={fn as () => void} style={{ flex: 1, flexDirection: "row", alignItems: "center", gap: 10, backgroundColor: c.surface, borderWidth: 1, borderColor: c.border, borderRadius: 14, padding: 12 }}><View style={{ width: 38, height: 38, borderRadius: 12, backgroundColor: c.primarySoft, alignItems: "center", justifyContent: "center" }}><Ionicons name={ic as keyof typeof Ionicons.glyphMap} size={18} color={c.primary} /></View><View style={{ flex: 1 }}><RNText style={S(12.5, "400", c.text4)}>{l as string}</RNText><RNText style={S(13, "600")} numberOfLines={1}>{v as string}</RNText></View></Pressable>)}</View>
        <Pressable onPress={() => nav.navigate("Chats")} style={{ flexDirection: "row", alignItems: "center", gap: 12, backgroundColor: c.hero, borderRadius: 14, padding: 14 }}><View style={{ width: 38, height: 38, borderRadius: 12, backgroundColor: "rgba(255,255,255,.1)", alignItems: "center", justifyContent: "center" }}><Ionicons name="chatbubbles-outline" size={18} color="#fff" /></View><View style={{ flex: 1 }}><RNText style={S(15, "600", "#fff")}>Live chat</RNText><RNText style={S(12.5, "400", "#B7BAC1")}>Typically replies in a few minutes</RNText></View><Ionicons name="chevron-forward" size={18} color="#fff" /></Pressable>
        <View><RNText style={S(17, "700")}>Frequently asked questions</RNText><RNText style={S(13.5, "400", c.text4)}>Everything you need to know about jobs, payouts and activation.</RNText></View>
        <View style={{ backgroundColor: c.surface, borderWidth: 1, borderColor: c.border, borderRadius: 16 }}>{FAQ.map(([q, a], i) => <Pressable key={q} onPress={() => setOpen(open === i ? -1 : i)} style={{ padding: 14, paddingHorizontal: 16, borderTopWidth: i ? 1 : 0, borderTopColor: c.border, gap: 6 }}><View style={{ flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 10 }}><RNText style={{ flex: 1, ...S(14.5, "600") }}>{q}</RNText><Ionicons name={open === i ? "remove-circle-outline" : "add-circle-outline"} size={20} color={c.text4} /></View>{open === i && <RNText style={{ ...S(13.5, "400", c.text3), lineHeight: 19 }}>{a}</RNText>}</Pressable>)}</View>
      </ScrollView>
    </SafeAreaView>
  );
}
