// PRO Home = Marketplace (client: hero card · active job · filter · expandable job cards · empty/loading/offline)
import React, { useCallback, useState } from "react";
import { Pressable, ScrollView, Text as RNText, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { useFocusEffect, useNavigation } from "@react-navigation/native";
import { NativeStackNavigationProp } from "@react-navigation/native-stack";
import { Ionicons } from "@expo/vector-icons";
import * as Location from "expo-location";
import { Sheet, ChoiceRow } from "../../components/sheet";
import { PrimaryButton, SecondaryButton } from "../../components/form";
import { money } from "../../components";
import { api, Job } from "../../api/client";
import { useSession } from "../../auth/session";
import { useTheme } from "../../theme/ThemeProvider";
import { font } from "../../theme/tokens";
import { RootParams } from "../../navigation";

interface Lock { locked: boolean; qualified: string[]; practical_pending: string[]; reasons: string[] }
function lockText(l: Lock): string {
  const r = l.reasons; const parts: string[] = [];
  if (r.includes("core_incomplete") || r.includes("safety_incomplete")) parts.push(`Finish ${[r.includes("core_incomplete") && "Core", r.includes("safety_incomplete") && "Safety"].filter(Boolean).join(" and ")} training`);
  if (r.includes("no_qualified_category")) parts.push(l.practical_pending.length ? `${l.practical_pending.join(", ")}: training done — a supervised first job (or admin sign-off) activates it` : "complete at least one category module");
  if (r.includes("account_not_approved")) parts.push("our team reviews your application within 3–5 business days and you'll be notified");
  return parts.length ? parts.join(" · ").replace(/^./, (ch) => ch.toUpperCase()) + "." : "Complete training in the Training tab.";
}
const ACTIVE = ["assigned", "en_route", "arrived", "in_progress", "paused_safety", "return_visit_scheduled", "dispute_rejected", "issue_reported", "inspection_booked"];

export default function HomeScreen() {
  const nav = useNavigation<NativeStackNavigationProp<RootParams>>();
  const { user } = useSession();
  const { c } = useTheme();
  const [lock, setLock] = useState<Lock | null>(null); const [mine, setMine] = useState<Job[]>([]); const [market, setMarket] = useState<Job[]>([]); const [unread, setUnread] = useState(0);
  const [loading, setLoading] = useState(true); const [offline, setOffline] = useState(false); const [open, setOpen] = useState<string | null>(null); const [filter, setFilter] = useState<{ cat: string; dist: number } | null>(null); const [fsheet, setFsheet] = useState(false); const [fcat, setFcat] = useState("all"); const [fdist, setFdist] = useState(50);
  const S = (n: number, w: "400" | "500" | "600" | "700" = "400", col = c.text) => ({ fontSize: n, fontFamily: w === "400" ? font.regular : w === "500" ? font.medium : w === "600" ? font.semibold : font.bold, color: col });

  const load = useCallback(async () => {
    let q = "";
    try { const { status } = await Location.requestForegroundPermissionsAsync(); if (status === "granted") { const p = (await Location.getLastKnownPositionAsync()) ?? (await Location.getCurrentPositionAsync({})); if (p) q = `?lat=${p.coords.latitude}&lng=${p.coords.longitude}`; } } catch {}
    const [t, m, k, n] = await Promise.all([api<{ lock: Lock }>("/training"), api<Job[]>("/jobs/me?active=1&limit=50"), api<Job[]>(`/jobs${q}`), api("/notifications?limit=1")]);
    setOffline(!t.success && /connection/i.test(t.error ?? "")); setLock(t.data?.lock ?? null); setMine(m.data ?? []); setMarket(k.data ?? []); setUnread(n.meta?.unread ?? 0); setLoading(false);
  }, []);
  useFocusEffect(useCallback(() => { load(); }, [load]));
  const active = mine.find((j) => ACTIVE.includes(j.status));
  const shown = market.filter((j) => !filter || ((filter.cat === "all" || j.service_category === filter.cat) && (j.distance_miles == null || j.distance_miles <= filter.dist)));
  const dates = (j: Job) => j.preferred_start_date ? `${new Date(j.preferred_start_date).toLocaleDateString("en-US", { month: "short", day: "numeric" })}${j.preferred_end_date ? ` – ${new Date(j.preferred_end_date).toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" })}` : ""}` : "Flexible";
  async function accept(j: Job) { const r = await api(`/jobs/${j.id}/accept`, { method: "POST", body: {} }); if (r.success) nav.navigate("JobDetail", { id: j.id }); else load(); }
  const Info = ({ k, v, warn }: { k: string; v?: string | null; warn?: boolean }) => <View style={{ width: "48%", flexDirection: "row", justifyContent: "space-between", paddingVertical: 4 }}><RNText style={S(13, "400", c.text4)}>{k}</RNText><RNText style={{ ...S(13, "500", warn ? c.warn : c.text), textTransform: "capitalize" }}>{v ?? "—"}</RNText></View>;

  return (
    <SafeAreaView edges={["top"]} style={{ flex: 1, backgroundColor: c.bg }}>
      <View style={{ flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingHorizontal: 16, paddingVertical: 8 }}><RNText style={S(20, "700")}>Marketplace</RNText><Pressable onPress={() => nav.navigate("Notifications")} style={{ width: 40, height: 40, borderRadius: 12, borderWidth: 1, borderColor: c.border, backgroundColor: c.surface, alignItems: "center", justifyContent: "center" }}><Ionicons name="notifications-outline" size={20} color={c.text2} />{unread > 0 && <View style={{ position: "absolute", top: 8, right: 8, width: 8, height: 8, borderRadius: 4, backgroundColor: c.primary }} />}</Pressable></View>
      <ScrollView contentContainerStyle={{ padding: 16, paddingTop: 4, gap: 12 }}>
        <View style={{ backgroundColor: c.hero, borderRadius: 16, padding: 16, paddingHorizontal: 18, flexDirection: "row", alignItems: "center", justifyContent: "space-between" }}><View><RNText style={S(16, "600", "#fff")}>Welcome, {user?.first_name} 👋</RNText><RNText style={S(13, "400", "#B7BAC1")}>{lock?.locked ? "Finish training to unlock jobs" : "Ready for your next job?"}</RNText></View><View style={{ alignItems: "flex-end" }}><RNText style={S(11, "600", "#F9DBAF")}>New jobs</RNText><RNText style={S(24, "700", "#fff")}>{market.length}</RNText></View></View>
        {lock?.locked && <Pressable onPress={() => nav.navigate("Training")} style={{ flexDirection: "row", alignItems: "center", gap: 12, backgroundColor: c.warnBg, borderWidth: 1, borderColor: c.warnBd, borderRadius: 16, padding: 14 }}><View style={{ width: 44, height: 44, borderRadius: 12, backgroundColor: c.surface, alignItems: "center", justifyContent: "center" }}><Ionicons name="school-outline" size={22} color={c.warn} /></View><View style={{ flex: 1 }}><RNText style={S(14.5, "600", c.warn)}>{lock.reasons.includes("account_not_approved") && !lock.reasons.includes("core_incomplete") && !lock.reasons.includes("safety_incomplete") ? "Account under review" : "Marketplace locked"}</RNText><RNText style={S(12.5, "400", c.text3)}>{lockText(lock)}</RNText></View><Ionicons name="chevron-forward" size={18} color={c.warn} /></Pressable>}
        {active && <><Pressable onPress={() => nav.navigate("JobDetail", { id: active.id })} style={{ flexDirection: "row", alignItems: "center", gap: 12, backgroundColor: c.surface, borderWidth: 1, borderColor: c.orangeBd, borderRadius: 16, padding: 12, paddingHorizontal: 14 }}><View style={{ width: 44, height: 44, borderRadius: 12, backgroundColor: c.primarySoft, alignItems: "center", justifyContent: "center" }}><RNText style={S(10, "700", c.orange)}>{(active.scheduled_start ? new Date(active.scheduled_start) : new Date()).toLocaleDateString("en-US", { month: "short" }).toUpperCase()}</RNText><RNText style={S(17, "700", c.orange)}>{(active.scheduled_start ? new Date(active.scheduled_start) : new Date()).getDate()}</RNText></View><View style={{ flex: 1, gap: 1 }}><RNText style={S(12, "600", c.orange)}>{active.status === "in_progress" ? "In progress" : active.status === "paused_safety" ? "Paused for safety" : active.status === "en_route" ? "On the way" : active.status === "arrived" ? "On site" : "Your active job"}</RNText><RNText style={S(15, "600")}>{active.title}{active.scheduled_start ? ` · ${new Date(active.scheduled_start).toLocaleTimeString("en-US", { hour: "numeric", minute: "2-digit" })}` : ""}</RNText><RNText style={S(12.5, "400", c.text4)}>{active.location_address}, {active.location_city}{active.distance_miles != null ? ` · ${active.distance_miles.toFixed(1)} mi` : ""}</RNText></View><Ionicons name="chevron-forward" size={18} color={c.text4} /></Pressable><Pressable onPress={() => nav.navigate("Schedule")} style={{ flexDirection: "row", alignItems: "center", gap: 6, alignSelf: "flex-start" }}><Ionicons name="calendar-outline" size={16} color={c.orange} /><RNText style={S(13.5, "600", c.orange)}>View my schedule</RNText></Pressable></>}
        <View style={{ flexDirection: "row", alignItems: "center", gap: 8 }}><Pressable onPress={() => setFsheet(true)} style={{ height: 40, paddingHorizontal: 14, borderRadius: 999, borderWidth: 1, borderColor: c.border2, backgroundColor: c.surface, flexDirection: "row", alignItems: "center", gap: 6 }}><Ionicons name="options-outline" size={16} color={c.text} /><RNText style={S(13.5, "600")}>Filter</RNText></Pressable>{filter && <><View style={{ height: 40, paddingHorizontal: 12, borderRadius: 999, backgroundColor: c.primarySoft, justifyContent: "center" }}><RNText style={{ ...S(13, "600", c.orange), textTransform: "capitalize" }}>{filter.cat === "all" ? "All" : filter.cat} · {filter.dist} mi</RNText></View><Pressable onPress={() => setFilter(null)}><RNText style={S(13.5, "500", c.text3)}>Clear</RNText></Pressable></>}</View>
        {offline && <View style={{ flexDirection: "row", alignItems: "center", gap: 10, padding: 12, borderRadius: 12, backgroundColor: c.warnBg }}><Ionicons name="cloud-offline-outline" size={18} color={c.warn} /><View style={{ flex: 1 }}><RNText style={S(13.5, "600", c.warn)}>You're offline</RNText><RNText style={S(12.5, "400", c.text3)}>Showing saved data · couldn't refresh</RNText></View><Pressable onPress={load} style={{ height: 32, paddingHorizontal: 10, borderRadius: 8, backgroundColor: c.surface, justifyContent: "center" }}><RNText style={S(12.5, "600", c.warn)}>Retry</RNText></Pressable></View>}
        {loading && [1, 2, 3].map((k) => <View key={k} style={{ height: 112, borderRadius: 16, backgroundColor: c.surface2 }} />)}
        {!loading && shown.length === 0 && <View style={{ alignItems: "center", gap: 8, paddingVertical: 24 }}><View style={{ width: 200, height: 200, alignItems: "center", justifyContent: "center" }}>{[200, 150, 100].map((d) => <View key={d} style={{ position: "absolute", width: d, height: d, borderRadius: d / 2, backgroundColor: c.primarySoft, opacity: 0.6 }} />)}<View style={{ width: 56, height: 56, borderRadius: 16, backgroundColor: c.surface, alignItems: "center", justifyContent: "center" }}><Ionicons name="briefcase-outline" size={26} color={c.primary} /></View></View><RNText style={S(17, "600")}>{lock?.locked ? "Unlock the marketplace" : filter ? "No jobs match your filter" : "No new jobs right now"}</RNText><RNText style={{ ...S(14, "400", c.text4), textAlign: "center" }}>{lock?.locked ? "Finish training to start receiving jobs." : "You'll get a notification when something comes in."}</RNText></View>}
        {shown.map((j) => { const ex = open === j.id; const spec = j.pergola_spec ?? {}; return (
          <View key={j.id} style={{ backgroundColor: c.surface, borderWidth: 1, borderColor: c.border, borderRadius: 16, padding: 14, gap: 12 }}>
            <View style={{ flexDirection: "row", justifyContent: "space-between", gap: 8 }}><View style={{ flex: 1, gap: 4 }}><RNText style={S(17, "600")}>{j.title}</RNText><View style={{ flexDirection: "row", alignItems: "center", gap: 4 }}><Ionicons name="location-outline" size={14} color={c.text3} /><RNText style={S(13, "400", c.text3)}>{j.location_city}, {j.location_state}{j.distance_miles != null ? ` · ${j.distance_miles.toFixed(1)} mi · ~${Math.round(j.distance_miles * 2.2)} min` : ""}</RNText></View></View><View style={{ gap: 4, alignItems: "flex-end" }}><View style={{ paddingHorizontal: 8, paddingVertical: 2, borderRadius: 999, backgroundColor: c.primarySoft }}><RNText style={S(12, "600", c.orange)}>{j.is_assessment ? "Assessment" : "New"}</RNText></View><View style={{ paddingHorizontal: 8, paddingVertical: 2, borderRadius: 999, backgroundColor: c.surface2 }}><RNText style={{ ...S(12, "600", c.text2), textTransform: "capitalize" }}>{j.service_category}</RNText></View></View></View>
            {j.issue_description && <RNText style={S(13.5, "400", c.text3)} numberOfLines={ex ? undefined : 2}>{j.issue_description}</RNText>}
            <View style={{ flexDirection: "row", justifyContent: "space-between", backgroundColor: c.bg, borderRadius: 12, padding: 10, paddingHorizontal: 12 }}><View><RNText style={S(12, "500", c.text4)}>Preferred dates</RNText><RNText style={S(14, "600")}>{dates(j)}</RNText></View><View style={{ alignItems: "flex-end" }}><RNText style={S(12, "500", c.text4)}>Your payout</RNText><RNText style={S(20, "700", c.primary)}>{money(j.contractor_net)}</RNText></View></View>
            <Pressable onPress={() => setOpen(ex ? null : j.id)} style={{ flexDirection: "row", alignItems: "center", gap: 6 }}><Ionicons name={ex ? "chevron-up" : "chevron-down"} size={16} color={c.text2} /><RNText style={S(13, "500", c.text3)}>{j.width_ft ? `${j.width_ft}×${j.length_ft}×${j.height_ft} ft · ` : ""}{j.mounting?.replace("_", " ")}</RNText><RNText style={S(13, "600", c.orange)}>{ex ? "Less" : "Details"}</RNText></Pressable>
            {ex && <View style={{ gap: 10 }}><View style={{ flexDirection: "row", flexWrap: "wrap", justifyContent: "space-between" }}><Info k="Structure" v={spec.structure_type?.replace("_", " ")} /><Info k="Mounting" v={j.mounting?.replace("_", " ")} /><Info k="Property" v="Residential" />{j.urgency && <Info k="Urgency" v={j.urgency} warn />}</View>{j.notes && <View style={{ padding: 10, borderRadius: 10, backgroundColor: c.surface2 }}><RNText style={S(13, "400", c.text2)}><RNText style={S(13, "600")}>Client notes:</RNText> {j.notes}</RNText></View>}<View style={{ flexDirection: "row", gap: 8 }}>{[["Width", j.width_ft], ["Length", j.length_ft], ["Height", j.height_ft]].map(([k, v]) => <View key={k} style={{ flex: 1, backgroundColor: c.surface2, borderRadius: 10, padding: 10 }}><RNText style={S(12, "400", c.text4)}>{k}</RNText><RNText style={S(15, "600")}>{v ? `${v}'` : "—"}</RNText></View>)}</View></View>}
            <View style={{ flexDirection: "row", gap: 8 }}><SecondaryButton title="Decline" style={{ flex: 1 }} onPress={async () => { await api(`/jobs/${j.id}/decline`, { method: "POST", body: { reason: "not_available" } }); load(); }} /><Pressable disabled={!!lock?.locked} onPress={() => accept(j)} style={{ flex: 1.4, height: 48, borderRadius: 12, backgroundColor: lock?.locked ? c.surface3 : c.primary, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8 }}><Ionicons name="checkmark" size={18} color={lock?.locked ? c.text4 : "#fff"} /><RNText style={S(15, "600", lock?.locked ? c.text4 : "#fff")}>Accept job</RNText></Pressable></View>
          </View>); })}
      </ScrollView>
      <Sheet open={fsheet} onClose={() => setFsheet(false)} title="Filter jobs">
        <View style={{ gap: 8 }}>{[["all", "All categories"], ["installation", "Installation"], ["repair", "Repair"], ["maintenance", "Maintenance"], ["cleaning", "Cleaning"], ["inspection", "Inspection"]].map(([k, l]) => <ChoiceRow key={k} title={l} on={fcat === k} onPress={() => setFcat(k)} />)}</View>
        <View style={{ gap: 6 }}><RNText style={S(13, "600", c.text2)}>Max distance</RNText><View style={{ flexDirection: "row", gap: 8 }}>{[10, 25, 50, 100].map((d) => <Pressable key={d} onPress={() => setFdist(d)} style={{ flex: 1, height: 40, borderRadius: 10, borderWidth: 1.5, borderColor: fdist === d ? c.primary : c.border2, backgroundColor: fdist === d ? c.primarySoft : c.surface, alignItems: "center", justifyContent: "center" }}><RNText style={S(14, "600")}>{d} mi</RNText></Pressable>)}</View></View>
        <PrimaryButton title="Apply" onPress={() => { setFilter({ cat: fcat, dist: fdist }); setFsheet(false); }} />
      </Sheet>
    </SafeAreaView>
  );
}
