import React, { useCallback, useState } from "react";
import { Alert, Image, Linking, Pressable, ScrollView, Text as RNText, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { useFocusEffect, useNavigation, useRoute } from "@react-navigation/native";
import { NativeStackNavigationProp } from "@react-navigation/native-stack";
import { Ionicons } from "@expo/vector-icons";
import * as ImagePicker from "expo-image-picker";
import { Field, PrimaryButton, SecondaryButton } from "../../components/form";
import { Header, Sheet } from "../../components/sheet";
import { money } from "../../components";
import { api, Category, Job, uploadFile } from "../../api/client";
import { useTheme } from "../../theme/ThemeProvider";
import { font } from "../../theme/tokens";
import { RootParams } from "../../navigation";

interface Ev { id: string; kind: string; url: string; note: string | null; created_at: string }
interface Event { event_type: string; created_at: string; payload?: Record<string, unknown> | null }
interface Proposal { id: string; proposed_by: string; kind: string; proposed_start: string; message: string | null; status: string }
interface Rating { rating: number; comment: string | null; rater_role: string }
const fmtD = (v?: string | null, t = false) => (v ? new Date(v).toLocaleString("en-US", t ? { month: "short", day: "numeric", hour: "numeric", minute: "2-digit" } : { month: "short", day: "numeric", year: "numeric" }) : "");
const DONE = ["completed_paid", "dispute_upheld"], CANC = ["cancelled_by_client", "cancelled_by_contractor", "quote_declined"];

export default function JobDetailScreen() {
  const nav = useNavigation<NativeStackNavigationProp<RootParams>>();
  const { params } = useRoute<{ key: string; name: string; params: { id: string } }>();
  const { c } = useTheme();
  const [j, setJ] = useState<Job | null>(null); const [cat, setCat] = useState<Category | null>(null); const [ev, setEv] = useState<Ev[]>([]); const [events, setEvents] = useState<Event[]>([]); const [props, setProps] = useState<Proposal[]>([]); const [ratings, setRatings] = useState<Rating[]>([]);
  const [busy, setBusy] = useState(false); const [sheet, setSheet] = useState<null | "enroute" | "start" | "complete" | "pause" | "cancel" | "reschedule">(null);
  const [eta, setEta] = useState("15"); const [note, setNote] = useState(""); const [damage, setDamage] = useState(false); const [photos, setPhotos] = useState<string[]>([]); const [reason, setReason] = useState(""); const [when, setWhen] = useState("");
  const S = (n: number, w: "400" | "500" | "600" | "700" = "400", col = c.text) => ({ fontSize: n, fontFamily: w === "400" ? font.regular : w === "500" ? font.medium : w === "600" ? font.semibold : font.bold, color: col });

  const load = useCallback(async () => {
    const r = await api<Job>(`/jobs/${params.id}`); if (!r.data) return; setJ(r.data);
    const [k, e, x, p, rt] = await Promise.all([api<Category[]>("/categories"), api<{ items: Ev[] }>(`/jobs/${params.id}/evidence`), api<Event[]>(`/jobs/${params.id}/events`), api<Proposal[]>(`/jobs/${params.id}/reschedule`), api<Rating[]>(`/jobs/${params.id}/ratings`)]);
    setCat((k.data ?? []).find((z) => z.slug === r.data!.service_category) ?? null); setEv(e.data?.items ?? []); setEvents(x.data ?? []); setProps(p.data ?? []); setRatings(rt.data ?? []);
  }, [params.id]);
  useFocusEffect(useCallback(() => { load(); }, [load]));

  async function act(path: string, body: unknown = {}, method = "POST") {
    setBusy(true); const r = await api(`/jobs/${params.id}/${path}`, { method, body }); setBusy(false);
    if (!r.success) { Alert.alert("Not allowed", (r.error ?? "") + (r.missing ? `\n\nMissing: ${r.missing.join(", ")}` : "")); return false; }
    setSheet(null); setNote(""); setPhotos([]); load(); return true;
  }
  async function shoot(kind: "area" | "product" | "damage" | "completion") {
    const perm = await ImagePicker.requestCameraPermissionsAsync();
    const res = perm.granted ? await ImagePicker.launchCameraAsync({ quality: 0.7 }) : await ImagePicker.launchImageLibraryAsync({ quality: 0.7 });
    if (res.canceled || !res.assets[0]) return;
    setBusy(true); const url = await uploadFile(res.assets[0].uri, "evidence"); setBusy(false);
    if (!url) { Alert.alert("Upload failed", "Photo storage isn't configured yet."); return; }
    if (kind === "completion") { setPhotos((p) => [...p, url]); return; }
    let n: string | undefined; if (kind === "damage") { n = await new Promise<string | undefined>((res) => Alert.prompt("Describe the damage", "Recorded so it isn't attributed to you.", (t) => res(t))); if (!n) return; }
    const r = await api(`/jobs/${params.id}/evidence`, { method: "POST", body: { kind, url, note: n, captured_at: new Date().toISOString() } }); if (!r.success) Alert.alert("Error", r.error); load();
  }
  async function toggleCheck(id: string) { if (!j) return; const done = j.checklist_done.includes(id) ? j.checklist_done.filter((x) => x !== id) : [...j.checklist_done, id]; await api(`/jobs/${params.id}/checklist`, { method: "PUT", body: { items: done } }); load(); }
  async function openChat() { const r = await api<{ id: string }>(`/jobs/${params.id}/conversation`, { method: "POST", body: {} }); if (r.data && j?.consumer) nav.navigate("Chat", { id: r.data.id, title: `${j.consumer.first_name} ${j.consumer.last_name}` }); }

  if (!j) return <SafeAreaView style={{ flex: 1, backgroundColor: c.bg }}><Header title="Job" onBack={() => nav.goBack()} /></SafeAreaView>;
  const st = j.status; const mine = !!j.contractor; const client = j.consumer; const cname = client ? `${client.first_name} ${client.last_name}` : "Client"; const cfirst = client?.first_name ?? "Client";
  const checklist = cat?.pre_job_checklist ?? []; const ckDone = checklist.filter((i) => j.checklist_done.includes(i.id)).length;
  const counts = { area: ev.filter((e) => e.kind === "area").length, product: ev.filter((e) => e.kind === "product").length, damage: ev.filter((e) => e.kind === "damage").length };
  const pre = ["assigned", "en_route", "arrived"].includes(st); const spec = j.pergola_spec ?? {}; const evAt = (t: string) => events.find((e) => e.event_type === t)?.created_at;
  const pendingProp = props.find((p) => p.status === "pending" && p.proposed_by !== "contractor"); const isInsp = j.service_category === "inspection" || (j.quote_method === "inspection" && st === "inspection_booked");
  const clientRating = ratings.find((r) => r.rater_role === "consumer"), myRating = ratings.find((r) => r.rater_role === "contractor");
  const address = [j.location_address, j.location_city, j.location_state].filter(Boolean).join(", ");

  type Step = { t: string; sub?: string; kind: "done" | "cur" | "todo" | "err" | "info"; n?: number };
  const steps: Step[] = []; const D = (t: string, sub?: string) => steps.push({ t, sub, kind: "done" }), C = (t: string, sub?: string) => steps.push({ t, sub, kind: "cur" }), T = (t: string) => steps.push({ t, kind: "todo", n: steps.length + 1 }), E = (t: string, sub?: string) => steps.push({ t, sub, kind: "err" }), I = (t: string, sub?: string) => steps.push({ t, sub, kind: "info" });
  if (mine) {
    D("Accepted", `You accepted this job on ${fmtD(evAt("accepted") ?? j.updated_at)}.`);
    if (isInsp) { if (evAt("inspection_submitted")) D("Visit & inspect", fmtD(evAt("arrived"))); else C("Visit & inspect", j.scheduled_start ? fmtD(j.scheduled_start, true) : address); if (evAt("inspection_submitted")) { D("Report & quote submitted", fmtD(evAt("inspection_submitted"))); C("Waiting for client approval", "Quote valid 14 days"); } else T("Submit report & quote"); T("Job converts to installation"); }
    else {
      if (pendingProp) I("Client proposed a new time", fmtD(pendingProp.proposed_start, true));
      if (evAt("started")) D("Job started", `${fmtD(evAt("started"), true)} · site check complete`); else if (CANC.includes(st)) E(st === "cancelled_by_client" ? "Cancelled by client" : "You cancelled", fmtD(j.updated_at)); else C("Job started", st === "assigned" ? "Tap On my way, then Arrived, then complete the site check." : st === "en_route" ? "On the way" : st === "arrived" ? "On site · photos & checklist" : undefined);
      if (st === "paused_safety") E("Paused for safety", j.pause_reason ?? undefined);
      if (evAt("completed")) D("You completed the job", fmtD(evAt("completed"))); else if (!CANC.includes(st)) (evAt("started") ? C : T)("You completed the job");
      if (["issue_reported", "dispute_open", "dispute_rejected", "return_visit_scheduled"].includes(st) || (evAt("issue_reported") && !DONE.includes(st))) E("Client reported an issue", fmtD(evAt("issue_reported")));
      if (st === "dispute_open") { I("You disputed the feedback", fmtD(evAt("dispute_opened"))); C("Under review", "Our team is reviewing your dispute."); }
      if (evAt("fix_done")) D("You completed the fix", fmtD(evAt("fix_done")));
      if (DONE.includes(st)) D("Client confirmed & paid", `${fmtD(j.paid_at)} · ${money((j.contractor_net ?? 0) + j.tip)} payout${j.tip ? ` incl. ${money(j.tip)} tip` : ""}`); else if (st === "awaiting_confirmation") C("Awaiting client confirmation", j.auto_confirm_at ? `${cfirst} has until ${fmtD(j.auto_confirm_at, true)} to confirm or report an issue` : undefined); else if (!CANC.includes(st)) T("Client confirmed & paid");
    }
  }
  const alert = st === "issue_reported" ? ["warn", "Client reported an issue", "Please review their feedback and complete the remaining tasks to finish the project and receive payment.", "View client's feedback", () => nav.navigate("ClientComment", { id: j.id })] : pendingProp ? ["warn", `${cname} asked to reschedule`, `Original slot ${fmtD(j.scheduled_start, true)} stays booked until you respond.`, "Suggest another time", () => setSheet("reschedule")] : st === "paused_safety" ? ["err", "Work paused for safety", "The client and MrBuilder were notified. No fee, no rating impact. Resume when it's safe.", null, null] : isInsp && !evAt("inspection_submitted") ? ["info", `Inspection job · ${money(j.inspection_fee)} fee prepaid by client`, `Your report replaces the AI estimate. If ${cfirst} approves the quote, the job is created for you automatically.`, null, null] : st === "dispute_open" ? ["info", "Dispute under review", "MrBuilder will decide and notify both sides.", null, null] : st === "dispute_rejected" ? ["warn", "Fix required", "MrBuilder reviewed the dispute — please complete the remaining work.", "Propose a return visit", () => setSheet("reschedule")] : null;
  const tone = (t: string) => ({ warn: [c.warnBg, c.warnBd, c.warn], err: [c.errBg, c.errBd, c.err], info: [c.infoBg, c.infoBd, c.info] }[t] ?? [c.surface2, c.border, c.text]);
  const Card = ({ children, style }: { children: React.ReactNode; style?: object }) => <View style={[{ backgroundColor: c.surface, borderWidth: 1, borderColor: c.border, borderRadius: 16, padding: 16, gap: 12 }, style]}>{children}</View>;
  const Title = ({ icon, t, right }: { icon: keyof typeof Ionicons.glyphMap; t: string; right?: React.ReactNode }) => <View style={{ flexDirection: "row", alignItems: "center", justifyContent: "space-between" }}><View style={{ flexDirection: "row", alignItems: "center", gap: 8 }}><Ionicons name={icon} size={18} color={c.text2} /><RNText style={S(15, "600")}>{t}</RNText></View>{right}</View>;
  const KV = ({ rows }: { rows: [string, React.ReactNode, string?][] }) => <View style={{ gap: 6 }}>{rows.map(([k, v, col]) => <View key={k} style={{ flexDirection: "row", justifyContent: "space-between", gap: 12 }}><RNText style={S(14, "400", c.text4)}>{k}</RNText><RNText style={{ flex: 1, textAlign: "right", ...S(14, "500", col ?? c.text) }}>{v}</RNText></View>)}</View>;

  // footer CTA
  let cta: { t: string; fn: () => void; help?: string; kind?: "primary" | "danger" } | null = null;
  if (!mine) cta = { t: "Accept job", fn: () => act("accept") };
  else if (st === "assigned") cta = { t: "On my way", fn: () => setSheet("enroute"), help: "Share your ETA with the client." };
  else if (st === "en_route") cta = { t: "I've arrived", fn: () => act("arrived") };
  else if (st === "arrived" && isInsp) cta = { t: "Submit report & quote", fn: () => nav.navigate("InspectionReport", { id: j.id }), help: "After the visit: findings, photos and an itemized quote." };
  else if (st === "arrived") cta = { t: "Start job", fn: () => setSheet("start"), help: `Checklist ${ckDone}/${checklist.length} · area ${counts.area}/3 · product ${counts.product}/1 — complete before starting.` };
  else if (st === "in_progress") cta = { t: "Mark as completed", fn: () => setSheet("complete"), help: "Tap this once the job is fully done." };
  else if (st === "paused_safety") cta = { t: "Resume work", fn: () => act("resume") };
  else if (st === "issue_reported") cta = { t: "View client's feedback", fn: () => nav.navigate("ClientComment", { id: j.id }) };
  else if (["dispute_rejected", "return_visit_scheduled"].includes(st)) cta = { t: "Fix done", fn: () => setSheet("complete") };
  else if (DONE.includes(st) && !myRating) cta = { t: "Leave a rating", fn: () => nav.navigate("RateClient", { id: j.id }) };

  return (
    <SafeAreaView edges={["top"]} style={{ flex: 1, backgroundColor: c.bg }}>
      <Header title={j.request_code} onBack={() => nav.goBack()} right={mine && client ? <Pressable onPress={openChat} style={{ width: 40, height: 40, borderRadius: 12, borderWidth: 1, borderColor: c.border, alignItems: "center", justifyContent: "center" }}><Ionicons name="chatbubble-ellipses-outline" size={20} color={c.text2} /></Pressable> : undefined} />
      <ScrollView contentContainerStyle={{ padding: 16, paddingBottom: 24, gap: 12 }}>
        <Card style={{ padding: 0, gap: 0, overflow: "hidden" }}>
          <View style={{ flexDirection: "row", justifyContent: "space-between", padding: 14, paddingHorizontal: 16, backgroundColor: c.bg }}><View><RNText style={S(12, "500", c.text4)}>{isInsp ? "Visit window" : "Preferred dates"}</RNText><RNText style={S(14, "600")}>{j.scheduled_start ? fmtD(j.scheduled_start, true) : j.preferred_start_date ? `${fmtD(j.preferred_start_date)}${j.preferred_end_date ? ` – ${fmtD(j.preferred_end_date)}` : ""}` : "Flexible"}</RNText></View><View style={{ alignItems: "flex-end" }}><RNText style={S(12, "500", c.text4)}>{isInsp ? "Inspection fee" : "Your payout"}</RNText><RNText style={S(20, "700", c.primary)}>{money(isInsp ? j.inspection_fee : j.contractor_net)}</RNText></View></View>
          {mine && <View style={{ padding: 16, gap: 0 }}>{steps.map((s, i) => <View key={i} style={{ flexDirection: "row", gap: 12 }}><View style={{ alignItems: "center", width: 26 }}>{s.kind === "done" ? <View style={{ width: 26, height: 26, borderRadius: 13, backgroundColor: "#079455", alignItems: "center", justifyContent: "center" }}><Ionicons name="checkmark" size={15} color="#fff" /></View> : s.kind === "cur" ? <View style={{ width: 26, height: 26, borderRadius: 13, backgroundColor: c.primarySoft, alignItems: "center", justifyContent: "center" }}><View style={{ width: 10, height: 10, borderRadius: 5, backgroundColor: c.primary }} /></View> : s.kind === "err" ? <View style={{ width: 26, height: 26, borderRadius: 13, backgroundColor: "#D92D20", alignItems: "center", justifyContent: "center" }}><Ionicons name="alert" size={15} color="#fff" /></View> : s.kind === "info" ? <View style={{ width: 26, height: 26, borderRadius: 13, backgroundColor: c.info, alignItems: "center", justifyContent: "center" }}><Ionicons name="information" size={15} color="#fff" /></View> : <View style={{ width: 26, height: 26, borderRadius: 13, borderWidth: 1, borderColor: c.border2, alignItems: "center", justifyContent: "center" }}><RNText style={S(12, "600", c.text5)}>{s.n}</RNText></View>}{i < steps.length - 1 && <View style={{ flex: 1, width: 2, backgroundColor: s.kind === "done" ? "#079455" : c.border, marginVertical: 3 }} />}</View><View style={{ flex: 1, paddingBottom: i < steps.length - 1 ? 16 : 0 }}><RNText style={S(14.5, "600", s.kind === "todo" ? c.text5 : s.kind === "err" ? c.err : c.text)}>{s.t}</RNText>{s.sub && <RNText style={S(13, "400", c.text4)}>{s.sub}</RNText>}</View></View>)}</View>}
          {alert && <View style={{ margin: 16, marginTop: 0, flexDirection: "row", gap: 10, padding: 12, paddingHorizontal: 14, borderRadius: 12, backgroundColor: tone(alert[0] as string)[0], borderWidth: 1, borderColor: tone(alert[0] as string)[1] }}><Ionicons name="information-circle-outline" size={20} color={tone(alert[0] as string)[2]} /><View style={{ flex: 1, gap: 2 }}><RNText style={S(14, "600", tone(alert[0] as string)[2])}>{alert[1] as string}</RNText><RNText style={S(13, "400", c.text2)}>{alert[2] as string}</RNText>{alert[3] && <Pressable onPress={alert[4] as () => void}><RNText style={{ ...S(13, "600", tone(alert[0] as string)[2]), textDecorationLine: "underline", marginTop: 4 }}>{alert[3] as string}</RNText></Pressable>}</View></View>}
        </Card>

        {mine && pre && !isInsp && (
          <Card>
            <Title icon="clipboard-outline" t="Pre-job checklist" right={<RNText style={S(12.5, "600", ckDone === checklist.length ? c.ok : c.warn)}>{ckDone}/{checklist.length}</RNText>} />
            <View style={{ height: 6, borderRadius: 3, backgroundColor: c.surface3 }}><View style={{ width: `${checklist.length ? (ckDone / checklist.length) * 100 : 0}%`, height: 6, borderRadius: 3, backgroundColor: "#079455" }} /></View>
            {checklist.map((i) => { const on = j.checklist_done.includes(i.id); return <Pressable key={i.id} onPress={() => toggleCheck(i.id)} style={{ flexDirection: "row", alignItems: "center", gap: 10, paddingVertical: 4 }}><View style={{ width: 22, height: 22, borderRadius: 7, backgroundColor: on ? "#079455" : c.surface3, alignItems: "center", justifyContent: "center" }}>{on && <Ionicons name="checkmark" size={14} color="#fff" />}</View><RNText style={{ flex: 1, ...S(14, "400", on ? c.text : c.text2) }}>{i.text}{i.critical ? " *" : ""}</RNText></Pressable>; })}
            <RNText style={S(12.5, "400", c.text4)}>Category: {j.service_category} · complete before you tap Start job</RNText>
            <View style={{ borderTopWidth: 1, borderTopColor: c.border, paddingTop: 12, gap: 8 }}><RNText style={S(13, "600")}>Before-work photos</RNText><RNText style={S(12.5, "400", c.text4)}>3 work-area + 1 product photo required. Shared with the client and locked after Start.</RNText><View style={{ flexDirection: "row", gap: 8, flexWrap: "wrap" }}>{[["area", `Area ${counts.area}/3`, counts.area >= 3], ["product", `Product ${counts.product}/1`, counts.product >= 1], ["damage", `Damage ${counts.damage}`, false]].map(([k, l, ok]) => <Pressable key={k as string} onPress={() => { if (k === "damage") setDamage(true); shoot(k as "area"); }} style={{ height: 36, paddingHorizontal: 12, borderRadius: 9, backgroundColor: ok ? c.okBg : k === "damage" ? c.surface2 : c.primary, flexDirection: "row", alignItems: "center", gap: 6 }}><Ionicons name={ok ? "checkmark" : "camera-outline"} size={15} color={ok ? c.ok : k === "damage" ? c.text : "#fff"} /><RNText style={S(13, "600", ok ? c.ok : k === "damage" ? c.text : "#fff")}>{l as string}</RNText></Pressable>)}</View>{ev.length > 0 && <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{ gap: 6 }}>{ev.map((e) => <Image key={e.id} source={{ uri: e.url }} style={{ width: 64, height: 64, borderRadius: 8, backgroundColor: c.surface2, borderWidth: e.kind === "damage" ? 2 : 0, borderColor: c.err }} />)}</ScrollView>}</View>
          </Card>
        )}
        {DONE.includes(st) && (clientRating || myRating) && <Card><Title icon="star-outline" t="Rating & Feedback" />{[clientRating && [cfirst, clientRating], myRating && ["Your comment", myRating]].filter(Boolean).map((x) => { const [n, r] = x as [string, Rating]; return <View key={n} style={{ backgroundColor: c.bg, borderRadius: 12, padding: 12, gap: 4 }}><View style={{ flexDirection: "row", justifyContent: "space-between" }}><RNText style={S(13, "600", c.text2)}>{n}</RNText><RNText style={S(13, "700")}>★ {r.rating}.0</RNText></View>{r.comment && <RNText style={S(13.5, "400", c.text3)}>{r.comment}</RNText>}</View>; })}</Card>}
        {DONE.includes(st) && <Card><Title icon="cash-outline" t="Payment details" /><KV rows={[["Base pay", money(j.contractor_net)], ["Tip", j.tip ? `+ ${money(j.tip)}` : "—", j.tip ? "#079455" : undefined], ["Platform fee (MrBuilder)", `– ${money(j.platform_fee)}`]]} /><View style={{ flexDirection: "row", justifyContent: "space-between", alignItems: "center", paddingTop: 10, borderTopWidth: 1, borderTopColor: c.border }}><RNText style={S(14, "600")}>Total payout</RNText><RNText style={S(20, "700")}>{money((j.contractor_net ?? 0) + j.tip)}</RNText></View><SecondaryButton title="Receipt.pdf" height={44} icon={<Ionicons name="document-outline" size={16} color={c.text} />} onPress={() => nav.navigate("Tabs", { screen: "Profile" })} /></Card>}

        <Card>
          <View style={{ flexDirection: "row", alignItems: "center", gap: 12 }}><View style={{ width: 44, height: 44, borderRadius: 22, backgroundColor: c.hero, alignItems: "center", justifyContent: "center" }}><RNText style={S(15, "700", "#fff")}>{client ? `${client.first_name[0]}${client.last_name[0]}` : "?"}</RNText></View><View style={{ flex: 1 }}><RNText style={S(15, "600")}>{mine ? cname : `${client?.first_name ?? "Client"} · shown after accept`}</RNText><RNText style={S(12.5, "400", c.text4)}>{mine ? (j.consumer?.phone ?? "Client") : "Contact unlocks once you accept"}</RNText></View>{mine && !DONE.includes(st) && !CANC.includes(st) ? <View style={{ flexDirection: "row", gap: 8 }}>{client?.phone && <Pressable onPress={() => Linking.openURL(`tel:${client.phone}`)} style={{ width: 40, height: 40, borderRadius: 12, borderWidth: 1, borderColor: c.border, alignItems: "center", justifyContent: "center" }}><Ionicons name="call-outline" size={18} color={c.text2} /></Pressable>}<Pressable onPress={openChat} style={{ width: 40, height: 40, borderRadius: 12, backgroundColor: c.primary, alignItems: "center", justifyContent: "center" }}><Ionicons name="chatbubble-outline" size={18} color="#fff" /></Pressable></View> : mine ? <View style={{ paddingHorizontal: 8, paddingVertical: 4, borderRadius: 999, backgroundColor: c.surface2, flexDirection: "row", alignItems: "center", gap: 4 }}><Ionicons name="lock-closed-outline" size={12} color={c.text4} /><RNText style={S(12, "600", c.text4)}>Chat closed</RNText></View> : null}</View>
          {(j.issue_description || j.notes) && <RNText style={S(13.5, "400", c.text3)}>{j.issue_description ?? j.notes}</RNText>}
        </Card>
        <Card>
          <Title icon="cube-outline" t="Structure details" />
          <KV rows={[["Structure type", (spec as { type?: string }).type ?? spec.structure_type?.replace("_", " ") ?? "—"], ["Mounting", j.mounting?.replace("_", " ") ?? "—"], ["Property", "Residential"], ["Address", mine ? address : `${j.location_city}, ${j.location_state}`], ["Request ID", j.request_code]]} />
          {j.notes && <View style={{ padding: 10, borderRadius: 10, backgroundColor: c.surface2 }}><RNText style={S(13, "400", c.text2)}><RNText style={S(13, "600")}>Client notes:</RNText> {j.notes}</RNText></View>}
          {!!spec.enclosures?.length && <View style={{ gap: 6 }}><RNText style={S(12, "700", c.text4)}>SIDE ENCLOSURES & SUBSYSTEMS · {spec.enclosures.length}</RNText>{spec.enclosures.map((e, i) => { const x = e as { label?: string; type: string; width_ft?: number; length_ft?: number; height_ft?: number; location?: string }; return <View key={i} style={{ padding: 10, borderRadius: 10, backgroundColor: c.surface2, flexDirection: "row", justifyContent: "space-between" }}><RNText style={S(13, "600")}>{i + 1} · {x.label ?? x.type}</RNText><RNText style={S(13, "400", c.text3)}>{x.width_ft ? `W ${x.width_ft} × L ${x.length_ft} × H ${x.height_ft} ft` : ""}{x.location ? ` · ${x.location}` : ""}</RNText></View>; })}</View>}
          {spec.footings?.involved && <View style={{ gap: 6 }}><RNText style={S(12, "700", c.text4)}>FOOTINGS</RNText><View style={{ padding: 10, borderRadius: 10, backgroundColor: c.surface2, flexDirection: "row", justifyContent: "space-between" }}><RNText style={S(13, "600")}>{spec.footings.count} footings · client-provided</RNText><RNText style={S(13, "600", c.warn)}>{spec.footings.ready ? "In place" : "NOT ready"}</RNText></View><RNText style={S(12, "400", c.text4)}>Footings must be complete and ready before installation. Verify on arrival; do not build footings.</RNText></View>}
          {!!spec.accessories?.length && <View style={{ gap: 6 }}><RNText style={S(12, "700", c.text4)}>ACCESSORIES · MOUNTING ONLY</RNText><View style={{ flexDirection: "row", flexWrap: "wrap", gap: 6 }}>{spec.accessories.map((a, i) => <View key={i} style={{ height: 28, paddingHorizontal: 10, borderRadius: 999, backgroundColor: c.surface2, justifyContent: "center" }}><RNText style={S(13, "500")}>{(a as { label?: string }).label ?? a.type} × {a.qty}</RNText></View>)}</View><RNText style={S(12, "400", c.text4)}>Electrical wiring, power, gas, plumbing and water-supply work are excluded.</RNText></View>}
          <View style={{ flexDirection: "row", gap: 8 }}>{[["Width", j.width_ft], ["Length", j.length_ft], ["Height", j.height_ft]].map(([k, v]) => <View key={k} style={{ flex: 1, backgroundColor: c.surface2, borderRadius: 10, padding: 10 }}><RNText style={S(12, "400", c.text4)}>{k}</RNText><RNText style={S(15, "600")}>{v ? `${v}'` : "—"}</RNText></View>)}</View>
        </Card>
        {mine && <Card><View style={{ flexDirection: "row", alignItems: "center", gap: 10 }}><Ionicons name="location-outline" size={18} color={c.text2} /><RNText style={{ flex: 1, ...S(14, "600") }}>{address}</RNText><Pressable onPress={() => Linking.openURL(`https://maps.google.com/?q=${encodeURIComponent(address)}`)} style={{ height: 36, paddingHorizontal: 12, borderRadius: 10, backgroundColor: c.primary, flexDirection: "row", alignItems: "center", gap: 6 }}><Ionicons name="navigate-outline" size={15} color="#fff" /><RNText style={S(13, "600", "#fff")}>Navigate</RNText></Pressable></View><View style={{ height: 150, borderRadius: 12, backgroundColor: c.surface2, alignItems: "center", justifyContent: "center" }}><Ionicons name="map-outline" size={30} color={c.text4} /><RNText style={S(12, "400", c.text4)}>Map opens in Google Maps</RNText></View></Card>}
        {!!j.images?.length && <Card><Title icon="images-outline" t="Images & files" /><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{ gap: 8 }}>{j.images.map((u, i) => <Pressable key={i} onPress={() => nav.navigate("Gallery", { photos: j.images.map((x) => ({ url: typeof x === "string" ? x : (x as { url: string }).url, label: (x as { label?: string }).label ?? "Client photo" })), index: i })}><Image source={{ uri: typeof u === "string" ? u : (u as { url: string }).url }} style={{ width: 110, height: 110, borderRadius: 12, backgroundColor: c.surface2 }} /></Pressable>)}</ScrollView></Card>}
        {mine && !DONE.includes(st) && !CANC.includes(st) && <Pressable onPress={() => nav.navigate("Store", { jobId: j.id })} style={{ flexDirection: "row", alignItems: "center", gap: 12, backgroundColor: c.surface, borderWidth: 1, borderColor: c.border, borderRadius: 16, padding: 14 }}><View style={{ width: 40, height: 40, borderRadius: 12, backgroundColor: c.primarySoft, alignItems: "center", justifyContent: "center" }}><Ionicons name="cart-outline" size={20} color={c.primary} /></View><View style={{ flex: 1 }}><RNText style={S(15, "600")}>Order parts for this job</RNText><RNText style={S(12.5, "400", c.text4)}>Mr Supply · shipped to the job address</RNText></View><Ionicons name="chevron-forward" size={18} color={c.text4} /></Pressable>}
        {mine && ["assigned", "en_route", "arrived", "in_progress"].includes(st) && <SecondaryButton title="Cancel the job" tone="danger" icon={<Ionicons name="close-circle-outline" size={18} color={c.err} />} onPress={() => setSheet("cancel")} />}
      </ScrollView>
      {cta && <View style={{ padding: 12, paddingHorizontal: 16, paddingBottom: 30, backgroundColor: c.surface, borderTopWidth: 1, borderTopColor: c.border, gap: 6 }}><PrimaryButton title={cta.t} onPress={cta.fn} loading={busy} />{cta.help && <RNText style={{ textAlign: "center", ...S(12, "400", c.text4) }}>{cta.help}</RNText>}</View>}

      <Sheet open={sheet === "enroute"} onClose={() => setSheet(null)} title="On my way"><RNText style={{ ...S(14, "400", c.text3), marginTop: -8 }}>{cfirst} will see your ETA and get a notification.</RNText><View style={{ flexDirection: "row", gap: 8 }}>{["10", "15", "30", "45", "60"].map((m) => <Pressable key={m} onPress={() => setEta(m)} style={{ flex: 1, height: 44, borderRadius: 10, borderWidth: 1.5, borderColor: eta === m ? c.primary : c.border2, backgroundColor: eta === m ? c.primarySoft : c.surface, alignItems: "center", justifyContent: "center" }}><RNText style={S(14, "600")}>{m} min</RNText></Pressable>)}</View><PrimaryButton title={`Share ETA · ${eta} min`} onPress={() => act("en-route", { eta_minutes: Number(eta) })} loading={busy} /></Sheet>
      <Sheet open={sheet === "start"} onClose={() => setSheet(null)} title="Start job?"><RNText style={{ ...S(14, "400", c.text3), marginTop: -8 }}>Before-work photos lock when you start. Checklist {ckDone}/{checklist.length} · area photos {counts.area}/3 · product {counts.product}/1.</RNText><Pressable onPress={() => setDamage(!damage)} style={{ flexDirection: "row", alignItems: "center", gap: 10 }}><View style={{ width: 22, height: 22, borderRadius: 7, backgroundColor: damage ? c.err : c.surface3, alignItems: "center", justifyContent: "center" }}>{damage && <Ionicons name="checkmark" size={14} color="#fff" />}</View><RNText style={{ flex: 1, ...S(14, "400") }}>Existing damage present (needs a damage photo with note)</RNText></Pressable><PrimaryButton title="Start job" onPress={() => act("start", { damage_present: damage })} loading={busy} /></Sheet>
      <Sheet open={sheet === "complete"} onClose={() => setSheet(null)} title={["dispute_rejected", "return_visit_scheduled"].includes(st) ? "Fix done?" : "Mark as completed?"}><RNText style={{ ...S(14, "400", c.text3), marginTop: -8 }}>Add at least 2 completion photos and a short note. {cfirst} reviews them before payment is released.</RNText><View style={{ flexDirection: "row", gap: 8, flexWrap: "wrap" }}>{photos.map((u, i) => <Image key={i} source={{ uri: u }} style={{ width: 72, height: 72, borderRadius: 10, backgroundColor: c.surface2 }} />)}<Pressable onPress={() => shoot("completion")} style={{ width: 72, height: 72, borderRadius: 10, borderWidth: 1.5, borderStyle: "dashed", borderColor: c.border2, alignItems: "center", justifyContent: "center" }}><Ionicons name="camera-outline" size={22} color={c.text4} /></Pressable></View><Field label="Completion note" value={note} onChangeText={setNote} placeholder="What was done, anything the client should know" /><PrimaryButton title={["dispute_rejected", "return_visit_scheduled"].includes(st) ? "Submit fix" : "Complete job"} disabled={photos.length < 2 || !note.trim()} onPress={() => act(["dispute_rejected", "return_visit_scheduled"].includes(st) ? "fix-done" : "complete", { photos, note })} loading={busy} /><Pressable onPress={() => setSheet("pause")}><RNText style={{ textAlign: "center", ...S(13, "600", c.err) }}>Pause for safety instead</RNText></Pressable></Sheet>
      <Sheet open={sheet === "pause"} onClose={() => setSheet(null)} title="Pause for safety"><RNText style={{ ...S(14, "400", c.text3), marginTop: -8 }}>No fee, no rating impact. The client and MrBuilder are notified immediately.</RNText><View style={{ gap: 6 }}>{["Unsafe weather / lightning", "Structural hazard found", "Unsafe footings", "Site access blocked", "Other"].map((r) => <Pressable key={r} onPress={() => setReason(r)} style={{ height: 44, borderRadius: 12, borderWidth: 1.5, borderColor: reason === r ? c.err : c.border2, backgroundColor: reason === r ? c.errBg : c.surface, paddingHorizontal: 14, justifyContent: "center" }}><RNText style={S(14, "500")}>{r}</RNText></Pressable>)}</View><Pressable disabled={!reason} onPress={() => act("pause", { reason })} style={{ height: 52, borderRadius: 12, backgroundColor: reason ? c.errBg : c.surface3, alignItems: "center", justifyContent: "center" }}><RNText style={S(16, "600", reason ? c.err : c.text4)}>Pause work</RNText></Pressable></Sheet>
      <Sheet open={sheet === "cancel"} onClose={() => setSheet(null)} title="Cancel the job?"><RNText style={{ ...S(14, "400", c.text3), marginTop: -8 }}>{["assigned", "en_route", "arrived"].includes(st) ? "A 1% fee applies before start." : "A 5% fee applies after start."} The job goes back to the marketplace and your reliability score is affected.</RNText><View style={{ gap: 6 }}>{[["schedule", "Schedule conflict"], ["too_far", "Too far / travel"], ["scope", "Scope isn't what was described"], ["personal", "Personal reasons"], ["other", "Other"]].map(([k, l]) => <Pressable key={k} onPress={() => setReason(k)} style={{ height: 44, borderRadius: 12, borderWidth: 1.5, borderColor: reason === k ? c.primary : c.border2, backgroundColor: reason === k ? c.primarySoft : c.surface, paddingHorizontal: 14, justifyContent: "center" }}><RNText style={S(14, "500")}>{l}</RNText></Pressable>)}</View><Pressable disabled={!reason} onPress={() => act("cancel", { reason }, "PATCH")} style={{ height: 52, borderRadius: 12, backgroundColor: reason ? c.errBg : c.surface3, alignItems: "center", justifyContent: "center" }}><RNText style={S(16, "600", reason ? c.err : c.text4)}>Cancel job</RNText></Pressable><SecondaryButton title="Keep the job" onPress={() => setSheet(null)} /></Sheet>
      <Sheet open={sheet === "reschedule"} onClose={() => setSheet(null)} title={pendingProp ? "Respond to reschedule" : "Propose a time"}>{pendingProp && <><View style={{ flexDirection: "row", gap: 8 }}><View style={{ flex: 1, padding: 12, borderRadius: 12, backgroundColor: c.surface2 }}><RNText style={S(12, "400", c.text4)}>Original · kept</RNText><RNText style={S(14, "700")}>{fmtD(j.scheduled_start, true)}</RNText></View><View style={{ flex: 1, padding: 12, borderRadius: 12, backgroundColor: c.primarySoft }}><RNText style={S(12, "400", c.orange)}>Client proposed</RNText><RNText style={S(14, "700")}>{fmtD(pendingProp.proposed_start, true)}</RNText></View></View><PrimaryButton title={`Accept ${fmtD(pendingProp.proposed_start, true)}`} onPress={() => act(`reschedule/${pendingProp.id}`, { action: "accept" }, "PATCH")} loading={busy} /><SecondaryButton title="Keep original" onPress={() => act(`reschedule/${pendingProp.id}`, { action: "decline" }, "PATCH")} /><RNText style={{ textAlign: "center", ...S(12.5, "400", c.text4) }}>or suggest another:</RNText></>}<Field label="Proposed start (YYYY-MM-DD HH:MM)" value={when} onChangeText={setWhen} placeholder="2026-05-14 14:00" /><Field label="Message (optional)" value={note} onChangeText={setNote} /><SecondaryButton title="Send proposal" onPress={() => act("reschedule", { kind: st === "dispute_rejected" ? "return" : "start", proposed_start: new Date(when.replace(" ", "T")).toISOString(), message: note || undefined })} /></Sheet>
    </SafeAreaView>
  );
}
