import React, { useState } from "react";
import { Alert, Pressable, ScrollView, Text as RNText, View } from "react-native";
import { useNavigation } from "@react-navigation/native";
import { NativeStackNavigationProp } from "@react-navigation/native-stack";
import { Ionicons } from "@expo/vector-icons";
import * as ImagePicker from "expo-image-picker";
import { Field, PrimaryButton, SecondaryButton, validEmail, validPassword } from "../../components/form";
import { PickerSheet, SelectField } from "../../components/sheet";
import { STATES } from "../../state/requestDraft";
import { AuthFrame } from "./ProLoginScreen";
import { api, uploadFile } from "../../api/client";
import { useSession } from "../../auth/session";
import { useTheme } from "../../theme/ThemeProvider";
import { font } from "../../theme/tokens";
import { RootParams } from "../../navigation";
import { useContent } from "../../state/content";

const T = ["Account information", "Address information", "Choose your role", "Business information", "Insurance & skills", "Final steps"];
const SUB = ["Create your account credentials.", "We need your address for job assignments.", "Select the role that best matches your skills and experience.", "Connect with high-value projects in outdoor living spaces.", "Verify your insurance and tell us about your skills.", "Review and accept the agreements to complete your application."];
const ROLES = [["inspector", "Inspector", "Conduct on-site diagnostics, recommend parts, and upsell services.", "$70 per inspection"], ["service_team", "Service Team", "Perform repair services in teams of 1–2.", "75–80% of labor cost"], ["installation_team", "Installation Team", "Handle new pergola installations (team of 2–4).", "75–80% of project fee"]];
const SERVICES0: [string, string][] = [["repair", "Repair"], ["programming", "Programming & Smart Controls"], ["upgrades", "Upgrades & Accessories"], ["inspection", "Inspection & Diagnostics"], ["maintenance", "Maintenance"], ["cleaning", "Cleaning"], ["removal", "Removal & Relocation"]];
const YEARS = ["Less than 1 year", "1–2 years", "3–5 years", "6–10 years", "10+ years"];

export default function ProSignupScreen() {
  const nav = useNavigation<NativeStackNavigationProp<RootParams>>();
  const { register } = useSession();
  const { c } = useTheme();
  const content = useContent(); const SYSTEMS = content.pergola_systems; const SERVICES = content.categories.length ? content.categories.filter((k) => k.slug !== "installation").map((k) => [k.slug, k.name] as [string, string]) : SERVICES0;
  const [n, setN] = useState(1); const [busy, setBusy] = useState(false); const [done, setDone] = useState(false); const [pick, setPick] = useState<null | "state" | "years">(null);
  const [f, setF] = useState({ first: "", last: "", email: "", phone: "", pw: "", pw2: "", street: "", apt: "", city: "", state: "", zip: "", role: "installation_team", biz: "llc", ssn: "", coi: "", insProgram: false, years: "", systems: [] as string[], services: [] as string[], certs: [] as string[], agreeTerms: false, agreeIC: false, agreeBg: false });
  const S = (n: number, w: "400" | "500" | "600" | "700" = "400", col = c.text) => ({ fontSize: n, fontFamily: w === "400" ? font.regular : w === "500" ? font.medium : w === "600" ? font.semibold : font.bold, color: col });
  const toggle = (k: "systems" | "services" | "certs", v: string) => setF({ ...f, [k]: f[k].includes(v) ? f[k].filter((x) => x !== v) : [...f[k], v] });
  const ok = [validEmail(f.email) && f.first && f.last && validPassword(f.pw) && f.pw === f.pw2, f.street && f.city && f.state && /^\d{5}/.test(f.zip), !!f.role, !!f.biz && f.ssn.replace(/\D/g, "").length >= 4, f.years && f.services.length > 0, f.agreeTerms && f.agreeIC && f.agreeBg][n - 1];
  async function upload(k: "coi" | "certs") { const res = await ImagePicker.launchImageLibraryAsync({ quality: 0.8 }); if (res.canceled || !res.assets[0]) return; const u = (await uploadFile(res.assets[0].uri, "documents")) ?? res.assets[0].uri; if (k === "coi") setF({ ...f, coi: u }); else setF({ ...f, certs: [...f.certs, u] }); }
  async function submit() {
    setBusy(true);
    const e = await register({ first_name: f.first.trim(), last_name: f.last.trim(), email: f.email.trim(), phone: f.phone.trim() || undefined, password: f.pw, role: "contractor" });
    if (e) { setBusy(false); Alert.alert("Couldn't create account", e); setN(1); return; }
    await api("/profile", { method: "PUT", body: { contractor_role: f.role, business_type: f.biz, tax_id_last4: f.ssn.replace(/\D/g, "").slice(-4), years_experience: f.years, coi_url: f.coi || undefined, insurance_program_interest: f.insProgram, certifications: f.certs, address: { line1: f.street, line2: f.apt || undefined, city: f.city, state: f.state, zip_code: f.zip } } });
    await api("/profile/skills", { method: "PUT", body: { skills: f.services } });
    await api("/profile/pergola-systems", { method: "PUT", body: { systems: f.systems } });
    await api("/addresses", { method: "POST", body: { label: "Business", line1: f.street, line2: f.apt || undefined, city: f.city, state: f.state, zip_code: f.zip, is_default: true } });
    setBusy(false); setDone(true);
  }
  const Radio = ({ on }: { on: boolean }) => <View style={{ width: 22, height: 22, borderRadius: 11, borderWidth: on ? 6 : 1.5, borderColor: on ? c.primary : c.border2, backgroundColor: c.surface }} />;
  const Check = ({ on, label, onPress, bold }: { on: boolean; label: string; onPress: () => void; bold?: boolean }) => <Pressable onPress={onPress} style={{ flexDirection: "row", alignItems: "center", gap: 10, padding: 10, paddingHorizontal: 12, borderRadius: 10, backgroundColor: on ? c.primarySoft : c.surface, borderWidth: 1, borderColor: on ? c.orangeBd : c.border }}><View style={{ width: 20, height: 20, borderRadius: 6, backgroundColor: on ? c.primary : "transparent", borderWidth: on ? 0 : 1.5, borderColor: c.border2, alignItems: "center", justifyContent: "center" }}>{on && <Ionicons name="checkmark" size={14} color="#fff" />}</View><RNText style={{ flex: 1, ...S(14, bold ? "600" : "400") }}>{label}</RNText></Pressable>;
  const Upload = ({ label, done: d, onPress, hint }: { label: string; done?: string; onPress: () => void; hint?: string }) => <Pressable onPress={onPress} style={{ borderRadius: 12, borderWidth: 1, borderStyle: "dashed", borderColor: d ? c.ok : c.border2, backgroundColor: d ? c.okBg : c.surface, padding: 16, alignItems: "center", gap: 6 }}><View style={{ width: 40, height: 40, borderRadius: 10, backgroundColor: c.surface2, alignItems: "center", justifyContent: "center" }}><Ionicons name={d ? "checkmark-circle-outline" : "cloud-upload-outline"} size={20} color={d ? c.ok : c.text2} /></View><RNText style={S(14, "400", c.text3)}>{d ? "Uploaded" : <><RNText style={S(14, "600", c.orange)}>Click to upload</RNText> {label}</>}</RNText><RNText style={S(12, "400", c.text4)}>{hint ?? "PDF, JPG or PNG · max 10 MB"}</RNText></Pressable>;
  const Info = ({ title, text }: { title: string; text: string }) => <View style={{ flexDirection: "row", gap: 10, padding: 12, borderRadius: 12, backgroundColor: c.infoBg }}><Ionicons name="bulb-outline" size={18} color={c.info} /><View style={{ flex: 1 }}><RNText style={S(14, "600", c.info)}>{title}</RNText><RNText style={S(13, "400", c.text2)}>{text}</RNText></View></View>;
  const Foot = () => <RNText style={{ textAlign: "center", ...S(12, "400", c.text4) }}>Need help? Contact our Contractor Support Team{"\n"}<RNText style={S(12, "600", c.orange)}>support@mrbuilder.com</RNText> · MrBuilder © 2026</RNText>;

  if (done) return (
    <AuthFrame>
      <View style={{ flex: 1, padding: 20, paddingTop: 24, gap: 24 }}>
        <View style={{ width: 72, height: 72, borderRadius: 36, backgroundColor: c.okBg, alignItems: "center", justifyContent: "center" }}><View style={{ width: 50, height: 50, borderRadius: 25, backgroundColor: "#079455", alignItems: "center", justifyContent: "center" }}><Ionicons name="checkmark" size={28} color="#fff" /></View></View>
        <View style={{ gap: 8 }}><RNText style={S(26, "700")}>Application submitted!</RNText><RNText style={S(15, "400", c.text3)}>Thank you for applying to join MrBuilder. Our team will review your application and get back to you within 3–5 business days.</RNText><RNText style={S(14, "400", c.text4)}>You've been automatically added to the waitlist in your area. We'll notify you when jobs become available.</RNText></View>
        <Info title="Next steps" text="Training starts right away — Core and Safety modules are open in the app. Complete your Stripe payout setup when you receive the link." />
        <View style={{ flex: 1 }} /><PrimaryButton title="Start training" onPress={() => nav.navigate("Tabs", { screen: "Training" })} /><Foot />
      </View>
    </AuthFrame>
  );
  return (
    <AuthFrame onBack={() => (n > 1 ? setN(n - 1) : nav.goBack())}>
      <ScrollView contentContainerStyle={{ padding: 20, paddingTop: 16, gap: 20 }} keyboardShouldPersistTaps="handled">
        <View style={{ gap: 12 }}><View style={{ flexDirection: "row", justifyContent: "space-between" }}><RNText style={S(12.5, "600", c.orange)}>Step {n} of 6</RNText><RNText style={S(12.5, "400", c.text4)}>{n < 6 ? `Next: ${T[n]}` : "Last step"}</RNText></View><View style={{ flexDirection: "row", gap: 6 }}>{[1, 2, 3, 4, 5, 6].map((i) => <View key={i} style={{ flex: 1, height: 5, borderRadius: 3, backgroundColor: i < n ? "#079455" : i === n ? c.primary : c.border }} />)}</View><View style={{ gap: 4 }}><RNText style={S(24, "700")}>{T[n - 1]}</RNText><RNText style={S(14.5, "400", c.text3)}>{SUB[n - 1]}</RNText></View></View>
        {n === 1 && <View style={{ gap: 14 }}><View style={{ flexDirection: "row", gap: 10 }}><View style={{ flex: 1 }}><Field label="First name" value={f.first} onChangeText={(v) => setF({ ...f, first: v })} autoCapitalize="words" placeholder="John" /></View><View style={{ flex: 1 }}><Field label="Last name" value={f.last} onChangeText={(v) => setF({ ...f, last: v })} autoCapitalize="words" placeholder="Peterson" /></View></View><Field label="Email address" value={f.email} onChangeText={(v) => setF({ ...f, email: v })} keyboardType="email-address" placeholder="you@example.com" /><Field label="Phone number" value={f.phone} onChangeText={(v) => setF({ ...f, phone: v })} keyboardType="phone-pad" placeholder="+1 (555) 000-0000" /><Field label="Create password" value={f.pw} onChangeText={(v) => setF({ ...f, pw: v })} secure placeholder="Minimum 8 characters, one number" ok={validPassword(f.pw) ? "Strong enough" : null} /><Field label="Confirm password" value={f.pw2} onChangeText={(v) => setF({ ...f, pw2: v })} secure placeholder="Re-enter password" error={f.pw2 && f.pw2 !== f.pw ? "Passwords don't match" : null} /></View>}
        {n === 2 && <View style={{ gap: 14 }}><Field label="Street address" value={f.street} onChangeText={(v) => setF({ ...f, street: v })} placeholder="123 Main St" /><Field label="Apt, Suite, etc. (Optional)" value={f.apt} onChangeText={(v) => setF({ ...f, apt: v })} placeholder="Apt 4B" /><View style={{ flexDirection: "row", gap: 10 }}><View style={{ flex: 1.4 }}><Field label="City" value={f.city} onChangeText={(v) => setF({ ...f, city: v })} placeholder="Portland" /></View><View style={{ flex: 1 }}><SelectField label="State" value={f.state} placeholder="Select" onPress={() => setPick("state")} /></View></View><View style={{ flexDirection: "row", gap: 10 }}><View style={{ flex: 1 }}><Field label="ZIP code" value={f.zip} onChangeText={(v) => setF({ ...f, zip: v })} keyboardType="numeric" placeholder="97201" /></View><View style={{ flex: 1.4 }}><SelectField label="Country" value="United States" placeholder="" onPress={() => {}} /></View></View></View>}
        {n === 3 && <View style={{ gap: 12 }}>{ROLES.map(([k, name, desc, pay]) => { const on = f.role === k; return <Pressable key={k} onPress={() => setF({ ...f, role: k })} style={{ backgroundColor: c.surface, borderWidth: on ? 1.5 : 1, borderColor: on ? c.primary : c.border, borderRadius: 16, padding: 14, gap: 8 }}><View style={{ flexDirection: "row", alignItems: "center", gap: 10 }}><Radio on={on} /><RNText style={{ flex: 1, ...S(16, "600") }}>{name}</RNText><Ionicons name="information-circle-outline" size={18} color={c.text4} /></View><RNText style={S(13.5, "400", c.text3)}>{desc}</RNText><View style={{ flexDirection: "row", gap: 6 }}><View style={{ paddingHorizontal: 8, paddingVertical: 3, borderRadius: 999, backgroundColor: c.primarySoft }}><RNText style={S(12, "600", c.orange)}>{pay}</RNText></View><View style={{ paddingHorizontal: 8, paddingVertical: 3, borderRadius: 999, backgroundColor: c.okBg }}><RNText style={S(12, "600", c.ok)}>+3–5% commission</RNText></View></View></Pressable>; })}</View>}
        {n === 4 && <View style={{ gap: 16 }}><View style={{ gap: 8 }}><RNText style={S(13.5, "500", c.text2)}>Business type</RNText>{[["sole", "Sole Proprietor", ""], ["llc", "LLC", "Recommended"], ["corp", "Corporation", ""]].map(([k, l, tag]) => { const on = f.biz === k; return <Pressable key={k} onPress={() => setF({ ...f, biz: k })} style={{ flexDirection: "row", alignItems: "center", gap: 12, height: 52, paddingHorizontal: 14, borderRadius: 12, backgroundColor: on ? c.primarySoft : c.surface, borderWidth: on ? 1.5 : 1, borderColor: on ? c.primary : c.border }}><Radio on={on} /><RNText style={{ flex: 1, ...S(14.5, on ? "600" : "500") }}>{l}</RNText>{!!tag && <RNText style={S(12, "600", c.orange)}>{tag}</RNText>}</Pressable>; })}</View><Field label="SSN or ITIN" value={f.ssn} onChangeText={(v) => setF({ ...f, ssn: v })} secure keyboardType="numeric" placeholder="•••-••-••••" hint="Required for tax reporting (1099). Encrypted; only the last 4 digits are stored." /><Info title="LLC recommendation" text="Creating an LLC offers legal protection, tax benefits, and increased trust on the platform." /></View>}
        {n === 5 && <View style={{ gap: 18 }}><View style={{ gap: 8 }}><RNText style={S(13.5, "500", c.text2)}>Certificate of Insurance (COI)</RNText><Upload label="your COI" done={f.coi} onPress={() => upload("coi")} /><Check on={f.insProgram} label="I'm interested in the MrBuilder Insurance Program" onPress={() => setF({ ...f, insProgram: !f.insProgram })} /></View>
          <View style={{ gap: 12 }}><RNText style={S(15, "600")}>Skills & experience</RNText><SelectField label="Years of experience" value={f.years} placeholder="Select" onPress={() => setPick("years")} /><View style={{ gap: 6 }}><RNText style={S(13.5, "500", c.text2)}>Pergola systems installed</RNText><View style={{ flexDirection: "row", flexWrap: "wrap", gap: 8 }}>{SYSTEMS.map((s) => <View key={s} style={{ width: "48%" }}><Check on={f.systems.includes(s)} label={s} onPress={() => toggle("systems", s)} /></View>)}</View></View><View style={{ gap: 6 }}><RNText style={S(13.5, "500", c.text2)}>Services you offer</RNText><View style={{ gap: 8 }}>{SERVICES.map(([k, l]) => <Check key={k} on={f.services.includes(k)} label={l} onPress={() => toggle("services", k)} />)}</View></View><View style={{ gap: 6 }}><RNText style={S(13.5, "500", c.text2)}>Certifications <RNText style={S(13.5, "400", c.text5)}>(Optional)</RNText></RNText><Upload label="certifications" done={f.certs[0]} onPress={() => upload("certs")} hint={f.certs.length ? `${f.certs.length} file${f.certs.length > 1 ? "s" : ""} added · tap to add more` : "PDF, JPG or PNG"} /></View></View></View>}
        {n === 6 && <View style={{ gap: 12 }}><View style={{ backgroundColor: c.surface, borderWidth: 1, borderColor: c.border, borderRadius: 16, padding: 14, gap: 8 }}><RNText style={S(15, "600")}>How MrBuilder works for PROs</RNText>{["Prices are set by MrBuilder; you see your net before accepting.", "Before-work photos and the safety checklist are required before every start.", "Payment is released when the client confirms; disputes are reviewed by MrBuilder.", "1% fee if you cancel an accepted job before starting, 5% after."].map((t) => <View key={t} style={{ flexDirection: "row", gap: 8 }}><Ionicons name="checkmark-circle" size={16} color={c.ok} style={{ marginTop: 2 }} /><RNText style={{ flex: 1, ...S(13.5, "400", c.text2) }}>{t}</RNText></View>)}</View><Check bold on={f.agreeTerms} label="I agree to the Terms of Service and Privacy Policy" onPress={() => setF({ ...f, agreeTerms: !f.agreeTerms })} /><Check bold on={f.agreeIC} label="I accept the Independent Contractor Agreement" onPress={() => setF({ ...f, agreeIC: !f.agreeIC })} /><Check bold on={f.agreeBg} label="I consent to a background and license check" onPress={() => setF({ ...f, agreeBg: !f.agreeBg })} /><Info title="Certification recommendation" text="Complete the Core and Safety training in the app right after applying — it's required before your first job." /></View>}
        <View style={{ flexDirection: "row", gap: 10, paddingTop: 8 }}>{n > 1 && <SecondaryButton title="Back" height={52} style={{ flex: 1 }} onPress={() => setN(n - 1)} />}<PrimaryButton title={n === 6 ? "Submit application" : "Continue"} style={{ flex: 2 }} disabled={!ok} loading={busy} onPress={() => (n === 6 ? submit() : setN(n + 1))} /></View>
        <Foot />
      </ScrollView>
      <PickerSheet open={pick === "state"} onClose={() => setPick(null)} title="State" options={STATES} value={f.state} onSelect={(v) => setF({ ...f, state: v })} searchable />
      <PickerSheet open={pick === "years"} onClose={() => setPick(null)} title="Years of experience" options={YEARS} value={f.years} onSelect={(v) => setF({ ...f, years: v })} />
    </AuthFrame>
  );
}
