import Link from "next/link";
import SiteHeader from "@/components/site/SiteHeader";
import SiteFooter from "@/components/site/SiteFooter";
import { Phone } from "@/components/site/Phone";
import { QuickForm } from "@/components/site/QuickForm";
import { Btn, Check, Chip, Container, Eyebrow, H2, Lead, S, Section } from "@/components/site/ui";
import { getContent } from "@/lib/content";

export const metadata = { title: "Partner With Us — MrBuilder", description: "Your products deserve installation and service that match." };

const WHO = [["Manufacturers & Sellers", "Connect your customers with installation and after-sales support, so your team can focus on products and sales.", ["Manufacturer", "Wholesaler / Distributor", "Retail Showroom", "Online Retailer / E-commerce Store", "Motor & Automation Supplier / Dealer"]], ["Design & Construction", "Coordinate installation and technical support for outdoor systems within your projects.", ["Outdoor Living / Patio Company", "Landscape Design / Landscaping Company", "Pool & Spa Company", "Architecture / Engineering Firm", "General Contractor", "Builder", "Real Estate Developer"]], ["Property & Community Management", "Request and track repairs, maintenance, and service for the outdoor systems across your properties.", ["Residential Property Management", "Commercial Property Management", "Facilities Management Company", "Homeowners Association (HOA)"]], ["Hospitality & Leisure", "Keep outdoor guest areas ready to use with installation, repairs, and ongoing maintenance.", ["Hotel / Resort", "Restaurant / Café / Bar", "Country Club / Golf Club"]]] as const;
const ACCOUNT = [["01", "One account per company", "Each participating company receives a partner account. Add team members so sales and operations can both submit and follow requests."], ["02", "Submit installation requests", "For every pergola you sell: customer, address, product, dimensions, mounting and preferred dates: the same fields the consumer app collects, so contractors see one consistent job card."], ["03", "Request repairs and service", "When a customer calls about a motor, a panel or a leak, open a repair or service request instead of dispatching your own crew."], ["04", "Track everything in one place", "Every request shows its live status (submitted, quoted, contractor assigned, in progress, awaiting confirmation, completed) in a single list."]];
const ROWS: [string, string, string, string, string, "in" | "wn" | "ok" | "or" | "gray"][] = [["Louvered pergola installation · 12 × 10 ft", "MRB-2026-11204", "R. Alvarez · Round Rock, TX", "Sep 22 – 24", "Contractor assigned", "in"], ["Motor repair · attached pergola", "MRB-2026-11198", "K. Nguyen · Austin, TX", "Sep 18", "In progress", "wn"], ["Fixed-roof pergola installation · 16 × 12 ft", "MRB-2026-11187", "D. Osei · Cedar Park, TX", "Sep 15 – 17", "Awaiting customer confirmation", "wn"], ["Screen enclosure add-on", "MRB-2026-11160", "M. Brooks · Austin, TX", "Sep 9", "Completed · paid", "ok"], ["Retractable pergola installation · 14 × 10 ft", "MRB-2026-11221", "New, pending quote", "TBD", "Submitted", "or"]];
const FLOW = [["1", "Your company", "Sell a product", "Close the sale as you do today. Nothing about your product, pricing or brand changes.", false], ["2", "Your company", "Submit a request", "Log the installation in your partner account with the customer's details, the product and preferred dates.", false], ["3", "MrBuilder", "We coordinate the work", "MrBuilder prices the job, matches a vetted contractor, schedules the visit and handles on-site progress, proof photos and payment.", true], ["4", "Your company · your customer", "Track through completion", "You follow status in the partner account; your customer follows the same job in the consumer app and confirms the finished work.", false]] as const;
const CATEGORIES = [
  { tag: "Pergola manufacturers & sellers", title: "Sell more pergolas. Let one partner install and service them.", body: "Every unit you sell needs an installer, and every installed unit eventually needs service. MrBuilder can be the installation and after-sales layer behind your product line, from a dealer network or direct to consumer.", points: ["Installation and repair requests for products you sell, through a company partner account", "Structured job cards that carry your product's type, mounting and dimensions to the contractor", "MrCare maintenance and electronics protection offered to your customers after installation"] },
  { tag: "Motor manufacturers & suppliers", title: "Programming, diagnostics and replacement handled by trained contractors.", body: "Louver motors, smart controls, sensors and remotes are where most after-sales calls come from. MrBuilder's service types already include Programming & Smart Controls and Inspection & Diagnostics, and the Electronics Protection Plan covers exactly this equipment.", points: ["Contractors matched by skill to motor programming, diagnostics and replacement jobs", "Electronics issues logged as trackable claims with photos, device and problem type", "A route for warranty-covered repairs to be dispatched and documented through the platform"] },
  { tag: "Outdoor accessory suppliers", title: "Turn add-ons into installed upgrades.", body: "Screens, enclosures, lighting, heaters and shades sell better when installation is one tap away. The consumer app already captures enclosures and accessories per pergola, and Upgrades & Accessories is a service type contractors can filter for.", points: ["Accessory installation offered as an upgrade request on an existing pergola", "Per-pergola records of what's installed, so service requests reference the right equipment", "Contractors can source parts for a job through the platform's parts-request flow"] },
  { tag: "Door & window manufacturers & sellers", title: "Extend the same coordination to doors and windows.", body: "Outdoor living rarely stops at the pergola. Patio doors, bi-folds and windows share the same problem: a sale, then an installation, then years of adjustments and repairs. MrBuilder's request, quote, match and track workflow is built to extend to these products as we grow.", points: ["Installation and service coordination modeled on the pergola workflow", "A single customer app for everything installed around the home's outdoor space", "Early-partner input on how door and window jobs should be specified and priced"] },
];
const CHECKLIST = ["A partner account with team access", "Installation, repair and service request forms", "Live status on every request you submit", "Your customers onboarded to the MrBuilder consumer app, with MrCare available after installation"];

export default async function PartnerPage() {
  const content = await getContent();
  return (
    <>
      <div className="bg-[#181D27] text-white"><SiteHeader dark /><Container className="pb-16 pt-10 lg:pb-24 lg:pt-16"><Eyebrow color="text-[#F7A26B]">Partner with us</Eyebrow><h1 className="max-w-3xl text-[40px] font-bold leading-[1.05] tracking-tight md:text-[56px]">Your products deserve installation and service that match.</h1><p className="mt-6 max-w-2xl text-[17px] leading-7 text-[#D5D7DA]">MrBuilder works with manufacturers and suppliers across outdoor living (pergolas, motors, accessories, doors and windows) to make installation, service and repair part of the product experience, not an afterthought.</p><div className="mt-8 flex flex-wrap items-center gap-4"><Btn href="#inquiry">Submit Partnership Inquiry</Btn><Link href="#companies" className="font-semibold text-white/85">Pergola company? Start here →</Link></div></Container></div>

      <Section id="companies" className="scroll-mt-20"><Container className="grid gap-10 lg:grid-cols-2"><div><Eyebrow color="text-[#175CD3]">For pergola companies</Eyebrow><H2>Focus on selling. Let MrBuilder handle installation and after-sales service.</H2></div><div className="space-y-4 text-[17px] leading-7 text-gray-600"><p>Installation crews, service calls and warranty follow-ups pull your team away from selling. With MrBuilder, you submit the request and we do the rest: pricing, matching a vetted contractor, scheduling, on-site progress, completion proof and payment.</p><p>Your customer gets the MrBuilder consumer app (the same one homeowners use) and you get a partner account to track every request you've sent, from submitted to confirmed.</p></div></Container></Section>

      <Section className="bg-[#FAFAFA]"><Container><Eyebrow>Who we help</Eyebrow><H2>Built for every business behind an outdoor space.</H2><Lead>Installation, repairs, and ongoing care for the outdoor products you sell, specify, build with, or manage.</Lead><div className="mt-10 grid gap-5 md:grid-cols-2">{WHO.map(([t, b, tags]) => <div key={t} className="rounded-[20px] border border-gray-200 bg-white p-6"><div className="text-[20px] font-bold text-[#181D27]">{t}</div><p className="mt-2 text-[15px] leading-6 text-gray-600">{b}</p><div className="mt-4 flex flex-wrap gap-2">{tags.map((x) => <span key={x} className="rounded-full bg-gray-100 px-3 py-1 text-[13px] font-medium text-gray-700">{x}</span>)}</div></div>)}</div><div className="mt-8 flex flex-wrap items-center gap-4"><Btn href="#inquiry">Partner with MrBuilder →</Btn><span className="text-[14px] text-gray-500">Don't see your business type? Tell us in the inquiry form.</span></div></Container></Section>

      <Section><Container><Eyebrow color="text-[#175CD3]">The partner account</Eyebrow><H2>One account for every product you've sold.</H2><div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-4">{ACCOUNT.map(([n, t, b]) => <div key={n} className="rounded-[20px] border border-gray-200 bg-white p-6"><div className="text-[13px] font-bold text-[#175CD3]">{n}</div><div className="mt-2 text-[19px] font-bold text-[#181D27]">{t}</div><p className="mt-2 text-[15px] leading-6 text-gray-600">{b}</p></div>)}</div>
        <div className="mt-10 overflow-hidden rounded-[24px] border border-gray-200 bg-white shadow-[0_30px_60px_-30px_rgba(24,29,39,.35)]"><div className="flex flex-wrap items-center justify-between gap-2 border-b border-gray-200 bg-[#FAFAFA] px-5 py-3"><div className="flex items-center gap-2 text-[13px] text-gray-500"><span className="rounded-full border border-[#FEDF89] bg-[#FFFAEB] px-2 py-0.5 text-[11px] font-bold uppercase text-[#B54708]">Concept preview</span>Planned company portal, not yet built. Layout follows the MrBuilder apps; contents are illustrative.</div><span className="text-[12px] text-gray-400">partners.mrbuilder: Company portal (concept)</span></div>
          <div className="grid md:grid-cols-[220px_1fr]"><aside className="hidden border-r border-gray-200 bg-[#FAFAFA] p-4 md:block"><div className="mb-4 flex items-center gap-2"><img src="/site/brand/mrb-mark.png" alt="" className="h-8 w-8" /><div><div className="text-[13px] font-bold">Partner account</div><div className="text-[11px] text-gray-500">Sunline Pergolas · Austin, TX</div></div></div>{["Requests", "Customers", "Products sold", "MrCare", "Team & settings"].map((x, i) => <div key={x} className={`rounded-lg px-3 py-2 text-[14px] ${i === 0 ? "bg-white font-semibold shadow-sm" : "text-gray-600"}`}>{x}</div>)}<div className="mt-6 text-[11px] text-gray-400">3 team members</div></aside>
            <div className="p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><div className="text-[18px] font-bold text-[#181D27]">Requests</div><div className="text-[13px] text-gray-500">Installation, repair and service requests you've submitted</div></div><div className="flex gap-2"><span className="rounded-full border border-gray-300 px-3 py-1.5 text-[13px] font-semibold">Request a repair</span><span className="rounded-full bg-[#EF6820] px-3 py-1.5 text-[13px] font-semibold text-white">+ New installation request</span></div></div><div className="mt-4 flex gap-2">{["All", "Installation", "Repair", "Service"].map((x, i) => <span key={x} className={`rounded-full px-3 py-1 text-[12px] font-semibold ${i === 0 ? "bg-[#181D27] text-white" : "bg-gray-100 text-gray-600"}`}>{x}</span>)}</div>
              <div className="mt-4 overflow-x-auto"><table className="w-full text-[13px]"><thead className="text-left text-[11px] uppercase text-gray-400"><tr><th className="py-2 pr-3">Request</th><th className="py-2 pr-3">Customer</th><th className="py-2 pr-3">Dates</th><th className="py-2">Status</th></tr></thead><tbody>{ROWS.map(([t, id, cu, d, st, tone]) => <tr key={id} className="border-t border-gray-100"><td className="py-2.5 pr-3"><div className="font-semibold text-[#181D27]">{t}</div><div className="text-[11px] text-gray-400">{id}</div></td><td className="py-2.5 pr-3 text-gray-600">{cu}</td><td className="py-2.5 pr-3 text-gray-600">{d}</td><td className="py-2.5"><Chip tone={tone}>{st}</Chip></td></tr>)}</tbody></table></div></div></div></div></Container></Section>

      <Section className="bg-[#FAFAFA]"><Container><Eyebrow>Workflow</Eyebrow><H2>Sell → submit → we coordinate → you track.</H2><div className="mt-10 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{FLOW.map(([n, actor, t, b, dark]) => <div key={n} className={`rounded-[20px] p-6 ${dark ? "bg-[#181D27] text-white" : "border border-gray-200 bg-white"}`}><div className="flex items-center gap-2"><span className={`grid h-8 w-8 place-items-center rounded-full text-sm font-bold text-white ${dark ? "bg-[#EF6820]" : "bg-[#175CD3]"}`}>{n}</span><span className={`text-[12px] font-bold uppercase tracking-wide ${dark ? "text-[#F7A26B]" : "text-[#175CD3]"}`}>{actor}</span></div><div className="mt-4 text-[19px] font-bold">{t}</div><p className={`mt-2 text-[15px] leading-6 ${dark ? "text-[#D5D7DA]" : "text-gray-600"}`}>{b}</p></div>)}</div>
        <div className="mt-14 grid items-center gap-10 lg:grid-cols-2"><div><Eyebrow>What your customer sees</Eyebrow><h3 className="text-[28px] font-bold leading-tight text-[#181D27]">The same MrBuilder app homeowners use.</h3><p className="mt-3 text-[16px] leading-7 text-gray-600">Your customer is invited into the consumer app, where the installation appears as a request they can follow: contractor assigned, on the way, in progress, awaiting confirmation. They confirm the finished work and rate the installer, and their pergola is registered under My pergolas for future service.</p></div><div className="flex justify-center gap-4"><Phone src={S("c-in-progress")} alt="Consumer app: request in progress" className="w-1/2" /><Phone src={S("c-add-empty")} alt="Consumer app: My pergolas" className="mt-8 w-1/2" /></div></div></Container></Section>

      <Section><Container className="grid items-center gap-10 lg:grid-cols-2"><div className="flex justify-center gap-4 lg:order-1"><Phone src={S("c-mrcare")} alt="Consumer app: MrCare hub" className="w-1/2" /><Phone src={S("c-protection")} alt="Consumer app: Electronics Protection Plan" className="mt-8 w-1/2" /></div><div className="lg:order-2"><Eyebrow>After-sales · MrCare</Eyebrow><H2>MrBuilder offers its own protection to your customers.</H2><Lead>Alongside your manufacturer warranty, customers can buy MrCare in the app: a Service & Maintenance Subscription for scheduled visits, and an Electronics Protection Plan for motors, sensors, remotes and controllers. Claims and bookings become trackable requests handled by MrBuilder, not calls to your sales desk.</Lead><p className="mt-4 text-[13px] text-gray-500">Coverage, terms and pricing are presented in the app and are being finalized.</p></div></Container></Section>

      <Section className="bg-[#FAFAFA]"><Container><Eyebrow>Who we work with</Eyebrow><H2>Four partner categories. One service layer.</H2><div className="mt-10 grid gap-6 md:grid-cols-2">{CATEGORIES.map((c) => <div key={c.tag} className="rounded-[24px] border border-gray-200 bg-white p-7"><Chip tone="in">{c.tag}</Chip><h3 className="mt-4 text-[22px] font-bold leading-snug text-[#181D27]">{c.title}</h3><p className="mt-3 text-[15px] leading-6 text-gray-600">{c.body}</p><div className="mt-5 text-[12px] font-bold uppercase tracking-wide text-gray-500">How we could work together</div><ul className="mt-2 space-y-2">{c.points.map((p) => <li key={p} className="flex gap-2 text-[14px] text-gray-700"><Check />{p}</li>)}</ul></div>)}</div></Container></Section>

      <Section id="inquiry" className="scroll-mt-20 bg-[#181D27] text-white"><Container className="grid gap-10 lg:grid-cols-[1fr_520px]"><div><Eyebrow color="text-[#F7A26B]">Company partnership</Eyebrow><h2 className="text-[34px] font-bold leading-tight">Become a Company Partner.</h2><p className="mt-4 text-[16px] leading-7 text-[#D5D7DA]">Tell us about your company and where you sell. We'll set up your partner account and walk your team through submitting the first installation request.</p><ul className="mt-6 space-y-3">{CHECKLIST.map((c) => <li key={c} className="flex gap-3 text-[15px] text-white/90"><Check />{c}</li>)}</ul><div className="mt-8 text-[13px] text-white/50">Starting in the United States. We aim to expand globally over time.</div></div><div className="text-[#181D27]"><QuickForm kind="partner" appLinks={content.app_links} /></div></Container></Section>
      <SiteFooter />
    </>
  );
}
