import React, { useCallback, useState } from "react";
import { Alert, Image, Pressable, ScrollView, Text as RNText, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { useFocusEffect, useNavigation, useRoute } from "@react-navigation/native";
import { NativeStackNavigationProp } from "@react-navigation/native-stack";
import { Ionicons } from "@expo/vector-icons";
import { Header } from "../../components/sheet";
import { api, Job } from "../../api/client";
import { useTheme } from "../../theme/ThemeProvider";
import { font } from "../../theme/tokens";
import { RootParams } from "../../navigation";
import type { Pergola } from "./PergolasScreen";
import type { Sub } from "./MrCareScreen";

export default function PergolaDetailScreen() {
  const nav = useNavigation<NativeStackNavigationProp<RootParams>>();
  const { params } = useRoute<{ key: string; name: string; params: { id: string } }>();
  const { c } = useTheme();
  const [p, setP] = useState<Pergola | null>(null); const [subs, setSubs] = useState<Sub[]>([]); const [jobs, setJobs] = useState<Job[]>([]); const [docs, setDocs] = useState(0); const [reminders, setReminders] = useState<{ due_at: string; kind: string }[]>([]);
  const load = useCallback(async () => { const [g, h, j, d, r] = await Promise.all([api<Pergola[]>("/pergolas"), api<{ subscriptions: Sub[] }>("/mrcare"), api<Job[]>("/jobs/me?limit=100"), api<unknown[]>(`/documents?pergola_id=${params.id}`), api<{ due_at: string; kind: string; pergola_id: string }[]>("/reminders")]); setP((g.data ?? []).find((x) => x.id === params.id) ?? null); setSubs((h.data?.subscriptions ?? []).filter((s) => s.status === "active" && s.pergola_ids.includes(params.id))); setJobs((j.data ?? []).filter((x) => (x as Job & { pergola_id?: string }).pergola_id === params.id || x.title?.includes(((g.data ?? []).find((x) => x.id === params.id)?.name) ?? "\u0000"))); setDocs(d.data?.length ?? 0); setReminders((r.data ?? []).filter((x) => x.pergola_id === params.id)); }, [params.id]);
  useFocusEffect(useCallback(() => { load(); }, [load]));
  const S = (n: number, w: "400" | "600" | "700" | "800" = "400", col = c.text) => ({ fontSize: n, fontFamily: w === "400" ? font.regular : w === "600" ? font.semibold : font.bold, color: col });
  if (!p) return <SafeAreaView style={{ flex: 1, backgroundColor: c.bg }}><Header title="Pergola" onBack={() => nav.goBack()} /></SafeAreaView>;
  const fmt = (v?: string | null) => v ? new Date(v).toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" }) : "—";
  const maint = subs.find((s) => s.offering === "maintenance"), elec = subs.find((s) => s.offering === "electronics");
  const spec = (p.spec ?? {}) as { enclosures?: { label?: string; type: string }[]; accessories?: { label?: string; type: string; qty: number }[]; type?: string };
  const chips = [spec.type ?? p.structure_type?.replace("_", " "), p.mounting?.replace("_", " "), ...(spec.enclosures ?? []).map((e) => e.label ?? e.type), ...(spec.accessories ?? []).map((a) => `${a.qty}× ${a.label ?? a.type}`)].filter(Boolean) as string[];
  const lastJob = jobs.filter((j) => ["completed_paid", "dispute_upheld"].includes(j.status)).sort((a, b) => (b.paid_at ?? b.updated_at).localeCompare(a.paid_at ?? a.updated_at))[0];
  const nextRem = reminders.sort((a, b) => a.due_at.localeCompare(b.due_at))[0];
  const Row = ({ icon, bg, fg, title, sub, onPress }: { icon: keyof typeof Ionicons.glyphMap; bg: string; fg: string; title: string; sub: string; onPress: () => void }) => <Pressable onPress={onPress} style={{ flexDirection: "row", alignItems: "center", gap: 12, backgroundColor: c.surface, borderWidth: 1, borderColor: c.border, borderRadius: 14, padding: 12, paddingHorizontal: 14 }}><View style={{ width: 40, height: 40, borderRadius: 12, backgroundColor: bg, alignItems: "center", justifyContent: "center" }}><Ionicons name={icon} size={20} color={fg} /></View><View style={{ flex: 1, gap: 2 }}><RNText style={S(14.5, "600")}>{title}</RNText><RNText style={S(12.5, "400", c.text4)}>{sub}</RNText></View><Ionicons name="chevron-forward" size={18} color={c.text4} /></Pressable>;
  return (
    <SafeAreaView edges={["top"]} style={{ flex: 1, backgroundColor: c.bg }}>
      <Header title={p.name} onBack={() => nav.goBack()} right={<Pressable onPress={() => Alert.alert("Remove pergola?", "Its history and documents stay in your account.", [{ text: "Keep", style: "cancel" }, { text: "Remove", style: "destructive", onPress: async () => { await api(`/pergolas/${p.id}`, { method: "DELETE" }); nav.goBack(); } }])} style={{ width: 40, height: 40, alignItems: "center", justifyContent: "center" }}><Ionicons name="trash-outline" size={20} color={c.text2} /></Pressable>} />
      <ScrollView contentContainerStyle={{ padding: 16, gap: 16 }}>
        <View style={{ height: 200, borderRadius: 20, overflow: "hidden", backgroundColor: c.hero, justifyContent: "flex-end", padding: 14 }}>{p.photo_url && <Image source={{ uri: p.photo_url }} style={{ position: "absolute", width: "100%", height: "100%" }} />}<View style={{ position: "absolute", left: 0, right: 0, bottom: 0, height: 100, backgroundColor: "rgba(0,0,0,.35)" }} /><RNText style={S(20, "800", "#fff")}>{p.name}</RNText><RNText style={S(13, "400", "rgba(255,255,255,.8)")}>{[p.structure_type?.replace("_", " "), p.brand, p.installed_at ? `installed ${fmt(p.installed_at)}` : null].filter(Boolean).join(" · ")}</RNText>{!!p.photos?.length && <View style={{ position: "absolute", top: 12, right: 12, height: 24, paddingHorizontal: 8, borderRadius: 999, backgroundColor: "rgba(0,0,0,.4)", justifyContent: "center" }}><RNText style={S(11.5, "600", "#fff")}>1 / {p.photos.length}</RNText></View>}</View>
        {chips.length > 0 && <View style={{ flexDirection: "row", flexWrap: "wrap", gap: 6 }}>{chips.map((k) => <View key={k} style={{ height: 28, paddingHorizontal: 10, borderRadius: 999, backgroundColor: c.surface2, justifyContent: "center" }}><RNText style={{ ...S(13, "600", c.text2), textTransform: "capitalize" }}>{k}</RNText></View>)}</View>}
        <View style={{ flexDirection: "row", backgroundColor: c.surface, borderWidth: 1, borderColor: c.border, borderRadius: 16, padding: 14, paddingHorizontal: 16 }}>{[["Width", p.width_ft], ["Length", p.length_ft], ["Height", p.height_ft]].map(([k, v], i) => <View key={k} style={{ flex: 1, gap: 2, paddingLeft: i ? 14 : 0, borderLeftWidth: i ? 1 : 0, borderLeftColor: c.border }}><RNText style={S(12, "600", c.text4)}>{k}</RNText><RNText style={S(18, "700")}>{v ? `${v} ft` : "—"}</RNText></View>)}</View>
        <View style={{ backgroundColor: c.surface, borderWidth: 1, borderColor: c.border, borderRadius: 16 }}>{[["Installed", fmt(p.installed_at), c.text], ["Last service", lastJob ? `${fmt(lastJob.paid_at)} · ${lastJob.title}` : "—", c.text], ["Next check", nextRem ? `${fmt(nextRem.due_at)} · ${nextRem.kind.replace(/_/g, " ")}` : "—", c.orange]].map(([k, v, col], i) => <View key={k as string} style={{ flexDirection: "row", justifyContent: "space-between", gap: 12, padding: 12, paddingHorizontal: 16, borderTopWidth: i ? 1 : 0, borderTopColor: c.border }}><RNText style={S(13.5, "400", c.text4)}>{k as string}</RNText><RNText style={{ flex: 1, textAlign: "right", ...S(14, "600", col as string) }}>{v as string}</RNText></View>)}</View>
        <View style={{ gap: 10 }}>
          <View style={{ flexDirection: "row", justifyContent: "space-between", alignItems: "center" }}><RNText style={S(16, "700")}>MrCare plans</RNText><Pressable onPress={() => nav.navigate("Tabs", { screen: "MrCare" })}><RNText style={S(13, "600", c.primary)}>{maint || elec ? "Manage" : "Get MrCare"}</RNText></Pressable></View>
          {elec ? <Pressable onPress={() => nav.navigate("ElectronicsClaim", { subscriptionId: elec.id, pergolaId: p.id })} style={{ flexDirection: "row", alignItems: "center", gap: 10, backgroundColor: c.okBg, borderRadius: 14, padding: 12 }}><View style={{ width: 36, height: 36, borderRadius: 10, backgroundColor: c.surface, alignItems: "center", justifyContent: "center" }}><Ionicons name="flash-outline" size={18} color={c.ok} /></View><View style={{ flex: 1, gap: 2 }}><RNText style={S(14, "600")}>Report an Electronics Issue</RNText><RNText style={S(12, "400", c.text3)}>Covered by your Electronics Protection Plan. Prefilled repair request.</RNText></View></Pressable> : null}
          {maint ? <Pressable onPress={() => nav.navigate("MaintenanceBooking", { subscriptionId: maint.id, pergolaId: p.id })} style={{ flexDirection: "row", alignItems: "center", gap: 10, backgroundColor: c.infoBg, borderRadius: 14, padding: 12 }}><View style={{ width: 36, height: 36, borderRadius: 10, backgroundColor: c.surface, alignItems: "center", justifyContent: "center" }}><Ionicons name="calendar-outline" size={18} color={c.info} /></View><View style={{ flex: 1, gap: 2 }}><RNText style={S(14, "600")}>Book a maintenance visit</RNText><RNText style={S(12, "400", c.text3)}>{maint.visits_per_year - maint.visits_used} of {maint.visits_per_year} visits left · no charge</RNText></View></Pressable> : null}
          <Pressable onPress={() => nav.navigate("Reminders", { pergolaId: p.id })} style={{ flexDirection: "row", alignItems: "center", gap: 10, backgroundColor: c.surface, borderWidth: 1, borderColor: c.border, borderRadius: 14, padding: 12 }}><View style={{ width: 36, height: 36, borderRadius: 10, backgroundColor: c.primarySoft, alignItems: "center", justifyContent: "center" }}><Ionicons name="alarm-outline" size={18} color={c.primary} /></View><View style={{ flex: 1, gap: 2 }}><RNText style={S(14, "600")}>Maintenance reminders</RNText><RNText style={S(12, "400", c.text3)}>{reminders.length ? `${reminders.length} active · next ${fmt(nextRem?.due_at)}` : "Based on the manufacturer's care schedule"}</RNText></View></Pressable>
        </View>
        <Row icon="folder-outline" bg={c.infoBg} fg={c.info} title="Documents" sub={`Plans, reports, receipts, warranty certificate · ${docs} files`} onPress={() => nav.navigate("Documents")} />
        <Row icon="build-outline" bg={c.primarySoft} fg={c.primary} title="Request repair or maintenance" sub="Prefilled with this pergola" onPress={() => nav.navigate("RepairForm")} />
        <View style={{ gap: 10 }}><RNText style={S(16, "700")}>Service history</RNText>{jobs.length === 0 && <RNText style={S(13, "400", c.text4)}>No requests for this pergola yet.</RNText>}{jobs.slice(0, 5).map((j) => <Pressable key={j.id} onPress={() => nav.navigate("RequestDetail", { id: j.id })} style={{ flexDirection: "row", alignItems: "center", gap: 12, backgroundColor: c.surface, borderWidth: 1, borderColor: c.border, borderRadius: 14, padding: 12, paddingHorizontal: 14 }}><View style={{ flex: 1 }}><RNText style={S(14, "600")}>{j.title}</RNText><RNText style={S(12, "400", c.text4)}>{j.request_code} · {fmt(j.created_at)}</RNText></View><RNText style={{ ...S(12, "600", c.text3), textTransform: "capitalize" }}>{j.status.replace(/_/g, " ")}</RNText></Pressable>)}</View>
      </ScrollView>
    </SafeAreaView>
  );
}
